// Konu paketleri: dar kapsamlı, zorluk seviyesi olmayan soru setleri (ilk şık doğru cevap)
const mk = cat => (q, ...o) => ({t: 'mc', cat, d: 'o', q, o});

const mp = mk('Plakalar'), mb = mk('Başkentler');
export const PACKS = [
  {id: 'plaka', name: 'Türkiye plakaları', icon: 'car', desc: 'İl plaka kodlarını ne kadar biliyorsun?', qs: [
    mp("61 hangi ilin plakasıdır?", "Trabzon", "Tunceli", "Tekirdağ", "Tokat"),
    mp("07 hangi ilin plakasıdır?", "Antalya", "Artvin", "Aydın", "Ağrı"),
    mp("Ağrı ilinin plaka kodu kaçtır?", "04", "03", "40", "02"),
    mp("34 hangi ilin plakasıdır?", "İstanbul", "İzmir", "Ağrı", "Hakkâri"),
    mp("Kars ilinin plaka kodu kaçtır?", "36", "46", "34", "37"),
    mp("54 hangi ilin plakasıdır?", "Sakarya", "Siirt", "Sivas", "Samsun"),
    mp("Bartın ilinin plaka kodu kaçtır?", "74", "73", "47", "76"),
    mp("81 hangi ilin plakasıdır?", "Düzce", "Denizli", "Diyarbakır", "Mersin"),
    mp("Mardin ilinin plaka kodu kaçtır?", "47", "57", "48", "46"),
    mp("40 hangi ilin plakasıdır?", "Kırşehir", "Kilis", "Karaman", "Konya"),
    mp("71 hangi ilin plakasıdır?", "Kırıkkale", "Kayseri", "Kütahya", "Kars"),
    mp("Gümüşhane ilinin plaka kodu kaçtır?", "29", "28", "19", "31"),
    mp("Karaman ilinin plaka kodu kaçtır?", "70", "69", "07", "72"),
    mp("Kırklareli ilinin plaka kodu kaçtır?", "39", "38", "29", "41"),
    mp("Rize ilinin plaka kodu kaçtır?", "53", "43", "54", "55"),
    mp("56 hangi ilin plakasıdır?", "Siirt", "Sivas", "Sakarya", "Samsun"),
    mp("Niğde ilinin plaka kodu kaçtır?", "51", "49", "50", "52"),
    mp("51 hangi ilin plakasıdır?", "Niğde", "Nevşehir", "Denizli", "Trabzon"),
    mp("18 hangi ilin plakasıdır?", "Çankırı", "Çorum", "Çanakkale", "Hakkâri"),
    mp("77 hangi ilin plakasıdır?", "Yalova", "Yozgat", "Rize", "Tunceli"),
    mp("01 hangi ilin plakasıdır?", "Adana", "Amasya", "Artvin", "Antalya"),
    mp("62 hangi ilin plakasıdır?", "Tunceli", "Tokat", "Tekirdağ", "Trabzon"),
    mp("Denizli ilinin plaka kodu kaçtır?", "20", "19", "22", "30"),
    mp("38 hangi ilin plakasıdır?", "Kayseri", "Karaman", "Konya", "Kahramanmaraş"),
    mp("11 hangi ilin plakasıdır?", "Bilecik", "Bingöl", "Bursa", "Balıkesir"),
    mp("Adıyaman ilinin plaka kodu kaçtır?", "02", "01", "20", "04"),
    mp("76 hangi ilin plakasıdır?", "Iğdır", "Isparta", "Bingöl", "Uşak"),
    mp("Sinop ilinin plaka kodu kaçtır?", "57", "75", "55", "58"),
    mp("15 hangi ilin plakasıdır?", "Burdur", "Bingöl", "Bartın", "Bolu"),
    mp("Muş ilinin plaka kodu kaçtır?", "49", "48", "39", "59"),
    mp("75 hangi ilin plakasıdır?", "Ardahan", "Ağrı", "Adana", "Amasya"),
    mp("İstanbul ilinin plaka kodu kaçtır?", "34", "44", "24", "33"),
    mp("Kahramanmaraş ilinin plaka kodu kaçtır?", "46", "56", "48", "47"),
    mp("Giresun ilinin plaka kodu kaçtır?", "28", "29", "26", "18"),
    mp("Ardahan ilinin plaka kodu kaçtır?", "75", "73", "76", "74"),
    mp("74 hangi ilin plakasıdır?", "Bartın", "Bolu", "Balıkesir", "Bayburt"),
    mp("39 hangi ilin plakasıdır?", "Kırklareli", "Kocaeli", "Kütahya", "Kahramanmaraş"),
    mp("48 hangi ilin plakasıdır?", "Muğla", "Malatya", "Mersin", "Manisa"),
    mp("Tokat ilinin plaka kodu kaçtır?", "60", "50", "70", "62"),
    mp("Iğdır ilinin plaka kodu kaçtır?", "76", "78", "67", "77"),
    mp("21 hangi ilin plakasıdır?", "Diyarbakır", "Denizli", "Düzce", "Gaziantep"),
    mp("50 hangi ilin plakasıdır?", "Nevşehir", "Niğde", "Sivas", "Tunceli"),
    mp("24 hangi ilin plakasıdır?", "Erzincan", "Edirne", "Elazığ", "Eskişehir"),
    mp("25 hangi ilin plakasıdır?", "Erzurum", "Erzincan", "Edirne", "Eskişehir"),
    mp("Aksaray ilinin plaka kodu kaçtır?", "68", "67", "69", "66"),
    mp("Konya ilinin plaka kodu kaçtır?", "42", "32", "24", "41"),
    mp("Yalova ilinin plaka kodu kaçtır?", "77", "67", "78", "79"),
    mp("46 hangi ilin plakasıdır?", "Kahramanmaraş", "Kocaeli", "Kütahya", "Konya"),
    mp("Bingöl ilinin plaka kodu kaçtır?", "12", "22", "02", "11"),
    mp("09 hangi ilin plakasıdır?", "Aydın", "Adana", "Ağrı", "Afyonkarahisar"),
    mp("Sakarya ilinin plaka kodu kaçtır?", "54", "56", "52", "55"),
    mp("Kayseri ilinin plaka kodu kaçtır?", "38", "28", "37", "48"),
    mp("Kırıkkale ilinin plaka kodu kaçtır?", "71", "73", "72", "81"),
    mp("33 hangi ilin plakasıdır?", "Mersin", "Muğla", "Manisa", "Mardin"),
    mp("08 hangi ilin plakasıdır?", "Artvin", "Adıyaman", "Aydın", "Amasya"),
    mp("Düzce ilinin plaka kodu kaçtır?", "81", "18", "80", "79"),
    mp("60 hangi ilin plakasıdır?", "Tokat", "Tunceli", "Trabzon", "Tekirdağ"),
    mp("59 hangi ilin plakasıdır?", "Tekirdağ", "Tokat", "Trabzon", "Tunceli"),
    mp("Nevşehir ilinin plaka kodu kaçtır?", "50", "51", "05", "40"),
    mp("49 hangi ilin plakasıdır?", "Muş", "Muğla", "Malatya", "Manisa"),
    mp("41 hangi ilin plakasıdır?", "Kocaeli", "Karaman", "Kahramanmaraş", "Kayseri"),
    mp("23 hangi ilin plakasıdır?", "Elazığ", "Eskişehir", "Erzincan", "Edirne"),
    mp("78 hangi ilin plakasıdır?", "Karabük", "Kars", "Kırklareli", "Kilis"),
    mp("03 hangi ilin plakasıdır?", "Afyonkarahisar", "Ardahan", "Ağrı", "Ankara"),
    mp("12 hangi ilin plakasıdır?", "Bingöl", "Bilecik", "Bartın", "Bayburt"),
    mp("02 hangi ilin plakasıdır?", "Adıyaman", "Adana", "Ardahan", "Ankara"),
    mp("36 hangi ilin plakasıdır?", "Kars", "Kütahya", "Karaman", "Konya"),
    mp("Muğla ilinin plaka kodu kaçtır?", "48", "46", "58", "38"),
    mp("31 hangi ilin plakasıdır?", "Hatay", "Hakkâri", "Kastamonu", "Ordu"),
    mp("37 hangi ilin plakasıdır?", "Kastamonu", "Konya", "Kocaeli", "Kırıkkale"),
    mp("79 hangi ilin plakasıdır?", "Kilis", "Karabük", "Konya", "Karaman"),
    mp("Aydın ilinin plaka kodu kaçtır?", "09", "11", "08", "19"),
    mp("Hatay ilinin plaka kodu kaçtır?", "31", "41", "13", "30"),
    mp("47 hangi ilin plakasıdır?", "Mardin", "Muş", "Malatya", "Muğla"),
    mp("19 hangi ilin plakasıdır?", "Çorum", "Çanakkale", "Çankırı", "Denizli"),
    mp("29 hangi ilin plakasıdır?", "Gümüşhane", "Gaziantep", "Giresun", "Zonguldak"),
    mp("70 hangi ilin plakasıdır?", "Karaman", "Konya", "Kilis", "Kayseri"),
    mp("32 hangi ilin plakasıdır?", "Isparta", "Iğdır", "Uşak", "Antalya"),
    mp("Ordu ilinin plaka kodu kaçtır?", "52", "25", "51", "42"),
    mp("80 hangi ilin plakasıdır?", "Osmaniye", "Ordu", "Kırşehir", "İstanbul"),
    mp("Çanakkale ilinin plaka kodu kaçtır?", "17", "07", "18", "15"),
    mp("Karabük ilinin plaka kodu kaçtır?", "78", "76", "80", "79"),
    mp("Mersin ilinin plaka kodu kaçtır?", "33", "32", "34", "43"),
    mp("Zonguldak ilinin plaka kodu kaçtır?", "67", "69", "57", "65"),
    mp("57 hangi ilin plakasıdır?", "Sinop", "Sivas", "Samsun", "Siirt"),
    mp("Kocaeli ilinin plaka kodu kaçtır?", "41", "39", "51", "14"),
    mp("63 hangi ilin plakasıdır?", "Şanlıurfa", "Şırnak", "Isparta", "Bitlis"),
    mp("Bitlis ilinin plaka kodu kaçtır?", "13", "03", "11", "12"),
    mp("35 hangi ilin plakasıdır?", "İzmir", "İstanbul", "Aydın", "Batman"),
    mp("04 hangi ilin plakasıdır?", "Ağrı", "Ardahan", "Amasya", "Antalya"),
    mp("05 hangi ilin plakasıdır?", "Amasya", "Ardahan", "Ağrı", "Antalya"),
    mp("69 hangi ilin plakasıdır?", "Bayburt", "Bitlis", "Burdur", "Bolu"),
    mp("10 hangi ilin plakasıdır?", "Balıkesir", "Burdur", "Bursa", "Bingöl"),
    mp("Amasya ilinin plaka kodu kaçtır?", "05", "50", "15", "03"),
    mp("Uşak ilinin plaka kodu kaçtır?", "64", "74", "54", "46"),
    mp("Manisa ilinin plaka kodu kaçtır?", "45", "54", "43", "55"),
    mp("72 hangi ilin plakasıdır?", "Batman", "Bursa", "Balıkesir", "Bingöl"),
    mp("26 hangi ilin plakasıdır?", "Eskişehir", "Elazığ", "Erzincan", "Erzurum"),
    mp("Afyonkarahisar ilinin plaka kodu kaçtır?", "03", "30", "02", "04"),
    mp("Tekirdağ ilinin plaka kodu kaçtır?", "59", "58", "57", "69"),
    mp("53 hangi ilin plakasıdır?", "Rize", "Çanakkale", "Zonguldak", "Yalova"),
    mp("Bayburt ilinin plaka kodu kaçtır?", "69", "71", "70", "67"),
    mp("Trabzon ilinin plaka kodu kaçtır?", "61", "51", "60", "62"),
    mp("Çankırı ilinin plaka kodu kaçtır?", "18", "28", "81", "20"),
    mp("Batman ilinin plaka kodu kaçtır?", "72", "73", "71", "27"),
    mp("73 hangi ilin plakasıdır?", "Şırnak", "Şanlıurfa", "Bilecik", "Gaziantep"),
    mp("Erzincan ilinin plaka kodu kaçtır?", "24", "23", "42", "26"),
    mp("Çorum ilinin plaka kodu kaçtır?", "19", "21", "29", "09"),
    mp("44 hangi ilin plakasıdır?", "Malatya", "Muş", "Mersin", "Manisa"),
    mp("İzmir ilinin plaka kodu kaçtır?", "35", "37", "33", "25"),
    mp("Tunceli ilinin plaka kodu kaçtır?", "62", "64", "52", "61"),
    mp("Gaziantep ilinin plaka kodu kaçtır?", "27", "29", "25", "37"),
    mp("13 hangi ilin plakasıdır?", "Bitlis", "Bartın", "Bingöl", "Burdur"),
    mp("68 hangi ilin plakasıdır?", "Aksaray", "Adıyaman", "Adana", "Aydın"),
    mp("Eskişehir ilinin plaka kodu kaçtır?", "26", "25", "28", "27"),
    mp("Şanlıurfa ilinin plaka kodu kaçtır?", "63", "61", "65", "36"),
    mp("Burdur ilinin plaka kodu kaçtır?", "15", "16", "05", "17"),
    mp("45 hangi ilin plakasıdır?", "Manisa", "Muğla", "Muş", "Mardin"),
    mp("Adana ilinin plaka kodu kaçtır?", "01", "03", "02", "10"),
    mp("30 hangi ilin plakasıdır?", "Hakkâri", "Hatay", "Sinop", "Siirt"),
    mp("58 hangi ilin plakasıdır?", "Sivas", "Sakarya", "Sinop", "Samsun"),
    mp("Bursa ilinin plaka kodu kaçtır?", "16", "14", "61", "17"),
    mp("Şırnak ilinin plaka kodu kaçtır?", "73", "63", "74", "75"),
    mp("Van ilinin plaka kodu kaçtır?", "65", "75", "63", "55"),
    mp("Kütahya ilinin plaka kodu kaçtır?", "43", "45", "41", "53"),
    mp("17 hangi ilin plakasıdır?", "Çanakkale", "Çankırı", "Çorum", "Bitlis"),
    mp("28 hangi ilin plakasıdır?", "Giresun", "Gaziantep", "Gümüşhane", "Konya"),
    mp("27 hangi ilin plakasıdır?", "Gaziantep", "Gümüşhane", "Giresun", "Bayburt"),
    mp("Hakkâri ilinin plaka kodu kaçtır?", "30", "29", "20", "28"),
    mp("22 hangi ilin plakasıdır?", "Edirne", "Erzurum", "Eskişehir", "Elazığ"),
    mp("52 hangi ilin plakasıdır?", "Ordu", "Osmaniye", "İstanbul", "Kırıkkale"),
    mp("Yozgat ilinin plaka kodu kaçtır?", "66", "65", "76", "67"),
    mp("Erzurum ilinin plaka kodu kaçtır?", "25", "24", "26", "27"),
    mp("67 hangi ilin plakasıdır?", "Zonguldak", "Düzce", "Siirt", "Ağrı"),
    mp("Bolu ilinin plaka kodu kaçtır?", "14", "15", "16", "24"),
    mp("Antalya ilinin plaka kodu kaçtır?", "07", "17", "05", "70"),
    mp("43 hangi ilin plakasıdır?", "Kütahya", "Kırıkkale", "Konya", "Kırklareli"),
    mp("Ankara ilinin plaka kodu kaçtır?", "06", "08", "04", "16"),
    mp("65 hangi ilin plakasıdır?", "Van", "Balıkesir", "Bayburt", "Kocaeli"),
    mp("Kastamonu ilinin plaka kodu kaçtır?", "37", "73", "36", "47"),
    mp("Artvin ilinin plaka kodu kaçtır?", "08", "18", "06", "10"),
    mp("Diyarbakır ilinin plaka kodu kaçtır?", "21", "11", "12", "22"),
    mp("16 hangi ilin plakasıdır?", "Bursa", "Bingöl", "Bolu", "Balıkesir"),
    mp("64 hangi ilin plakasıdır?", "Uşak", "Erzurum", "Ankara", "Kırklareli"),
    mp("06 hangi ilin plakasıdır?", "Ankara", "Aydın", "Aksaray", "Antalya"),
    mp("Edirne ilinin plaka kodu kaçtır?", "22", "23", "20", "32"),
    mp("55 hangi ilin plakasıdır?", "Samsun", "Sinop", "Sakarya", "Siirt"),
    mp("Kilis ilinin plaka kodu kaçtır?", "79", "78", "69", "80"),
    mp("14 hangi ilin plakasıdır?", "Bolu", "Balıkesir", "Burdur", "Bartın"),
    mp("42 hangi ilin plakasıdır?", "Konya", "Kars", "Kahramanmaraş", "Karaman"),
    mp("Siirt ilinin plaka kodu kaçtır?", "56", "46", "65", "54"),
    mp("Osmaniye ilinin plaka kodu kaçtır?", "80", "08", "78", "79"),
    mp("Elazığ ilinin plaka kodu kaçtır?", "23", "24", "25", "22"),
    mp("20 hangi ilin plakasıdır?", "Denizli", "Düzce", "Diyarbakır", "Bingöl"),
    mp("Isparta ilinin plaka kodu kaçtır?", "32", "33", "42", "31"),
    mp("Sivas ilinin plaka kodu kaçtır?", "58", "60", "57", "68"),
    mp("66 hangi ilin plakasıdır?", "Yozgat", "Yalova", "Erzurum", "Batman"),
    mp("Balıkesir ilinin plaka kodu kaçtır?", "10", "08", "09", "11"),
    mp("Kırşehir ilinin plaka kodu kaçtır?", "40", "04", "42", "39"),
    mp("Samsun ilinin plaka kodu kaçtır?", "55", "65", "57", "53"),
    mp("Bilecik ilinin plaka kodu kaçtır?", "11", "21", "13", "01"),
    mp("Malatya ilinin plaka kodu kaçtır?", "44", "45", "43", "46")
  ]},
  {id: 'baskent', name: 'Dünya başkentleri', icon: 'target', desc: 'Başkentleri ne kadar biliyorsun?', qs: [
    mb("Bosna Hersek ülkesinin başkenti hangisidir?", "Saraybosna", "Kopenhag", "Amsterdam", "Minsk"),
    mb("Sofya hangi ülkenin başkentidir?", "Bulgaristan", "Portekiz", "Bosna Hersek", "İspanya"),
    mb("İsviçre ülkesinin başkenti hangisidir?", "Bern", "Kişinev", "Saraybosna", "Amsterdam"),
    mb("Berlin hangi ülkenin başkentidir?", "Almanya", "Macaristan", "Hollanda", "İzlanda"),
    mb("Brasilia hangi ülkenin başkentidir?", "Brezilya", "Amerika Birleşik Devletleri", "Avustralya", "Küba"),
    mb("Hırvatistan ülkesinin başkenti hangisidir?", "Zagreb", "Kiev", "Madrid", "Bratislava"),
    mb("Podgorica hangi ülkenin başkentidir?", "Karadağ", "Yunanistan", "Malta", "Bulgaristan"),
    mb("Bağdat hangi ülkenin başkentidir?", "Irak", "Pakistan", "Ürdün", "Vietnam"),
    mb("Brezilya ülkesinin başkenti hangisidir?", "Brasilia", "Washington", "Canberra", "Havana"),
    mb("Pakistan ülkesinin başkenti hangisidir?", "İslamabad", "Dakka", "Katmandu", "Astana"),
    mb("Nijerya ülkesinin başkenti hangisidir?", "Abuja", "Kahire", "Addis Ababa", "Rabat"),
    mb("Yeni Zelanda ülkesinin başkenti hangisidir?", "Wellington", "Lima", "Meksiko", "Ottawa"),
    mb("Hanoi hangi ülkenin başkentidir?", "Vietnam", "Pakistan", "Çin", "Nepal"),
    mb("Bern hangi ülkenin başkentidir?", "İsviçre", "Moldova", "Bosna Hersek", "Hollanda"),
    mb("Brüksel hangi ülkenin başkentidir?", "Belçika", "Slovakya", "Bosna Hersek", "Hollanda"),
    mb("Yunanistan ülkesinin başkenti hangisidir?", "Atina", "Paris", "Varşova", "Üsküp"),
    mb("Suudi Arabistan ülkesinin başkenti hangisidir?", "Riyad", "Amman", "İslamabad", "Beyrut"),
    mb("Amman hangi ülkenin başkentidir?", "Ürdün", "Pakistan", "Endonezya", "Ermenistan"),
    mb("Nepal ülkesinin başkenti hangisidir?", "Katmandu", "Astana", "Şam", "Hanoi"),
    mb("Bratislava hangi ülkenin başkentidir?", "Slovakya", "Yunanistan", "Norveç", "Slovenya"),
    mb("Slovenya ülkesinin başkenti hangisidir?", "Ljubljana", "Tallinn", "Dublin", "Roma"),
    mb("Reykjavik hangi ülkenin başkentidir?", "İzlanda", "Hollanda", "Yunanistan", "Ukrayna"),
    mb("Macaristan ülkesinin başkenti hangisidir?", "Budapeşte", "Belgrad", "Riga", "Ljubljana"),
    mb("Cezayir ülkesinin başkenti hangisidir?", "Cezayir", "Kahire", "Abuja", "Nairobi"),
    mb("Stockholm hangi ülkenin başkentidir?", "İsveç", "Hollanda", "Sırbistan", "Arnavutluk"),
    mb("Prag hangi ülkenin başkentidir?", "Çekya", "Yunanistan", "Ukrayna", "Moldova"),
    mb("Moldova ülkesinin başkenti hangisidir?", "Kişinev", "Prag", "Brüksel", "Vilnius"),
    mb("Arnavutluk ülkesinin başkenti hangisidir?", "Tiran", "Bern", "Tallinn", "Atina"),
    mb("Canberra hangi ülkenin başkentidir?", "Avustralya", "Brezilya", "Yeni Zelanda", "Şili"),
    mb("Slovakya ülkesinin başkenti hangisidir?", "Bratislava", "Atina", "Oslo", "Ljubljana"),
    mb("Belçika ülkesinin başkenti hangisidir?", "Brüksel", "Bratislava", "Saraybosna", "Amsterdam"),
    mb("Belarus ülkesinin başkenti hangisidir?", "Minsk", "Kiev", "Londra", "Viyana"),
    mb("Havana hangi ülkenin başkentidir?", "Küba", "Avustralya", "Kanada", "Kolombiya"),
    mb("Romanya ülkesinin başkenti hangisidir?", "Bükreş", "Madrid", "Roma", "Bern"),
    mb("Paris hangi ülkenin başkentidir?", "Fransa", "Rusya", "Ukrayna", "Slovakya"),
    mb("Üsküp hangi ülkenin başkentidir?", "Kuzey Makedonya", "Hırvatistan", "Moldova", "İspanya"),
    mb("Almanya ülkesinin başkenti hangisidir?", "Berlin", "Budapeşte", "Amsterdam", "Reykjavik"),
    mb("Çekya ülkesinin başkenti hangisidir?", "Prag", "Atina", "Kiev", "Kişinev"),
    mb("Gürcistan ülkesinin başkenti hangisidir?", "Tiflis", "Beyrut", "Riyad", "Bakü"),
    mb("Küba ülkesinin başkenti hangisidir?", "Havana", "Canberra", "Ottawa", "Bogota"),
    mb("Japonya ülkesinin başkenti hangisidir?", "Tokyo", "Kabil", "Amman", "Hanoi"),
    mb("Portekiz ülkesinin başkenti hangisidir?", "Lizbon", "Paris", "Helsinki", "Zagreb"),
    mb("Bangkok hangi ülkenin başkentidir?", "Tayland", "Pakistan", "Hindistan", "Afganistan"),
    mb("Taşkent hangi ülkenin başkentidir?", "Özbekistan", "Afganistan", "Ürdün", "Endonezya"),
    mb("İzlanda ülkesinin başkenti hangisidir?", "Reykjavik", "Amsterdam", "Atina", "Kiev"),
    mb("Polonya ülkesinin başkenti hangisidir?", "Varşova", "Podgorica", "Prag", "Üsküp"),
    mb("Kahire hangi ülkenin başkentidir?", "Mısır", "Fas", "Etiyopya", "Libya"),
    mb("Fas ülkesinin başkenti hangisidir?", "Rabat", "Tunus", "Kahire", "Cezayir"),
    mb("Meksika ülkesinin başkenti hangisidir?", "Meksiko", "Havana", "Lima", "Buenos Aires"),
    mb("Çin ülkesinin başkenti hangisidir?", "Pekin", "Yeni Delhi", "Bangkok", "Şam"),
    mb("Seul hangi ülkenin başkentidir?", "Güney Kore", "Afganistan", "Irak", "Vietnam"),
    mb("Karadağ ülkesinin başkenti hangisidir?", "Podgorica", "Atina", "Valletta", "Sofya"),
    mb("Hindistan ülkesinin başkenti hangisidir?", "Yeni Delhi", "Bakü", "Taşkent", "Tokyo"),
    mb("Rabat hangi ülkenin başkentidir?", "Fas", "Tunus", "Mısır", "Cezayir"),
    mb("Şili ülkesinin başkenti hangisidir?", "Santiago", "Bogota", "Lima", "Washington"),
    mb("Şam hangi ülkenin başkentidir?", "Suriye", "Lübnan", "Nepal", "Ürdün"),
    mb("Malta ülkesinin başkenti hangisidir?", "Valletta", "Reykjavik", "Tiran", "Helsinki"),
    mb("Özbekistan ülkesinin başkenti hangisidir?", "Taşkent", "Kabil", "Amman", "Cakarta"),
    mb("Bakü hangi ülkenin başkentidir?", "Azerbaycan", "Hindistan", "Tayland", "Gürcistan"),
    mb("Tayland ülkesinin başkenti hangisidir?", "Bangkok", "İslamabad", "Yeni Delhi", "Kabil"),
    mb("Buenos Aires hangi ülkenin başkentidir?", "Arjantin", "Brezilya", "Kolombiya", "Peru"),
    mb("Ljubljana hangi ülkenin başkentidir?", "Slovenya", "Estonya", "İrlanda", "İtalya"),
    mb("Vilnius hangi ülkenin başkentidir?", "Litvanya", "Hırvatistan", "İzlanda", "Fransa"),
    mb("Lizbon hangi ülkenin başkentidir?", "Portekiz", "Fransa", "Finlandiya", "Hırvatistan"),
    mb("Budapeşte hangi ülkenin başkentidir?", "Macaristan", "Sırbistan", "Letonya", "Slovenya"),
    mb("Tokyo hangi ülkenin başkentidir?", "Japonya", "Afganistan", "Ürdün", "Vietnam"),
    mb("Tiran hangi ülkenin başkentidir?", "Arnavutluk", "İsviçre", "Estonya", "Yunanistan"),
    mb("Etiyopya ülkesinin başkenti hangisidir?", "Addis Ababa", "Tunus", "Kahire", "Rabat"),
    mb("Riga hangi ülkenin başkentidir?", "Letonya", "Arnavutluk", "İtalya", "İsviçre"),
    mb("Zagreb hangi ülkenin başkentidir?", "Hırvatistan", "Ukrayna", "İspanya", "Slovakya"),
    mb("Mısır ülkesinin başkenti hangisidir?", "Kahire", "Rabat", "Addis Ababa", "Trablus"),
    mb("Dublin hangi ülkenin başkentidir?", "İrlanda", "Portekiz", "Çekya", "Slovakya"),
    mb("Pekin hangi ülkenin başkentidir?", "Çin", "Hindistan", "Tayland", "Suriye"),
    mb("Yeni Delhi hangi ülkenin başkentidir?", "Hindistan", "Azerbaycan", "Özbekistan", "Japonya"),
    mb("Afganistan ülkesinin başkenti hangisidir?", "Kabil", "Riyad", "Katmandu", "Manila"),
    mb("Kişinev hangi ülkenin başkentidir?", "Moldova", "Çekya", "Belçika", "Litvanya"),
    mb("Kabil hangi ülkenin başkentidir?", "Afganistan", "Suudi Arabistan", "Nepal", "Filipinler"),
    mb("Norveç ülkesinin başkenti hangisidir?", "Oslo", "Atina", "Podgorica", "Kişinev"),
    mb("Astana hangi ülkenin başkentidir?", "Kazakistan", "Japonya", "Çin", "Suudi Arabistan"),
    mb("Roma hangi ülkenin başkentidir?", "İtalya", "Danimarka", "Rusya", "Macaristan"),
    mb("Washington hangi ülkenin başkentidir?", "Amerika Birleşik Devletleri", "Küba", "Peru", "Kanada"),
    mb("Bangladeş ülkesinin başkenti hangisidir?", "Dakka", "Tokyo", "Seul", "Bağdat"),
    mb("Trablus hangi ülkenin başkentidir?", "Libya", "Etiyopya", "Fas", "Nijerya"),
    mb("Kopenhag hangi ülkenin başkentidir?", "Danimarka", "İsviçre", "Avusturya", "İzlanda"),
    mb("Amerika Birleşik Devletleri ülkesinin başkenti hangisidir?", "Washington", "Havana", "Lima", "Ottawa"),
    mb("Tunus ülkesinin başkenti hangisidir?", "Tunus", "Kahire", "Rabat", "Addis Ababa"),
    mb("Riyad hangi ülkenin başkentidir?", "Suudi Arabistan", "Ürdün", "Pakistan", "Lübnan"),
    mb("Moskova hangi ülkenin başkentidir?", "Rusya", "Belçika", "Ukrayna", "Slovenya"),
    mb("Avusturya ülkesinin başkenti hangisidir?", "Viyana", "Madrid", "Dublin", "Saraybosna"),
    mb("Madrid hangi ülkenin başkentidir?", "İspanya", "Slovakya", "İtalya", "Slovenya"),
    mb("Arjantin ülkesinin başkenti hangisidir?", "Buenos Aires", "Brasilia", "Bogota", "Lima"),
    mb("Kiev hangi ülkenin başkentidir?", "Ukrayna", "Fransa", "Rusya", "Moldova"),
    mb("Belgrad hangi ülkenin başkentidir?", "Sırbistan", "Macaristan", "Fransa", "Karadağ"),
    mb("Güney Kore ülkesinin başkenti hangisidir?", "Seul", "Kabil", "Bağdat", "Hanoi"),
    mb("Amsterdam hangi ülkenin başkentidir?", "Hollanda", "Danimarka", "Norveç", "Litvanya"),
    mb("Cakarta hangi ülkenin başkentidir?", "Endonezya", "Tayland", "Pakistan", "Afganistan"),
    mb("Tunus hangi ülkenin başkentidir?", "Tunus", "Mısır", "Fas", "Etiyopya"),
    mb("Endonezya ülkesinin başkenti hangisidir?", "Cakarta", "Bangkok", "İslamabad", "Kabil"),
    mb("Fransa ülkesinin başkenti hangisidir?", "Paris", "Moskova", "Kiev", "Bratislava"),
    mb("Sırbistan ülkesinin başkenti hangisidir?", "Belgrad", "Budapeşte", "Paris", "Podgorica"),
    mb("Helsinki hangi ülkenin başkentidir?", "Finlandiya", "Belçika", "Çekya", "İzlanda"),
    mb("Katmandu hangi ülkenin başkentidir?", "Nepal", "Kazakistan", "Suriye", "Vietnam"),
    mb("Viyana hangi ülkenin başkentidir?", "Avusturya", "İspanya", "İrlanda", "Bosna Hersek"),
    mb("Manila hangi ülkenin başkentidir?", "Filipinler", "Suudi Arabistan", "Afganistan", "Kazakistan"),
    mb("Azerbaycan ülkesinin başkenti hangisidir?", "Bakü", "Yeni Delhi", "Bangkok", "Tiflis"),
    mb("Nairobi hangi ülkenin başkentidir?", "Kenya", "Mısır", "Fas", "Cezayir"),
    mb("Estonya ülkesinin başkenti hangisidir?", "Tallinn", "Dublin", "Paris", "Berlin"),
    mb("Bogota hangi ülkenin başkentidir?", "Kolombiya", "Amerika Birleşik Devletleri", "Avustralya", "Brezilya"),
    mb("Tallinn hangi ülkenin başkentidir?", "Estonya", "İrlanda", "Fransa", "Almanya"),
    mb("Ermenistan ülkesinin başkenti hangisidir?", "Erivan", "Bakü", "Astana", "Katmandu"),
    mb("Libya ülkesinin başkenti hangisidir?", "Trablus", "Addis Ababa", "Rabat", "Abuja"),
    mb("Letonya ülkesinin başkenti hangisidir?", "Riga", "Tiran", "Roma", "Bern"),
    mb("Litvanya ülkesinin başkenti hangisidir?", "Vilnius", "Zagreb", "Reykjavik", "Paris"),
    mb("İran ülkesinin başkenti hangisidir?", "Tahran", "Şam", "Kabil", "Hanoi"),
    mb("Tahran hangi ülkenin başkentidir?", "İran", "Suriye", "Afganistan", "Vietnam"),
    mb("Bulgaristan ülkesinin başkenti hangisidir?", "Sofya", "Lizbon", "Saraybosna", "Madrid"),
    mb("Wellington hangi ülkenin başkentidir?", "Yeni Zelanda", "Peru", "Meksika", "Kanada"),
    mb("Vietnam ülkesinin başkenti hangisidir?", "Hanoi", "İslamabad", "Pekin", "Katmandu"),
    mb("Kuzey Makedonya ülkesinin başkenti hangisidir?", "Üsküp", "Zagreb", "Kişinev", "Madrid"),
    mb("Dakka hangi ülkenin başkentidir?", "Bangladeş", "Japonya", "Güney Kore", "Irak"),
    mb("Kenya ülkesinin başkenti hangisidir?", "Nairobi", "Kahire", "Rabat", "Cezayir"),
    mb("Abuja hangi ülkenin başkentidir?", "Nijerya", "Mısır", "Etiyopya", "Fas"),
    mb("Minsk hangi ülkenin başkentidir?", "Belarus", "Ukrayna", "Birleşik Krallık", "Avusturya"),
    mb("Atina hangi ülkenin başkentidir?", "Yunanistan", "Fransa", "Polonya", "Kuzey Makedonya"),
    mb("Suriye ülkesinin başkenti hangisidir?", "Şam", "Beyrut", "Katmandu", "Amman"),
    mb("Lübnan ülkesinin başkenti hangisidir?", "Beyrut", "Astana", "Bağdat", "Tahran"),
    mb("Kolombiya ülkesinin başkenti hangisidir?", "Bogota", "Washington", "Canberra", "Brasilia"),
    mb("Addis Ababa hangi ülkenin başkentidir?", "Etiyopya", "Tunus", "Mısır", "Fas"),
    mb("Saraybosna hangi ülkenin başkentidir?", "Bosna Hersek", "Danimarka", "Hollanda", "Belarus"),
    mb("Kazakistan ülkesinin başkenti hangisidir?", "Astana", "Tokyo", "Pekin", "Riyad"),
    mb("Ottawa hangi ülkenin başkentidir?", "Kanada", "Amerika Birleşik Devletleri", "Küba", "Yeni Zelanda"),
    mb("Irak ülkesinin başkenti hangisidir?", "Bağdat", "İslamabad", "Amman", "Hanoi"),
    mb("Peru ülkesinin başkenti hangisidir?", "Lima", "Wellington", "Brasilia", "Havana"),
    mb("Lima hangi ülkenin başkentidir?", "Peru", "Yeni Zelanda", "Brezilya", "Küba"),
    mb("Birleşik Krallık ülkesinin başkenti hangisidir?", "Londra", "Helsinki", "Viyana", "Prag"),
    mb("Beyrut hangi ülkenin başkentidir?", "Lübnan", "Kazakistan", "Irak", "İran"),
    mb("Meksiko hangi ülkenin başkentidir?", "Meksika", "Küba", "Peru", "Arjantin"),
    mb("Danimarka ülkesinin başkenti hangisidir?", "Kopenhag", "Bern", "Viyana", "Reykjavik"),
    mb("Filipinler ülkesinin başkenti hangisidir?", "Manila", "Riyad", "Kabil", "Astana"),
    mb("Rusya ülkesinin başkenti hangisidir?", "Moskova", "Brüksel", "Kiev", "Ljubljana"),
    mb("İrlanda ülkesinin başkenti hangisidir?", "Dublin", "Lizbon", "Prag", "Bratislava"),
    mb("Avustralya ülkesinin başkenti hangisidir?", "Canberra", "Brasilia", "Wellington", "Santiago"),
    mb("Santiago hangi ülkenin başkentidir?", "Şili", "Kolombiya", "Peru", "Amerika Birleşik Devletleri"),
    mb("Kanada ülkesinin başkenti hangisidir?", "Ottawa", "Washington", "Havana", "Wellington"),
    mb("Oslo hangi ülkenin başkentidir?", "Norveç", "Yunanistan", "Karadağ", "Moldova"),
    mb("Ürdün ülkesinin başkenti hangisidir?", "Amman", "İslamabad", "Cakarta", "Erivan"),
    mb("Finlandiya ülkesinin başkenti hangisidir?", "Helsinki", "Brüksel", "Prag", "Reykjavik"),
    mb("Cezayir hangi ülkenin başkentidir?", "Cezayir", "Mısır", "Nijerya", "Kenya"),
    mb("Varşova hangi ülkenin başkentidir?", "Polonya", "Karadağ", "Çekya", "Kuzey Makedonya"),
    mb("Valletta hangi ülkenin başkentidir?", "Malta", "İzlanda", "Arnavutluk", "Finlandiya"),
    mb("Tiflis hangi ülkenin başkentidir?", "Gürcistan", "Lübnan", "Suudi Arabistan", "Azerbaycan"),
    mb("Ukrayna ülkesinin başkenti hangisidir?", "Kiev", "Paris", "Moskova", "Kişinev"),
    mb("Londra hangi ülkenin başkentidir?", "Birleşik Krallık", "Finlandiya", "Avusturya", "Çekya"),
    mb("Bükreş hangi ülkenin başkentidir?", "Romanya", "İspanya", "İtalya", "İsviçre"),
    mb("İspanya ülkesinin başkenti hangisidir?", "Madrid", "Bratislava", "Roma", "Ljubljana"),
    mb("İsveç ülkesinin başkenti hangisidir?", "Stockholm", "Amsterdam", "Belgrad", "Tiran"),
    mb("Erivan hangi ülkenin başkentidir?", "Ermenistan", "Azerbaycan", "Kazakistan", "Nepal"),
    mb("İtalya ülkesinin başkenti hangisidir?", "Roma", "Kopenhag", "Moskova", "Budapeşte"),
    mb("Hollanda ülkesinin başkenti hangisidir?", "Amsterdam", "Kopenhag", "Oslo", "Vilnius"),
    mb("İslamabad hangi ülkenin başkentidir?", "Pakistan", "Bangladeş", "Nepal", "Kazakistan")
  ]}
];
