// Zuqio ek soru havuzu · bölüm 2 (Spor, Futbol, Sinema ve dizi, Müzik, Edebiyat)
const m = (cat, d, q, ...o) => ({t: 'mc', cat, d, q, o});
const n = (cat, d, q, a, unit, tolAbs) => tolAbs ? {t: 'num', cat, d, q, a, unit, tolAbs} : {t: 'num', cat, d, q, a, unit};

export const MORE2 = [
  /* ================= Spor ================= */
  m('Spor','k','Tenis oynarken topa vurmak için ne kullanılır?','Raket','Sopa','Kürek','Eldiven'),
  m('Spor','k','Muhammed Ali hangi spor dalıyla ünlenmiştir?','Boks','Güreş','Tenis','Atletizm'),
  m('Spor','k','Kadın Voleybol A Milli Takımı’nın lakabı nedir?','Filenin Sultanları','Bizim Kızlar','Kartal Kızlar','Ay-Yıldızlılar'),
  m('Spor','k','Kırkpınar Yağlı Güreşleri hangi ilimizde yapılır?','Edirne','Bursa','Konya','Sivas'),
  m('Spor','k','Usain Bolt hangi ülkenin sporcusudur?','Jamaika','ABD','Kenya','Güney Afrika'),
  m('Spor','k','Basketbolda üç sayı çizgisinin gerisinden atılan basket kaç sayıdır?','3','2','1','4'),
  n('Spor','k','Boks ringinin kaç köşesi vardır?',4,'köşe'),
  m('Spor','o','Buz üzerinde taş kaydırılıp fırçayla yolu temizlenen spor hangisidir?','Curling','Hokey','Buz pateni','Bobsley'),
  m('Spor','o','Michael Phelps hangi spor dalında yarışmıştır?','Yüzme','Atletizm','Jimnastik','Boks'),
  m('Spor','o','Michael Jordan altı şampiyonluğu hangi takımla kazanmıştır?','Chicago Bulls','Los Angeles Lakers','Boston Celtics','Miami Heat'),
  m('Spor','o','Rafael Nadal en çok hangi turnuvada şampiyon olmuştur?','Roland Garros','Wimbledon','ABD Açık','Avustralya Açık'),
  m('Spor','o','Halil Mutlu hangi spor dalında şampiyon olmuştur?','Halter','Güreş','Boks','Judo'),
  m('Spor','o','A Milli Erkek Basketbol Takımı’nın lakabı nedir?','12 Dev Adam','Filenin Efeleri','Ay-Yıldızlılar','Kara Kartallar'),
  m('Spor','o','Wimbledon turnuvası hangi zeminde oynanır?','Çim','Toprak','Sert zemin','Halı'),
  m('Spor','o','Roland Garros turnuvası hangi zeminde oynanır?','Toprak','Çim','Sert zemin','Halı'),
  m('Spor','o','Triatlonda hangi üç branş yer alır?','Yüzme, bisiklet, koşu','Koşu, atlama, atma','Kürek, yüzme, koşu','Bisiklet, güreş, koşu'),
  m('Spor','o','Taekwondo hangi ülkede ortaya çıkmıştır?','Güney Kore','Japonya','Çin','Tayland'),
  m('Spor','o','Karate hangi ülkede ortaya çıkmıştır?','Japonya','Çin','Güney Kore','Hindistan'),
  m('Spor','o','Tenis skorunda sıfır sayısı için ne denir?','Love','Zero','Ace','Deuce'),
  n('Spor','o','Tenisin dört büyük (Grand Slam) turnuvasından kaç tanesi vardır?',4,'turnuva'),
  n('Spor','o','Beyzbolda bir takım sahada kaç oyuncuyla savunma yapar?',9,'oyuncu'),
  n('Spor','o','Standart bir golf sahasında kaç delik vardır?',18,'delik'),
  m('Spor','z','Tokyo 2020 Olimpiyatları’nda okçulukta altın madalya kazanan Türk sporcu kimdir?','Mete Gazoz','Yasemin Ecem Anagöz','Evren Çağıran','Sinan Yıldız'),
  m('Spor','z','Usain Bolt’un 100 metre dünya rekoru kaç saniyedir?','9,58','9,69','9,72','9,81'),
  m('Spor','z','Olimpiyat tarihinde en çok madalya kazanan sporcu kimdir?','Michael Phelps','Usain Bolt','Larisa Latınina','Carl Lewis'),
  m('Spor','z','Amerikan futbolunda bir touchdown kaç sayı değerindedir?','6','3','7','1'),
  m('Spor','z','Aşağıdakilerden hangisi eskrimin üç dalından biri değildir?','Mızrak','Epe','Flöre','Kılıç'),
  m('Spor','z','Tour de France’ta lider sürücü hangi renk formayı giyer?','Sarı','Yeşil','Kırmızı','Mavi'),

  /* ================= Futbol ================= */
  m('Futbol','k','Fenerbahçe’nin forma renkleri nelerdir?','Sarı-lacivert','Sarı-kırmızı','Siyah-beyaz','Bordo-mavi'),
  m('Futbol','k','Galatasaray’ın forma renkleri nelerdir?','Sarı-kırmızı','Sarı-lacivert','Siyah-beyaz','Bordo-mavi'),
  m('Futbol','k','Beşiktaş’ın forma renkleri nelerdir?','Siyah-beyaz','Sarı-kırmızı','Sarı-lacivert','Yeşil-beyaz'),
  m('Futbol','k','Trabzonspor’un forma renkleri nelerdir?','Bordo-mavi','Siyah-beyaz','Sarı-kırmızı','Kırmızı-beyaz'),
  m('Futbol','k','Lionel Messi hangi ülkenin millî futbolcusudur?','Arjantin','Brezilya','İspanya','Uruguay'),
  m('Futbol','k','Cristiano Ronaldo hangi ülkenin millî futbolcusudur?','Portekiz','İspanya','Brezilya','Fransa'),
  n('Futbol','k','Dünya Kupası kaç yılda bir yapılır?',4,'yılda'),
  m('Futbol','o','Beşiktaş’ın lakabı nedir?','Kara Kartal','Cim Bom','Kanarya','Fırtına'),
  m('Futbol','o','Galatasaray’ın lakabı nedir?','Cim Bom','Kanarya','Kara Kartal','Bordo Mavililer'),
  m('Futbol','o','Hakan Şükür’ün lakabı nedir?','Boğa','Kartal','Aslan','Kurt'),
  m('Futbol','o','Rüştü Reçber hangi mevkide oynamıştır?','Kaleci','Stoper','Orta saha','Forvet'),
  m('Futbol','o','Maradona’nın 1986 Dünya Kupası’nda İngiltere’ye attığı ünlü gole ne ad verilir?','Tanrı’nın Eli','Altın Gol','Kartal Vuruşu','Makas'),
  m('Futbol','o','2010 Dünya Kupası’nı hangi ülke kazandı?','İspanya','Hollanda','Almanya','Brezilya'),
  m('Futbol','o','2002 Dünya Kupası’nı hangi ülke kazandı?','Brezilya','Almanya','Türkiye','İtalya'),
  m('Futbol','o','2006 Dünya Kupası’nı hangi ülke kazandı?','İtalya','Fransa','Almanya','Portekiz'),
  m('Futbol','o','2014 Dünya Kupası’nı hangi ülke kazandı?','Almanya','Arjantin','Brezilya','Hollanda'),
  m('Futbol','o','Old Trafford stadyumu hangi kulübün ev sahibi stadıdır?','Manchester United','Liverpool','Chelsea','Arsenal'),
  m('Futbol','o','Camp Nou hangi kulübün stadyumudur?','Barcelona','Real Madrid','Atlético Madrid','Valencia'),
  m('Futbol','o','Şampiyonlar Ligi’ni en çok kazanan kulüp hangisidir?','Real Madrid','Milan','Bayern Münih','Liverpool'),
  m('Futbol','o','Liverpool taraftarının marşı olarak bilinen şarkı hangisidir?','You’ll Never Walk Alone','We Are the Champions','Seven Nation Army','Football’s Coming Home'),
  m('Futbol','o','Süper Lig’de en çok şampiyonluk kazanan kulüp hangisidir?','Galatasaray','Fenerbahçe','Beşiktaş','Trabzonspor'),
  n('Futbol','o','Futbolda penaltı noktası kaleye kaç metre uzaklıktadır?',11,'metre'),
  m('Futbol','z','Altın Top ödülünü kazanan tek kaleci kimdir?','Lev Yaşin','Gianluigi Buffon','Iker Casillas','Manuel Neuer'),
  m('Futbol','z','Zinedine Zidane 1998 Dünya Kupası finalinde kaç gol attı?','2','1','3','0'),
  m('Futbol','z','EURO 1992’yi sürpriz biçimde hangi ülke kazandı?','Danimarka','Hollanda','Almanya','İsveç'),
  m('Futbol','z','Galatasaray 2000’de UEFA Süper Kupa’yı hangi takımı yenerek kazandı?','Real Madrid','Milan','Barcelona','Bayern Münih'),
  m('Futbol','z','Türkiye, EURO 2008 çeyrek finalinde hangi takımı penaltılarla elemiştir?','Hırvatistan','Almanya','Çek Cumhuriyeti','İspanya'),
  m('Futbol','z','EURO 2016’yı hangi ülke kazandı?','Portekiz','Fransa','Almanya','İtalya'),
  m('Futbol','z','EURO 2012’yi hangi ülke kazandı?','İspanya','İtalya','Almanya','Hollanda'),

  /* ================= Sinema ve dizi ================= */
  m('Sinema ve dizi','k','Örümcek Adam’ın gerçek adı nedir?','Peter Parker','Bruce Wayne','Tony Stark','Clark Kent'),
  m('Sinema ve dizi','k','Shrek hangi renktir?','Yeşil','Mavi','Kırmızı','Turuncu'),
  m('Sinema ve dizi','k','“Frozen” filminde yaşayan ve konuşan kardan adamın adı nedir?','Olaf','Sven','Kristof','Hans'),
  m('Sinema ve dizi','k','“Toy Story”de kovboy oyuncağın adı nedir?','Woody','Buzz','Rex','Slinky'),
  m('Sinema ve dizi','k','Harry Potter serisinin yazarı kimdir?','J. K. Rowling','Roald Dahl','J. R. R. Tolkien','C. S. Lewis'),
  m('Sinema ve dizi','k','Walt Disney’in en ünlü fare karakteri hangisidir?','Mickey Mouse','Jerry','Speedy Gonzales','Stuart Little'),
  m('Sinema ve dizi','k','Pokémon serisinin sarı renkli en ünlü karakteri hangisidir?','Pikachu','Charmander','Bulbasaur','Snorlax'),
  m('Sinema ve dizi','k','Simpsonlar’da Bart’ın babasının adı nedir?','Homer','Ned','Moe','Barney'),
  n('Sinema ve dizi','k','Pamuk Prenses’in yanında kaç cüce yaşar?',7,'cüce'),
  m('Sinema ve dizi','o','“Yüzüklerin Efendisi” üçlemesinin yönetmeni kimdir?','Peter Jackson','Steven Spielberg','Christopher Nolan','Ridley Scott'),
  m('Sinema ve dizi','o','“Yüzüklerin Efendisi” kitaplarının yazarı kimdir?','J. R. R. Tolkien','C. S. Lewis','George R. R. Martin','Roald Dahl'),
  m('Sinema ve dizi','o','“Avatar” filminin yönetmeni kimdir?','James Cameron','George Lucas','Steven Spielberg','Peter Jackson'),
  m('Sinema ve dizi','o','“Forrest Gump” filminde başrolü kim oynamıştır?','Tom Hanks','Brad Pitt','Leonardo DiCaprio','Robin Williams'),
  m('Sinema ve dizi','o','“Matrix” filminde Neo karakterini kim canlandırmıştır?','Keanu Reeves','Brad Pitt','Tom Cruise','Will Smith'),
  m('Sinema ve dizi','o','Batman’in yaşadığı kurgusal şehir hangisidir?','Gotham','Metropolis','Springfield','Star City'),
  m('Sinema ve dizi','o','“Pulp Fiction” filminin yönetmeni kimdir?','Quentin Tarantino','Martin Scorsese','Francis Ford Coppola','David Fincher'),
  m('Sinema ve dizi','o','Şarlo (Charlie Chaplin) hangi dönemin yıldızıdır?','Sessiz sinema','Renkli sinema','Dijital sinema','Animasyon'),
  m('Sinema ve dizi','o','“Tosun Paşa” filminin başrolünde hangi oyuncu yer almıştır?','Kemal Sunal','Şener Şen','Adile Naşit','Cüneyt Arkın'),
  m('Sinema ve dizi','o','“Çiçek Abbas” filminin başrol oyuncusu kimdir?','Şener Şen','Kemal Sunal','Tarık Akan','Münir Özkul'),
  m('Sinema ve dizi','o','“Ezel” dizisinde başrol oyuncusu kimdir?','Kenan İmirzalıoğlu','Kıvanç Tatlıtuğ','Halit Ergenç','Engin Akyürek'),
  m('Sinema ve dizi','o','“Breaking Bad” dizisinin ana karakterinin adı nedir?','Walter White','Jesse Pinkman','Saul Goodman','Hank Schrader'),
  m('Sinema ve dizi','o','“Squid Game” dizisi hangi ülkede çekilmiştir?','Güney Kore','Japonya','Çin','Tayland'),
  m('Sinema ve dizi','o','Sherlock Holmes karakterini yaratan yazar kimdir?','Arthur Conan Doyle','Agatha Christie','Edgar Allan Poe','Jules Verne'),
  m('Sinema ve dizi','o','“Sünger Bob”un yaşadığı yerin adı nedir?','Bikini Kasabası','Atlantis','Springfield','Gotham'),
  n('Sinema ve dizi','o','“Yüzüklerin Efendisi” serisi kaç filmden oluşan bir üçlemedir?',3,'film'),
  m('Sinema ve dizi','z','“Esaretin Bedeli” filminin dayandığı öykünün yazarı kimdir?','Stephen King','John Grisham','Dean Koontz','Michael Crichton'),
  m('Sinema ve dizi','z','“Friends” dizisinde karakterlerin sık sık buluştuğu kafenin adı nedir?','Central Perk','Moe’s Tavern','Cheers','Luke’s Diner'),
  m('Sinema ve dizi','z','“Gladyatör” filminde Maximus karakterini kim canlandırmıştır?','Russell Crowe','Mel Gibson','Joaquin Phoenix','Brad Pitt'),
  m('Sinema ve dizi','z','“Kış Uykusu” filminin yönetmeni Nuri Bilge Ceylan hangi festivalde Altın Palmiye ödülü almıştır?','Cannes','Berlin','Venedik','Sundance'),
  m('Sinema ve dizi','z','Simpsonlar’ın yaşadığı kurgusal kasabanın adı nedir?','Springfield','Shelbyville','Quahog','South Park'),

  /* ================= Müzik ================= */
  m('Müzik','k','Tarkan’ın lakabı nedir?','Megastar','Süperstar','Kral','Sultan'),
  m('Müzik','k','Sezen Aksu’nun lakabı nedir?','Minik Serçe','Megastar','Diva','Süperstar'),
  m('Müzik','k','Müslüm Gürses’in lakabı nedir?','Müslüm Baba','Ferdi Baba','İbo','Efsane'),
  m('Müzik','k','Michael Jackson’ın lakabı nedir?','Pop Kralı','Rock Kralı','Soul Kralı','Caz Kralı'),
  m('Müzik','k','Darbuka hangi çalgı grubuna girer?','Vurmalı','Telli','Üflemeli','Yaylı'),
  m('Müzik','k','Flüt hangi çalgı grubuna girer?','Üflemeli','Telli','Vurmalı','Yaylı'),
  m('Müzik','k','Bir orkestrayı yöneten kişiye ne ad verilir?','Şef','Solist','Korist','Düzenleyici'),
  m('Müzik','o','Bağlama hangi çalgı grubuna girer?','Telli','Üflemeli','Vurmalı','Yaylı'),
  m('Müzik','o','Ajda Pekkan’ın lakabı nedir?','Süperstar','Megastar','Diva','Minik Serçe'),
  m('Müzik','o','Tarkan’ın “Şımarık” şarkısıyla ünlendiği albüm hangi yıl çıkmıştır?','1997','1987','2003','1992'),
  m('Müzik','o','Queen grubunun vokalisti kimdir?','Freddie Mercury','Mick Jagger','Robert Plant','Bono'),
  m('Müzik','o','Rolling Stones grubunun solisti kimdir?','Mick Jagger','Freddie Mercury','Paul McCartney','Roger Daltrey'),
  m('Müzik','o','ABBA grubu hangi ülkeden çıkmıştır?','İsveç','Norveç','Danimarka','Finlandiya'),
  m('Müzik','o','Bob Marley hangi ülkenin sanatçısıdır?','Jamaika','Küba','Brezilya','Nijerya'),
  m('Müzik','o','“Fındıkkıran” balesinin bestecisi kimdir?','Çaykovski','Mozart','Chopin','Vivaldi'),
  m('Müzik','o','Chopin hangi ülkede doğmuştur?','Polonya','Fransa','Almanya','Avusturya'),
  m('Müzik','o','Müzikte “piano” terimi ne anlama gelir?','Yavaş ve hafif çal','Hızlı çal','Gürültülü çal','Sürekli çal'),
  m('Müzik','o','Arabesk müziğin öncüsü olarak bilinen sanatçı kimdir?','Orhan Gencebay','Barış Manço','Cem Karaca','Zeki Müren'),
  m('Müzik','o','Âşık Veysel hangi çalgıyla özdeşleşmiştir?','Bağlama (saz)','Keman','Ney','Kanun'),
  n('Müzik','o','Sertab Erener Eurovision’u hangi yıl kazandı?',2003,'yılı',3),
  m('Müzik','z','Beethoven’ın “Elise’e Mektup” eseri hangi çalgı için yazılmıştır?','Piyano','Keman','Çello','Org'),
  m('Müzik','z','“Mavi Tuna Valsi”nin bestecisi kimdir?','Johann Strauss','Mozart','Schubert','Haydn'),
  m('Müzik','z','“Carmen” operasının bestecisi kimdir?','Bizet','Verdi','Puccini','Rossini'),
  m('Müzik','z','“La Traviata” operasının bestecisi kimdir?','Verdi','Puccini','Rossini','Bizet'),
  m('Müzik','z','“Madama Butterfly” operasının bestecisi kimdir?','Puccini','Verdi','Mozart','Wagner'),
  m('Müzik','z','Müzikte “allegro” terimi ne anlama gelir?','Hızlı','Yavaş','Hafif','Yumuşak'),
  m('Müzik','z','Müzikte “adagio” terimi ne anlama gelir?','Yavaş','Hızlı','Gür','Neşeli'),
  m('Müzik','z','Mozart’ın ünlü “Alla Turca” eseri hangi sonatın bölümüdür?','Piyano Sonatı No. 11','Piyano Sonatı No. 5','Keman Sonatı No. 2','Ay Işığı Sonatı'),
  m('Müzik','z','Bach hangi ülkede yaşamış bir bestecidir?','Almanya','İtalya','Fransa','Avusturya'),
  m('Müzik','z','Vivaldi hangi ülkede doğmuştur?','İtalya','Fransa','Almanya','İspanya'),

  /* ================= Edebiyat ================= */
  m('Edebiyat','k','“Hamlet” kimin eseridir?','William Shakespeare','Victor Hugo','Goethe','Cervantes'),
  m('Edebiyat','k','Nasreddin Hoca’nın mezarı hangi ilimizde bulunur?','Konya','Akşehir','Ankara','Bursa'),
  m('Edebiyat','o','“Don Kişot”un yazarı kimdir?','Cervantes','Dante','Goethe','Shakespeare'),
  m('Edebiyat','o','“Oliver Twist” romanının yazarı kimdir?','Charles Dickens','Mark Twain','Jane Austen','Thomas Hardy'),
  m('Edebiyat','o','“Notre Dame’ın Kamburu” romanının yazarı kimdir?','Victor Hugo','Balzac','Flaubert','Zola'),
  m('Edebiyat','o','“Seksen Günde Devri Âlem” romanının yazarı kimdir?','Jules Verne','H. G. Wells','Mark Twain','Daniel Defoe'),
  m('Edebiyat','o','“Gurur ve Önyargı” romanının yazarı kimdir?','Jane Austen','Charlotte Brontë','Mary Shelley','Virginia Woolf'),
  m('Edebiyat','o','“Hayvan Çiftliği” romanının yazarı kimdir?','George Orwell','Aldous Huxley','Ray Bradbury','Franz Kafka'),
  m('Edebiyat','o','“Yaşlı Adam ve Deniz” romanının yazarı kimdir?','Ernest Hemingway','John Steinbeck','F. Scott Fitzgerald','William Faulkner'),
  m('Edebiyat','o','“Yabancı” romanının yazarı kimdir?','Albert Camus','Jean-Paul Sartre','Victor Hugo','Marcel Proust'),
  m('Edebiyat','o','“İlyada” destanının yazarı olarak kabul edilen şair kimdir?','Homeros','Vergilius','Sofokles','Aristo'),
  m('Edebiyat','o','“Aşk-ı Memnu” romanının yazarı kimdir?','Halit Ziya Uşaklıgil','Reşat Nuri Güntekin','Peyami Safa','Yakup Kadri Karaosmanoğlu'),
  m('Edebiyat','o','“Fatih-Harbiye” romanının yazarı kimdir?','Peyami Safa','Reşat Nuri Güntekin','Halide Edib Adıvar','Ahmet Hamdi Tanpınar'),
  m('Edebiyat','o','“Yaprak Dökümü” romanının yazarı kimdir?','Reşat Nuri Güntekin','Halit Ziya Uşaklıgil','Peyami Safa','Refik Halit Karay'),
  m('Edebiyat','o','“Hababam Sınıfı”nın yazarı kimdir?','Rıfat Ilgaz','Aziz Nesin','Sait Faik Abasıyanık','Orhan Kemal'),
  m('Edebiyat','o','“Zübük” romanının yazarı kimdir?','Aziz Nesin','Rıfat Ilgaz','Sabahattin Ali','Yaşar Kemal'),
  m('Edebiyat','o','“Safahat” adlı şiir kitabı kimin eseridir?','Mehmet Âkif Ersoy','Yahya Kemal Beyatlı','Tevfik Fikret','Ziya Gökalp'),
  m('Edebiyat','o','“İstanbul’u Dinliyorum” şiirinin şairi kimdir?','Orhan Veli Kanık','Nazım Hikmet','Cahit Sıtkı Tarancı','Can Yücel'),
  m('Edebiyat','o','“Seyahatname” adlı eserin yazarı kimdir?','Evliya Çelebi','Katip Çelebi','Piri Reis','Ahmed Cevdet Paşa'),
  m('Edebiyat','o','“Leyla ile Mecnun” mesnevisinin Türk edebiyatındaki en ünlü yazarı kimdir?','Fuzuli','Nedim','Baki','Şeyh Galip'),
  m('Edebiyat','o','Orhan Pamuk’un “Benim Adım Kırmızı” romanı hangi sanat dalını konu alır?','Minyatür','Heykel','Mimari','Hat'),
  m('Edebiyat','z','“Saatleri Ayarlama Enstitüsü” romanının yazarı kimdir?','Ahmet Hamdi Tanpınar','Yusuf Atılgan','Oğuz Atay','Sait Faik Abasıyanık'),
  m('Edebiyat','z','“Aylak Adam” romanının yazarı kimdir?','Yusuf Atılgan','Oğuz Atay','Ahmet Hamdi Tanpınar','Sevgi Soysal'),
  m('Edebiyat','z','“Mai ve Siyah” romanının yazarı kimdir?','Halit Ziya Uşaklıgil','Namık Kemal','Recaizade Mahmud Ekrem','Ahmet Mithat Efendi'),
  m('Edebiyat','z','“Araba Sevdası” romanının yazarı kimdir?','Recaizade Mahmud Ekrem','Namık Kemal','Şemsettin Sami','Ahmet Mithat Efendi'),
  m('Edebiyat','z','“Dokuzuncu Hariciye Koğuşu” romanının yazarı kimdir?','Peyami Safa','Yakup Kadri Karaosmanoğlu','Reşat Nuri Güntekin','Refik Halit Karay'),
  m('Edebiyat','z','“Bereketli Topraklar Üzerinde” romanının yazarı kimdir?','Orhan Kemal','Yaşar Kemal','Kemal Tahir','Fakir Baykurt'),
  m('Edebiyat','z','“Puslu Kıtalar Atlası” romanının yazarı kimdir?','İhsan Oktay Anar','Ahmet Ümit','Orhan Pamuk','Latife Tekin'),
  m('Edebiyat','z','“Vişne Bahçesi” oyununun yazarı kimdir?','Anton Çehov','Gogol','Tolstoy','Gorki'),
  m('Edebiyat','z','“Müfettiş” oyununun yazarı kimdir?','Nikolay Gogol','Anton Çehov','Dostoyevski','Turgenyev'),
  m('Edebiyat','z','“Faust” adlı eserin yazarı kimdir?','Goethe','Schiller','Thomas Mann','Nietzsche'),
  m('Edebiyat','z','“Mavi Yolculuk” kavramıyla anılan yazar kimdir?','Halikarnas Balıkçısı','Sabahattin Ali','Falih Rıfkı Atay','Refik Halit Karay'),
  m('Edebiyat','z','“Han Duvarları” şiirinin şairi kimdir?','Faruk Nafiz Çamlıbel','Ahmet Haşim','Yahya Kemal Beyatlı','Ziya Gökalp')
];
