// Zuqio ek soru havuzu · bölüm 3 (Teknoloji, Yemek, Sanat, Doğa, Dil ve deyimler)
const m = (cat, d, q, ...o) => ({t: 'mc', cat, d, q, o});
const n = (cat, d, q, a, unit, tolAbs) => tolAbs ? {t: 'num', cat, d, q, a, unit, tolAbs} : {t: 'num', cat, d, q, a, unit};

export const MORE3 = [
  /* ================= Teknoloji ================= */
  m('Teknoloji','k','Bilgisayarda yazı yazmak için kullanılan aygıt hangisidir?','Klavye','Fare','Hoparlör','Yazıcı'),
  m('Teknoloji','k','Wi-Fi ne işe yarar?','Kablosuz internet bağlantısı','Şarj etme','Ses kaydı','Görüntü yazdırma'),
  m('Teknoloji','k','Akıllı telefonlarda ekrana dokunarak kullanılan ekran türü nedir?','Dokunmatik ekran','Tüplü ekran','Mekanik ekran','Kabartma ekran'),
  m('Teknoloji','k','E-posta adreslerinde kullanıcı adını alan adından ayıran işaret hangisidir?','@ (et işareti)','# (diyez)','& (ve işareti)','% (yüzde işareti)'),
  m('Teknoloji','k','Videoları izlemek için en çok kullanılan site hangisidir?','YouTube','Wikipedia','Excel','Zoom'),
  m('Teknoloji','k','Bilgisayarı kapatmak için hangi menü kullanılır?','Kapat','Kopyala','Yapıştır','Yazdır'),
  m('Teknoloji','o','USB’nin açılımındaki “S” harfi neyi ifade eder?','Serial','Super','Smart','Safe'),
  m('Teknoloji','o','“PDF” kısaltmasında “P” harfi neyi simgeler?','Portable','Private','Printed','Public'),
  m('Teknoloji','o','Bilgisayarın “beyni” olarak anılan parça hangisidir?','İşlemci','Ekran kartı','Fare','Kasa'),
  m('Teknoloji','o','Aşağıdakilerden hangisi bir işletim sistemidir?','Android','Chrome','Gmail','Skype'),
  m('Teknoloji','o','QR kodu telefonla nasıl okunur?','Kamerayla','Hoparlörle','Mikrofonla','Şarj kablosuyla'),
  m('Teknoloji','o','“Bulut depolama” ne demektir?','Dosyaları internet üzerindeki sunucularda saklamak','Dosyaları havada taşımak','Dosyaları yalnızca flash bellekte tutmak','Dosyaları yazıcıdan çıkarmak'),
  m('Teknoloji','o','Aşağıdakilerden hangisi bir programlama dilidir?','Python','Photoshop','Windows','Instagram'),
  m('Teknoloji','o','Bluetooth teknolojisi neyi sağlar?','Kısa mesafede kablosuz bağlantı','Uydudan yayın izleme','Elektrik üretme','Yazı tasarlama'),
  m('Teknoloji','o','Ekran çözünürlüğünde “Full HD” genellikle hangisidir?','1920 × 1080','640 × 480','800 × 600','320 × 240'),
  m('Teknoloji','z','Bilgisayar biliminde 1 bayt kaç bitten oluşur?','8','4','16','10'),
  m('Teknoloji','z','Dünyanın ilk programcısı olarak anılan kişi kimdir?','Ada Lovelace','Marie Curie','Grace Hopper','Hedy Lamarr'),
  m('Teknoloji','z','World Wide Web’i (WWW) geliştiren kişi kimdir?','Tim Berners-Lee','Bill Gates','Steve Jobs','Linus Torvalds'),
  m('Teknoloji','z','Linux çekirdeğini ilk yazan kişi kimdir?','Linus Torvalds','Dennis Ritchie','Richard Stallman','Alan Turing'),
  m('Teknoloji','z','“Yapay zekâ” alanında makinelerin zekâsını sınamak için önerilen ünlü test hangisidir?','Turing testi','Newton testi','Rorschach testi','Bell testi'),
  m('Teknoloji','z','Bitcoin’in ortaya çıkış yılı hangisidir?','2009','1999','2014','2004'),
  n('Teknoloji','o','Bir kilobayt (KB) yaklaşık kaç bayttır (bilgisayar hesabıyla)?',1024,'bayt'),
  n('Teknoloji','z','Apple şirketi hangi yılda kuruldu?',1976,'',2),
  n('Teknoloji','z','Google hangi yılda kuruldu?',1998,'',2),

  /* ================= Yemek ================= */
  m('Yemek','k','Baklavanın ana malzemelerinden biri hangisidir?','Yufka ve fıstık','Pirinç','Mercimek','Patates'),
  m('Yemek','k','Hangi içecek çaydanlıkta demlenir?','Çay','Ayran','Limonata','Boza'),
  m('Yemek','k','Yoğurdun sulandırılmasıyla yapılan içecek hangisidir?','Ayran','Şalgam','Salep','Boza'),
  m('Yemek','k','Hangisi bir tatlıdır?','Sütlaç','Mantı','Karnıyarık','Tarhana'),
  m('Yemek','k','Pizza hangi ülkenin mutfağıyla özdeşleşmiştir?','İtalya','Japonya','Meksika','Hindistan'),
  m('Yemek','k','Suşi hangi ülkenin yemeğidir?','Japonya','Çin','Tayland','Kore'),
  m('Yemek','k','Hamburger köftesi genellikle hangi etten yapılır?','Dana','Balık','Tavuk','Kuzu'),
  m('Yemek','o','Mantı hangi yemek grubuna girer?','Hamur işi','Tatlı','Çorba','Salata'),
  m('Yemek','o','Zeytinyağlı yemekler genellikle nasıl servis edilir?','Soğuk','Kızgın','Buzlu','Dondurulmuş'),
  m('Yemek','o','Aşağıdakilerden hangisi bir baharattır?','Kimyon','Pirinç','Bulgur','Nohut'),
  m('Yemek','o','Tarhana nasıl bir yiyecektir?','Fermente edilmiş çorba hamuru','Tatlı reçel','Turşu','Peynir çeşidi'),
  m('Yemek','o','İskender kebabı hangi şehirle anılır?','Bursa','Gaziantep','Adana','Urfa'),
  m('Yemek','o','Çiğ köfte geleneksel olarak hangi şehirle anılır?','Şanlıurfa','Edirne','Trabzon','Sinop'),
  m('Yemek','o','Hamsi hangi bölgemizin sembol balıklarındandır?','Karadeniz','Akdeniz','İç Anadolu','Ege'),
  m('Yemek','o','Guacamole hangi meyveden yapılır?','Avokado','Domates','Zeytin','Muz'),
  m('Yemek','z','Türk kahvesi UNESCO listesine hangi kategoride girmiştir?','Somut olmayan kültürel miras','Dünya doğa mirası','Dünya anıtı','Müzik mirası'),
  m('Yemek','z','Baharat olarak kullanılan safran hangi bitkiden elde edilir?','Çiğdem (Crocus)','Biberiye','Kekik','Nane'),
  m('Yemek','z','Wasabi hangi mutfağın sofrasında bulunur?','Japon','Hint','Fransız','İtalyan'),
  m('Yemek','z','Kimchi hangi ülkenin geleneksel fermente yiyeceğidir?','Güney Kore','Japonya','Çin','Vietnam'),
  m('Yemek','z','“Kapuçino” hangi iki bileşenden oluşur?','Espresso ve sütlü köpük','Çay ve süt','Filtre kahve ve su','Çikolata ve krema'),

  /* ================= Sanat ================= */
  m('Sanat','k','Mona Lisa tablosu hangi sanatçıya aittir?','Leonardo da Vinci','Picasso','Van Gogh','Monet'),
  m('Sanat','k','Resim yapmak için kullanılan boya aletine ne denir?','Fırça','Mikroskop','Cetvel','Pergel'),
  m('Sanat','k','Heykeller en çok hangi malzemeden yapılır?','Mermer','Kâğıt','Pamuk','Cam elyaf bulut'),
  m('Sanat','k','Ebru sanatı hangi malzemeyle yapılır?','Su üstünde boya','Ateşte demir','Kumda taş','Kâğıtta tebeşir'),
  m('Sanat','o','Hat sanatında kullanılan yazı aracına ne denir?','Kalem (kamış kalem)','Mühür','Çekiç','Spatula'),
  m('Sanat','o','Minyatür sanatı hangi tür çizimdir?','Küçük boyutlu detaylı resim','Duvar boyama','Dev heykel','Sokak yazısı'),
  m('Sanat','o','Çini sanatı hangi malzemeyle yapılır?','Seramik','Ahşap','Metal tel','Deri'),
  m('Sanat','o','“Düşünen Adam” heykelinin sanatçısı kimdir?','Auguste Rodin','Michelangelo','Donatello','Bernini'),
  m('Sanat','o','Michelangelo’nun Vatikan’daki Sistina Şapeli’nde yaptığı eser nedir?','Tavan freskleri','Duvar halısı','Kubbe mozaiği','Vitray pencereler'),
  m('Sanat','o','Süleymaniye Camii’ni kim yapmıştır?','Mimar Sinan','Mimar Vedat Tek','Sedefkâr Mehmed Ağa','Kemaleddin'),
  m('Sanat','z','Leonardo da Vinci’nin “Son Akşam Yemeği” eseri hangi türdendir?','Duvar resmi (fresk)','Heykel','Mozaik','Kabartma'),
  m('Sanat','z','Salvador Dalí hangi akımla anılır?','Sürrealizm','Kübizm','Fovizm','Dadaizm'),
  m('Sanat','z','Claude Monet’nin “İzlenim, Gün Doğumu” eseri hangi akıma adını vermiştir?','Empresyonizm','Kübizm','Barok','Gotik'),
  m('Sanat','z','Osman Hamdi Bey’in ünlü tablosu hangisidir?','Kaplumbağa Terbiyecisi','Gece Manzarası','Çıplak Kadın','Dört Mevsim'),
  m('Sanat','z','İstanbul Arkeoloji Müzeleri’nin kurucusu kimdir?','Osman Hamdi Bey','Mimar Kemaleddin','Fikret Mualla','Şeker Ahmed Paşa'),
  m('Sanat','z','Rönesans kelimesi ne anlama gelir?','Yeniden doğuş','Karanlık çağ','Büyük savaş','Altın çağ'),
  m('Sanat','z','Eyfel Kulesi hangi ülkededir?','Fransa','İtalya','Belçika','İspanya'),

  /* ================= Doğa ================= */
  m('Doğa','k','Arılar ne üretir?','Bal','Süt','İpek','Yumurta kabuğu'),
  m('Doğa','k','Hangi hayvan memeli değildir?','Kartal','At','Balina','Yarasa'),
  m('Doğa','k','Ağaçlar hangi gazı alıp oksijen verir?','Karbondioksit','Helyum','Metan','Azot'),
  m('Doğa','k','Hangisi bir deniz canlısıdır?','Ahtapot','Tavşan','Karınca','Serçe'),
  m('Doğa','o','Dünyanın en uzun nehri genellikle hangisi kabul edilir?','Nil','Amazon','Tuna','Fırat'),
  m('Doğa','o','Mercanlar hangi tür canlıdır?','Hayvan','Bitki','Mantar','Mineral'),
  m('Doğa','o','Fotosentez bitkinin hangi bölümünde gerçekleşir?','Yaprak','Kök','Çiçek tozu','Gövde kabuğu'),
  m('Doğa','o','Hangi hayvan en hızlı koşan kara hayvanıdır?','Çita','Aslan','At','Tilki'),
  m('Doğa','o','Mavi balina hangi sınıftadır?','Memeli','Balık','Sürüngen','Kabuklu'),
  m('Doğa','o','Aşağıdakilerden hangisi etçil bir bitkidir?','Venüs sinekkapan','Lale','Papatya','Zambak'),
  m('Doğa','z','Okyanuslarda en derin nokta olan çukurun adı nedir?','Mariana Çukuru','Kızıldeniz Çukuru','Hint Çukuru','Atlantik Hendeği'),
  m('Doğa','z','Hangi hayvanın kalbi üç tanedir?','Ahtapot','Köpekbalığı','Yılan','Kurbağa'),
  m('Doğa','z','Dünyanın en büyük çölü (kutuplar hariç) hangisidir?','Sahra','Gobi','Kalahari','Atacama'),
  m('Doğa','z','Hangi ağaç türü “yaşayan fosil” olarak bilinir?','Ginkgo','Meşe','Çam','Kavak'),
  m('Doğa','z','Hangi hayvan uyku sırasında yarım beynini uyutabilir?','Yunus','Köpek','Tavşan','Kedi'),
  m('Doğa','z','Karıncalar hangi böcek grubuna aittir?','Hymenoptera (zarkanatlılar)','Coleoptera','Diptera','Lepidoptera'),
  m('Doğa','z','Dünyanın en yüksek şelalesi hangisidir?','Angel Şelalesi','Niagara','Victoria','İguazu'),

  /* ================= Dil ve deyimler ================= */
  m('Dil ve deyimler','k','“Elini taşın altına koymak” ne demektir?','Sorumluluk almak','Taş atmak','Ceza almak','Yük taşımak'),
  m('Dil ve deyimler','k','“Ağzı kulaklarına varmak” ne anlama gelir?','Çok sevinmek','Çok yemek','Çok konuşmak','Çok susmak'),
  m('Dil ve deyimler','k','“Burun kıvırmak” ne demektir?','Beğenmemek','Koklamak','Hapşırmak','Koşmak'),
  m('Dil ve deyimler','o','“Bin bilsen de bir bilene danış” atasözünün öğüdü nedir?','Uzmana danışmak','Çok bilgi toplamak','Susmak','Kitap okumak'),
  m('Dil ve deyimler','o','“Ayağını yorganına göre uzat” sözü ne öğütler?','Gelire göre harcamak','Erken uyumak','Sıcak tutmak','Yatak almak'),
  m('Dil ve deyimler','o','“Sakla samanı, gelir zamanı” sözü neyi anlatır?','Biriktirilen şeyin bir gün işe yarayacağını','Saman toplamanın zorluğunu','Çiftçilerin işini','Kışın gelişini'),
  m('Dil ve deyimler','o','“Kaş yapayım derken göz çıkarmak” ne demektir?','İyilik yaparken zarar vermek','Göz muayenesi','Makyaj yapmak','Güzelleşmek'),
  m('Dil ve deyimler','o','“Havanda su dövmek” ne anlama gelir?','Boşuna uğraşmak','Su içmek','Baharat ezmek','Temizlik yapmak'),
  m('Dil ve deyimler','o','“Açıkta kalmak” ne demektir?','Güvencesiz kalmak','Hava almak','Yağmurdan korunmak','Işık görmek'),
  m('Dil ve deyimler','o','Zıt anlamlı çifti hangisidir?','Sıcak – soğuk','Kitap – defter','Masa – sandalye','Yol – cadde'),
  m('Dil ve deyimler','o','Eş anlamlı çifti hangisidir?','Güzel – hoş','Siyah – beyaz','Uzun – kısa','Gece – gündüz'),
  m('Dil ve deyimler','z','Aşağıdakilerden hangisi Arapça kökenli bir kelimedir?','Kitap','Göz','Su','Ağaç'),
  m('Dil ve deyimler','z','“Alfabe” sözcüğü hangi dillerin ilk iki harfinden gelir?','Yunanca (alfa, beta)','Latince','Arapça','Sanskritçe'),
  m('Dil ve deyimler','z','Türkçede “ünlü uyumu” neyi düzenler?','Sözcükteki ünlülerin birbirine uymasını','Noktalama işaretlerini','Büyük harf kullanımını','Cümle sırasını'),
  m('Dil ve deyimler','z','“Yazım kılavuzu” hazırlayan kurum hangisidir?','Türk Dil Kurumu','Diyanet İşleri','TRT','Milli Eğitim Bakanlığı'),
  m('Dil ve deyimler','z','Alfabenin Latin harfleriyle yeniden düzenlenmesi hangi yılda yapıldı?','1928','1923','1934','1938'),
  m('Dil ve deyimler','z','“Ağzıyla kuş tutsa” deyimi kimin için kullanılır?','Ne yapsa memnun edemediğimiz kişi için','Avcılar için','Kuşlara bakanlar için','Sessiz biri için'),
];
