// Zuqio İngilizce kategorisi.
//  e(alt başlık, zorluk, soru, doğru, yanlış1, yanlış2, yanlış3, öğrenme notu)
// Seviyeler: k = A1–A2 (Türkçe soru), o = B1–B2, z = C1.
// Öğrenme notu, cevap açıklanırken “Öğren” kartında gösterilir (cevabı önceden sızdırmamak için yalnızca oda sahibinde tutulur).
const e = (sub, d, q, ...rest) => {
  const info = rest.pop();
  return {t: 'mc', cat: 'İngilizce', sub, d, q, o: rest, info};
};

export const EN = [
  /* ============ KOLAY (A1–A2) ============ */
  e('Kelime','k','“Apple” ne demek?','Elma','Armut','Kiraz','Muz','apple = elma · I eat an apple every day. (Her gün bir elma yerim.)'),
  e('Kelime','k','“Dog” ne demek?','Köpek','Kedi','Kuş','Balık','dog = köpek · My dog is very friendly. (Köpeğim çok sevimli.)'),
  e('Kelime','k','“House” ne demek?','Ev','Okul','Araba','Bahçe','house = ev · We live in a big house. (Büyük bir evde yaşıyoruz.)'),
  e('Kelime','k','“Water” ne demek?','Su','Süt','Çay','Ekmek','water = su · Can I have some water, please? (Biraz su alabilir miyim?)'),
  e('Kelime','k','“Red” hangi rengin İngilizcesidir?','Kırmızı','Mavi','Yeşil','Sarı','red = kırmızı · She has a red bag. (Onun kırmızı bir çantası var.)'),
  e('Kelime','k','“Yellow” hangi rengin İngilizcesidir?','Sarı','Mor','Turuncu','Gri','yellow = sarı · The sun is yellow. (Güneş sarıdır.)'),
  e('Kelime','k','“Monday” hangi gündür?','Pazartesi','Salı','Cuma','Pazar','Monday = pazartesi · I have English class on Monday. (Pazartesi günü İngilizce dersim var.)'),
  e('Kelime','k','“Friday” hangi gündür?','Cuma','Cumartesi','Perşembe','Çarşamba','Friday = cuma · We watch a film on Friday. (Cuma günü film izleriz.)'),
  e('Kelime','k','“Tomorrow” ne demek?','Yarın','Dün','Bugün','Şimdi','tomorrow = yarın · See you tomorrow! (Yarın görüşürüz!)'),
  e('Kelime','k','“Yesterday” ne demek?','Dün','Yarın','Bugün','Hafta','yesterday = dün · I was at home yesterday. (Dün evdeydim.)'),
  e('Kelime','k','“Hand” ne demek?','El','Ayak','Kol','Baş','hand = el · Wash your hands. (Ellerini yıka.)'),
  e('Kelime','k','“Eye” ne demek?','Göz','Kulak','Burun','Ağız','eye = göz · She has blue eyes. (Mavi gözleri var.)'),
  e('Kelime','k','“Rain” ne demek?','Yağmur','Kar','Rüzgâr','Güneş','rain = yağmur · I like the rain. (Yağmuru severim.)'),
  e('Kelime','k','“Snow” ne demek?','Kar','Buz','Sis','Bulut','snow = kar · Children play in the snow. (Çocuklar karda oynuyor.)'),
  e('Kelime','k','“Eat” ne demek?','Yemek yemek','İçmek','Uyumak','Koşmak','eat = yemek yemek · We eat dinner at seven. (Akşam yemeğini yedide yeriz.)'),
  e('Kelime','k','“Run” ne demek?','Koşmak','Yürümek','Zıplamak','Yüzmek','run = koşmak · He runs every morning. (Her sabah koşar.)'),
  e('Kelime','k','“Sleep” ne demek?','Uyumak','Uyanmak','Oturmak','Gülmek','sleep = uyumak · The baby is sleeping. (Bebek uyuyor.)'),
  e('Kelime','k','“Mother” ne demek?','Anne','Baba','Kız kardeş','Dede','mother = anne · My mother is a teacher. (Annem öğretmen.)'),
  e('Kelime','k','“Brother” ne demek?','Erkek kardeş','Kız kardeş','Amca','Dede','brother = erkek kardeş · I have one brother. (Bir erkek kardeşim var.)'),
  e('Kelime','k','“Twelve” hangi sayıdır?','12','20','2','21','twelve = 12 · There are twelve months in a year. (Bir yılda on iki ay vardır.)'),
  e('Kelime','k','“Thirty” hangi sayıdır?','30','13','3','33','thirty = 30 · He is thirty years old. (Otuz yaşında.)'),
  e('Kelime','k','“Kitap” İngilizcede nasıl söylenir?','book','box','boat','bike','book = kitap · This book is interesting. (Bu kitap ilginç.)'),
  e('Kelime','k','“Okul” İngilizcede nasıl söylenir?','school','street','store','hospital','school = okul · I go to school by bus. (Okula otobüsle giderim.)'),
  e('Kelime','k','“Arkadaş” İngilizcede nasıl söylenir?','friend','family','father','farmer','friend = arkadaş · She is my best friend. (O benim en iyi arkadaşım.)'),
  e('Kelime','k','“Teşekkür ederim” İngilizcede nasıl söylenir?','Thank you','Please','Sorry','Excuse me','Thank you = teşekkür ederim · Thank you for your help. (Yardımın için teşekkür ederim.)'),
  e('Kelime','k','“Günaydın” İngilizcede nasıl söylenir?','Good morning','Good night','Good evening','Goodbye','Good morning = günaydın · Good morning, teacher! (Günaydın öğretmenim!)'),
  e('Kelime','k','“Mavi” İngilizcede nasıl söylenir?','blue','black','brown','pink','blue = mavi · The sky is blue. (Gökyüzü mavidir.)'),
  e('Kelime','k','“Süt” İngilizcede nasıl söylenir?','milk','meat','mouth','money','milk = süt · I drink milk every morning. (Her sabah süt içerim.)'),
  e('Kelime','k','“Üç” sayısı İngilizcede nasıl yazılır?','three','tree','free','there','three = üç · tree = ağaç. İkisini karıştırma! I have three trees. (Üç ağacım var.)'),
  e('Kelime','k','“Yağmur yağıyor” İngilizcede nasıl söylenir?','It’s raining.','It’s snowing.','It’s sunny.','It’s windy.','It’s raining. = Yağmur yağıyor. Take an umbrella! (Şemsiye al!)'),
  e('Kelime','k','Hangisi bir hayvan adıdır?','cat','cup','chair','coat','cat = kedi · cup = fincan, chair = sandalye, coat = palto.'),
  e('Kelime','k','Hangisi bir meyvedir?','banana','bread','butter','bottle','banana = muz · bread = ekmek, butter = tereyağı, bottle = şişe.'),
  e('Kelime','k','Hangisi bir meslektir?','doctor','dinner','desk','door','doctor = doktor · dinner = akşam yemeği, desk = sıra, door = kapı.'),
  e('Kelime','k','Hangisi bir renk değildir?','table','green','white','purple','table = masa · green = yeşil, white = beyaz, purple = mor.'),
  e('Kelime','k','Hangisi bir yiyecek değildir?','chair','cheese','rice','soup','chair = sandalye · cheese = peynir, rice = pirinç, soup = çorba.'),
  e('Kelime','k','“Big” kelimesinin zıt anlamlısı hangisidir?','small','tall','long','fast','big ↔ small · An elephant is big, a mouse is small. (Fil büyüktür, fare küçüktür.)'),
  e('Kelime','k','“Hot” kelimesinin zıt anlamlısı hangisidir?','cold','warm','dry','hard','hot ↔ cold · The soup is hot, the ice cream is cold. (Çorba sıcak, dondurma soğuk.)'),
  e('Kelime','k','“Happy” kelimesinin zıt anlamlısı hangisidir?','sad','funny','young','tired','happy ↔ sad · I’m happy today, but he is sad. (Bugün mutluyum ama o üzgün.)'),
  e('Kelime','k','“Old” (eski) kelimesinin zıt anlamlısı hangisidir?','new','slow','short','heavy','old ↔ new · I have an old phone and a new laptop. (Eski bir telefonum, yeni bir dizüstü bilgisayarım var.)'),
  e('Kelime','k','“Up” kelimesinin zıt anlamlısı hangisidir?','down','over','out','in','up ↔ down · Please sit down. (Lütfen otur.)'),
  e('Dilbilgisi','k','Boşluğu doldur: I ___ a teacher.','am','is','are','be','I ile “am” kullanılır: I am a teacher. (Ben öğretmenim.)'),
  e('Dilbilgisi','k','Boşluğu doldur: She ___ a student.','is','are','am','be','She / He / It ile “is” kullanılır: She is a student. (O bir öğrenci.)'),
  e('Dilbilgisi','k','Boşluğu doldur: They ___ my friends.','are','is','am','be','They / We / You ile “are” kullanılır: They are my friends. (Onlar arkadaşlarım.)'),
  e('Dilbilgisi','k','Boşluğu doldur: He ___ football every day.','plays','play','playing','played','He / She / It ile fiilin sonuna -s gelir: He plays football every day. (O her gün futbol oynar.)'),
  e('Dilbilgisi','k','Boşluğu doldur: There ___ three books on the table.','are','is','am','be','Çoğul isimlerle “There are” kullanılır: There are three books on the table. (Masada üç kitap var.)'),
  e('Dilbilgisi','k','Boşluğu doldur: She ___ like apples.','doesn’t','don’t','isn’t','aren’t','She / He / It için olumsuz: doesn’t + fiil. She doesn’t like apples. (O elmayı sevmez.)'),
  e('Dilbilgisi','k','Boşluğu doldur: ___ you like pizza?','Do','Does','Are','Is','You ile soru: Do you like pizza? (Pizza sever misin?)'),
  e('Dilbilgisi','k','Boşluğu doldur: He is ___ engineer.','an','a','two','many','Sesli harfle başlayan sözcüklerde “an” kullanılır: an engineer. (O bir mühendis.)'),
  e('Dilbilgisi','k','Boşluğu doldur: My birthday is ___ May.','in','on','at','to','Aylarla “in” kullanılır: in May. (Doğum günüm mayısta.)'),
  e('Dilbilgisi','k','Boşluğu doldur: We have English class ___ Monday.','on','in','at','by','Günlerle “on” kullanılır: on Monday. (Pazartesi günü İngilizce dersimiz var.)'),
  e('Dilbilgisi','k','Boşluğu doldur: I am ___ Turkey.','from','to','at','of','I am from Turkey. = Türkiye’denim. “from” = -den/-dan.'),
  e('Dilbilgisi','k','Boşluğu doldur: How ___ are you?','old','year','age','many','How old are you? = Kaç yaşındasın? Yaş sorarken “old” kullanılır.'),
  e('Dilbilgisi','k','Boşluğu doldur: What ___ your name?','is','are','am','be','What is your name? = Adın ne? İsim tekil olduğu için “is” kullanılır.'),
  e('Dilbilgisi','k','Boşluğu doldur: My mother ___ breakfast at eight every day.','has','have','having','haves','He / She / It ile “have” → “has” olur: My mother has breakfast at eight. (Annem her gün sekizde kahvaltı yapar.)'),
  e('Dilbilgisi','k','Boşluğu doldur: This is my sister. ___ name is Ayşe.','Her','His','Their','Your','Her = onun (kadın için) · His = onun (erkek için). Her name is Ayşe. (Onun adı Ayşe.)'),
  e('Kalıp','k','Hangisi “Nasılsın?” sorusudur?','How are you?','Who are you?','Where are you?','What are you?','How are you? = Nasılsın? · I’m fine, thanks. (İyiyim, teşekkürler.)'),
  e('Kalıp','k','Hangisi “Adın ne?” demektir?','What is your name?','Where is your name?','How is your name?','Who is your name?','What is your name? = Adın ne? · My name is Ali. (Benim adım Ali.)'),
  e('Kalıp','k','Hangisi “Saat kaç?” demektir?','What time is it?','What day is it?','How old is it?','Where is time?','What time is it? = Saat kaç? · It’s half past three. (Saat üç buçuk.)'),
  e('Kalıp','k','“Where are you from?” ne demektir?','Nerelisin?','Nereye gidiyorsun?','Nerede yaşıyorsun?','Kimsin?','Where are you from? = Nerelisin? · I’m from Izmir. (İzmirliyim.)'),
  e('Kalıp','k','“See you later” ne demektir?','Sonra görüşürüz','Hoş geldin','Teşekkürler','Özür dilerim','See you later. = Sonra görüşürüz. Arkadaşlarla vedalaşırken sık kullanılır.'),

  /* ============ ORTA (B1–B2) ============ */
  e('Dilbilgisi','o','I have lived in Ankara ___ 2015.','since','for','from','during','since + başlangıç noktası (since 2015), for + süre (for ten years). Ankara’da 2015’ten beri yaşıyorum.'),
  e('Dilbilgisi','o','She has worked here ___ five years.','for','since','from','during','for + süre: for five years (beş yıldır). since + zaman noktası: since 2019.'),
  e('Dilbilgisi','o','If it rains tomorrow, we ___ at home.','will stay','would stay','stayed','had stayed','Gerçekçi koşul (1. tip): If + şimdiki zaman, will + fiil. Yarın yağmur yağarsa evde kalırız.'),
  e('Dilbilgisi','o','If I ___ you, I would apologize.','were','am','be','will be','Gerçek dışı durumlarda “If I were you” kalıbı kullanılır. Yerinde olsam özür dilerdim.'),
  e('Dilbilgisi','o','I wish I ___ more time.','had','have','has','will have','wish + geçmiş zaman: şu an olmayan bir şeyi dilemek. Keşke daha fazla zamanım olsaydı.'),
  e('Dilbilgisi','o','The book ___ by millions of people.','has been read','has read','have been read','is reading','Edilgen yapı: has been + üçüncü hâl. Kitap milyonlarca kişi tarafından okundu.'),
  e('Dilbilgisi','o','This house ___ in 1990.','was built','built','has built','is building','Geçmişteki edilgen: was/were + üçüncü hâl. Bu ev 1990’da yapıldı.'),
  e('Dilbilgisi','o','You ___ smoke here. It’s forbidden.','mustn’t','don’t have to','needn’t','haven’t to','mustn’t = yasak (yapmamalısın). don’t have to = zorunda değilsin. Burada sigara içmemelisin.'),
  e('Dilbilgisi','o','She is ___ than her sister.','taller','tallest','more tall','the taller','Kısa sıfatlarda karşılaştırma -er ile yapılır: tall → taller. O, kız kardeşinden daha uzun.'),
  e('Dilbilgisi','o','He is the ___ student in the class.','smartest','smarter','most smart','more smarter','en üstünlük: the + sıfat-est → the smartest. O, sınıfın en zeki öğrencisi.'),
  e('Dilbilgisi','o','I’m looking forward ___ you.','to seeing','to see','for see','seeing','look forward to + -ing: I’m looking forward to seeing you. (Seni görmeyi iple çekiyorum.)'),
  e('Dilbilgisi','o','She enjoys ___ novels.','reading','to read','read','reads','enjoy + -ing: She enjoys reading novels. (Roman okumaktan hoşlanır.)'),
  e('Dilbilgisi','o','He suggested ___ to the cinema.','going','to go','go','went','suggest + -ing: He suggested going to the cinema. (Sinemaya gitmeyi önerdi.)'),
  e('Dilbilgisi','o','I’d rather ___ at home tonight.','stay','to stay','staying','stayed','would rather + yalın fiil: I’d rather stay at home. (Bu gece evde kalmayı tercih ederim.)'),
  e('Dilbilgisi','o','By the time we arrived, the film ___.','had started','started','has started','was starting','Geçmişte daha önce olan olay için past perfect: had + üçüncü hâl. Biz varana kadar film başlamıştı.'),
  e('Dilbilgisi','o','I ___ TV when the phone rang.','was watching','watched','am watching','have watched','Geçmişte sürmekte olan eylem: was/were + -ing. Telefon çaldığında TV izliyordum.'),
  e('Dilbilgisi','o','___ I was young, I played the piano.','When','Unless','Since','Until','When = -dığında. When I was young, I played the piano. (Gençken piyano çalardım.)'),
  e('Dilbilgisi','o','She didn’t go out ___ it was raining.','because','so','but','although','because = çünkü. Yağmur yağdığı için dışarı çıkmadı.'),
  e('Dilbilgisi','o','We have ___ milk left.','little','few','many','a few','Sayılamayan isimlerle little / much, sayılabilenlerle few / many kullanılır. Az süt kaldı.'),
  e('Dilbilgisi','o','The more you practise, ___ you become.','the better','better','the best','more better','The more …, the better … = ne kadar çok …, o kadar iyi … Ne kadar çok çalışırsan o kadar iyi olursun.'),
  e('Edat','o','She is afraid ___ spiders.','of','from','with','at','afraid of = -den korkmak. She is afraid of spiders. (Örümceklerden korkar.)'),
  e('Edat','o','He is interested ___ music.','in','on','at','for','interested in = -e ilgi duymak. He is interested in music. (Müziğe ilgi duyuyor.)'),
  e('Edat','o','I’m good ___ maths.','at','in','on','of','good at = -de iyi olmak. I’m good at maths. (Matematikte iyiyim.)'),
  e('Edat','o','We arrived ___ the airport at noon.','at','to','in','on','arrive at (yer/nokta), arrive in (şehir/ülke). Öğlen havalimanına vardık.'),
  e('Edat','o','She depends ___ her parents.','on','of','from','to','depend on = -e bağlı olmak. She depends on her parents. (Ailesine bağımlı.)'),
  e('Edat','o','He is married ___ a doctor.','to','with','by','for','married to = ile evli. He is married to a doctor. (Bir doktorla evli.)'),
  e('Kelime','o','What does “reluctant” mean?','İsteksiz','Cesur','Cömert','Meraklı','reluctant = isteksiz · He was reluctant to leave. (Ayrılmak istemiyordu.)'),
  e('Kelime','o','What does “achieve” mean?','Başarmak','Kaçırmak','Unutmak','Reddetmek','achieve = başarmak · She achieved her goal. (Hedefine ulaştı.)'),
  e('Kelime','o','What does “borrow” mean?','Ödünç almak','Ödünç vermek','Satın almak','Çalmak','borrow = ödünç almak · Can I borrow your pen? (Kalemini ödünç alabilir miyim?) lend = ödünç vermek.'),
  e('Kelime','o','What does “improve” mean?','Geliştirmek','Bozmak','Saklamak','Bitirmek','improve = geliştirmek · I want to improve my English. (İngilizcemi geliştirmek istiyorum.)'),
  e('Kelime','o','What does “ancient” mean?','Çok eski','Yeni','Büyük','Tehlikeli','ancient = çok eski, antik · We visited an ancient city. (Antik bir şehri gezdik.)'),
  e('Kelime','o','What does “fortunately” mean?','Neyse ki','Maalesef','Genellikle','Asla','fortunately = neyse ki · Fortunately, nobody was hurt. (Neyse ki kimse yaralanmadı.)'),
  e('Kelime','o','What does “increase” mean?','Artmak','Azalmak','Durmak','Dönmek','increase = artmak · Prices increased last year. (Fiyatlar geçen yıl arttı.)'),
  e('Kelime','o','What does “enough” mean?','Yeterli','Fazla','Az','Hiç','enough = yeterli · I have enough money. (Yeterli param var.)'),
  e('Kelime','o','What does “suddenly” mean?','Birdenbire','Yavaşça','Her zaman','Sonunda','suddenly = birdenbire · Suddenly, the lights went out. (Birdenbire ışıklar söndü.)'),
  e('Kelime','o','What does “expensive” mean?','Pahalı','Ucuz','Eski','Kalabalık','expensive = pahalı · This watch is too expensive. (Bu saat çok pahalı.)'),
  e('Kelime','o','Which word is the opposite of “increase”?','decrease','improve','enjoy','invite','increase ↔ decrease · Sales increased, but costs decreased. (Satışlar arttı ama maliyetler azaldı.)'),
  e('Kelime','o','Which word means “very big”?','enormous','tiny','narrow','ordinary','enormous = çok büyük, devasa · They live in an enormous house. (Devasa bir evde yaşıyorlar.)'),
  e('Kelime','o','What does “delicious” mean?','Lezzetli','Tehlikeli','Sıcak','Hızlı','delicious = lezzetli · The soup is delicious. (Çorba çok lezzetli.)'),
  e('Kelime','o','What does “forget” mean?','Unutmak','Hatırlamak','Affetmek','Kaybetmek','forget = unutmak · Don’t forget your keys. (Anahtarlarını unutma.)'),
  e('Phrasal verb','o','What does “give up” mean?','Vazgeçmek','Yükseltmek','Bağışlamak','Geri vermek','give up = vazgeçmek · Never give up! (Asla vazgeçme!)'),
  e('Phrasal verb','o','What does “look after” mean?','İlgilenmek, bakmak','Aramak','Dikkat etmek','Hayran olmak','look after = bakmak, ilgilenmek · She looks after her grandmother. (Büyükannesine bakar.) look for = aramak.'),
  e('Phrasal verb','o','What does “turn off” mean?','Kapatmak','Açmak','Çevirmek','Artırmak','turn off = kapatmak · Please turn off the lights. (Lütfen ışıkları kapat.) turn on = açmak.'),
  e('Phrasal verb','o','What does “find out” mean?','Öğrenmek','Aramak','Kaybetmek','Gizlemek','find out = (bilgiyi) öğrenmek · I found out the truth. (Gerçeği öğrendim.)'),
  e('Phrasal verb','o','What does “get up” mean?','Kalkmak','Yatmak','Gelmek','Almak','get up = (yataktan) kalkmak · I get up at seven. (Yedide kalkarım.)'),
  e('Phrasal verb','o','What does “carry on” mean?','Devam etmek','Taşımak','Durmak','Şikâyet etmek','carry on = devam etmek · Carry on with your work. (İşine devam et.)'),
  e('Phrasal verb','o','What does “run out of” mean?','Bir şeyin kalmaması','Dışarı koşmak','Yarışmak','Kaçmak','run out of = bitmek, tükenmek · We ran out of milk. (Sütümüz bitti.)'),
  e('Phrasal verb','o','What does “take off” mean for a plane?','Havalanmak','İnmek','Gecikmek','Yakıt almak','take off = havalanmak · The plane takes off at ten. (Uçak onda havalanır.)'),
  e('Phrasal verb','o','What does “put on” mean for clothes?','Giymek','Çıkarmak','Yıkamak','Asmak','put on = giymek · Put on your coat, it’s cold. (Montunu giy, hava soğuk.)'),
  e('Phrasal verb','o','What does “wake up” mean?','Uyanmak','Uyumak','Dinlenmek','Düşünmek','wake up = uyanmak · I wake up at six. (Altıda uyanırım.)'),
  e('Dikkat','o','Which word means “aslında”?','actually','currently','recently','exactly','actually = aslında · currently = şu anda, recently = yakın zamanda. Actually, I don’t agree. (Aslında katılmıyorum.)'),
  e('Dikkat','o','Which word means “şu anda”?','currently','actually','eventually','especially','currently = şu anda · eventually = sonunda. I’m currently studying. (Şu anda ders çalışıyorum.)'),
  e('Dikkat','o','Which word means “sonunda”?','eventually','possibly','probably','accurately','eventually = sonunda (nihayetinde). “Muhtemelen” anlamına gelmez! Eventually, he agreed. (Sonunda kabul etti.)'),
  e('Dikkat','o','What does “sensible” mean?','Mantıklı, akıllıca davranan','Çok duygusal','Alıngan','Sinirli','sensible = makul, mantıklı · sensitive = duyarlı, alıngan. It’s a sensible idea. (Mantıklı bir fikir.)'),
  e('Dikkat','o','What does “sympathetic” mean?','Anlayışlı, empati kuran','Sempatik, hoş','Kibar','Neşeli','sympathetic = anlayışlı. “Sempatik” için nice veya likeable kullanılır. She was sympathetic. (Anlayış gösterdi.)'),
  e('Dikkat','o','Which sentence uses the right adjective?','I’m interested in science.','I’m interesting in science.','I’m interested on science.','I’m interest in science.','interested = ilgilenen (kişi), interesting = ilginç (şey). I’m interested in science. (Bilimle ilgileniyorum.)'),
  e('Dikkat','o','Which negative sentence is correct?','He doesn’t have any money.','He don’t have any money.','He doesn’t has any money.','He not have any money.','doesn’t + yalın fiil: He doesn’t have any money. (Hiç parası yok.)'),
  e('Dikkat','o','What is the past tense of “go”?','went','goed','gone','going','go – went – gone. Düzensiz fiil: I went to school yesterday. (Dün okula gittim.)'),
  e('Dikkat','o','What is the plural of “child”?','children','childs','childrens','childes','child → children (düzensiz çoğul). The children are playing. (Çocuklar oynuyor.)'),
  e('Dikkat','o','Which spelling is correct for “gerekli”?','necessary','neccessary','necesary','neccesary','necessary = gerekli. Bir c, iki s: necessary. Water is necessary for life. (Su yaşam için gereklidir.)'),

  /* ============ ZOR (C1) ============ */
  e('Kelime','z','What does “ubiquitous” mean?','Her yerde bulunan','Çok nadir','Gizli','Eski moda','ubiquitous = her yerde bulunan · Smartphones are ubiquitous today. (Akıllı telefonlar bugün her yerde.)'),
  e('Kelime','z','What does “ephemeral” mean?','Kısa ömürlü','Sonsuz','Çok parlak','Gizemli','ephemeral = kısa ömürlü, geçici · Fame can be ephemeral. (Şöhret geçici olabilir.)'),
  e('Kelime','z','What does “meticulous” mean?','Titiz','Umursamaz','Acımasız','Sakin','meticulous = titiz, ince eleyip sık dokuyan · She is meticulous about details. (Ayrıntılarda titizdir.)'),
  e('Kelime','z','What does “ambiguous” mean?','Belirsiz, birden fazla anlama gelen','Net','Kızgın','Cömert','ambiguous = belirsiz, muğlak · His answer was ambiguous. (Cevabı muğlaktı.)'),
  e('Kelime','z','What does “inevitable” mean?','Kaçınılmaz','Mümkün','Gereksiz','Şaşırtıcı','inevitable = kaçınılmaz · Change is inevitable. (Değişim kaçınılmazdır.)'),
  e('Kelime','z','What does “scrutinize” mean?','Dikkatle incelemek','Hızla geçmek','Reddetmek','Cezalandırmak','scrutinize = dikkatle incelemek · They scrutinized the contract. (Sözleşmeyi dikkatle incelediler.)'),
  e('Kelime','z','What does “mitigate” mean?','Hafifletmek','Kötüleştirmek','Taşımak','Saklamak','mitigate = (etkisini) hafifletmek · We must mitigate the risks. (Riskleri azaltmalıyız.)'),
  e('Kelime','z','What does “resilient” mean?','Dirençli, çabuk toparlanan','Kırılgan','Tembel','Saygılı','resilient = dirençli · Children can be very resilient. (Çocuklar çok dirençli olabilir.)'),
  e('Kelime','z','What does “conundrum” mean?','Çözülmesi zor ikilem','Kutlama','Dilek','Kural','conundrum = çözülmesi zor bilmece, ikilem · It’s a real conundrum. (Gerçek bir ikilem.)'),
  e('Kelime','z','What does “pragmatic” mean?','Pratik, gerçekçi','Hayalperest','Titiz','Saldırgan','pragmatic = pratik, gerçekçi · She takes a pragmatic approach. (Pratik bir yaklaşım benimser.)'),
  e('Kelime','z','Which word is a synonym of “reluctant”?','unwilling','eager','careless','generous','reluctant ≈ unwilling (isteksiz) · eager = hevesli (zıt anlamlı). He was unwilling to help. (Yardım etmek istemedi.)'),
  e('Kelime','z','Which word is the opposite of “scarce”?','abundant','rare','limited','tiny','scarce = kıt ↔ abundant = bol · Water is scarce here, but food is abundant. (Burada su kıt ama yiyecek bol.)'),
  e('Deyim','z','What does “bite the bullet” mean?','Zor bir durumu cesurca göze almak','Çok yemek','Silahla vurmak','Hızla kaçmak','bite the bullet = dişini sıkmak, zor olanı göze almak · I had to bite the bullet and apologize. (Dişimi sıkıp özür dilemem gerekti.)'),
  e('Deyim','z','What does “break the ice” mean?','Ortamı yumuşatıp sohbeti başlatmak','Buzu kırmak','Soğuk almak','Karı eritmek','break the ice = buzları eritmek, ilk adımı atmak · A joke helped break the ice. (Bir espri ortamı yumuşattı.)'),
  e('Deyim','z','What does “once in a blue moon” mean?','Çok nadiren','Her gece','Gece yarısı','Hava iyiyse','once in a blue moon = çok nadiren · We eat out once in a blue moon. (Çok nadiren dışarıda yeriz.)'),
  e('Deyim','z','What does “a blessing in disguise” mean?','Kötü görünen ama sonradan iyi çıkan şey','Gizli hediye','Sahte dua','Şanssızlık','a blessing in disguise = şer görünen hayır · Losing that job was a blessing in disguise. (O işi kaybetmek şer görünen bir hayırdı.)'),
  e('Deyim','z','What does “the elephant in the room” mean?','Herkesin bildiği ama konuşmadığı büyük sorun','Büyük bir oda','Hayvanat bahçesi','Kalabalık toplantı','the elephant in the room = herkesin görüp konuşmaktan kaçındığı sorun · Let’s talk about the elephant in the room. (Konuşmaktan kaçındığımız meseleyi konuşalım.)'),
  e('Deyim','z','What does “cut corners” mean?','İşi özensiz, kestirmeden yapmak','Mobilya köşelerini kesmek','Para biriktirmek','Yolu kısaltmak','cut corners = işi gelişigüzel / kestirme yapmak · Never cut corners on safety. (Güvenlikte asla kestirmeye gitme.)'),
  e('Deyim','z','What does “hit the nail on the head” mean?','Tam isabet etmek, doğru tespit yapmak','Çivi çakmak','Sinirlenmek','Hata yapmak','hit the nail on the head = tam on ikiden vurmak · You hit the nail on the head! (Tam on ikiden vurdun!)'),
  e('Deyim','z','What does “under the weather” mean?','Hasta, keyifsiz','Dışarıda','Yağmurda','Çok mutlu','under the weather = rahatsız, keyifsiz · I’m feeling under the weather today. (Bugün biraz rahatsızım.)'),
  e('Dilbilgisi','z','If I ___ known, I would have helped.','had','have','would have','did','3. tip koşul: If + had + üçüncü hâl, would have + üçüncü hâl. Bilseydim yardım ederdim.'),
  e('Dilbilgisi','z','___ had she arrived when the phone rang.','Hardly','Almost','Nearly','Mostly','Hardly had … when … = … -er -mez … (devrik yapı). Hardly had she arrived when the phone rang. (O varır varmaz telefon çaldı.)'),
  e('Dilbilgisi','z','The report, ___ was published last week, caused controversy.','which','what','who','whose','which = nesneler için ilgi zamiri. Geçen hafta yayımlanan rapor tartışma yarattı.'),
  e('Dilbilgisi','z','I wish I ___ harder when I was at school.','had studied','studied','have studied','would study','Geçmiş pişmanlık: wish + had + üçüncü hâl. Keşke okulda daha çok çalışsaydım.'),
  e('Dilbilgisi','z','Not only ___ late, but he also forgot the documents.','did he arrive','he arrived','he did arrive','arrived he','Not only ile başlayan cümlelerde devrik yapı: did he arrive. Sadece geç kalmadı, belgeleri de unuttu.'),
  e('Dilbilgisi','z','Which conditional sentence is correct?','Had I known, I would have called you.','If I would have known, I would have called you.','If I knew, I would have called you.','Had I knew, I would call you.','Had I known = If I had known (devrik koşul). Bilseydim seni arardım.'),
  e('Dilbilgisi','z','The weather will ___ our plans.','affect','effect','affection','effected','affect (fiil) = etkilemek · effect (isim) = etki. The weather will affect our plans. (Hava planlarımızı etkileyecek.)'),
  e('Phrasal verb','z','Which phrase means “to postpone”?','put off','put on','put up','put out','put off = ertelemek · We put off the meeting until Friday. (Toplantıyı cumaya erteledik.)'),
  e('Dikkat','z','Which spelling is correct for “utandırmak”?','embarrass','embarass','embaras','embarras','embarrass = utandırmak. İki r, iki s: embarrass. Don’t embarrass me! (Beni utandırma!)')
];
