// Konu paketleri: dar kapsamlı, zorluk seviyesi olmayan soru setleri (ilk şık doğru cevap)
const mk = cat => (q, ...o) => ({t: 'mc', cat, d: 'o', q, o});

const mp = mk('Plakalar'), mb = mk('Başkentler'), me = mk('Elementler'), mr = mk('Bölgeler'), ma = mk('Atasözleri'), mu = mk('Uzay'), mx = mk('Edebiyat');
export const PACKS = [
  {id: 'plaka', name: 'Türkiye plakaları', icon: 'car', desc: 'İl plaka kodlarını ne kadar biliyorsun?', qs: [
    mp("61 hangi ilin plakasıdır?", "Trabzon", "Tunceli", "Tekirdağ", "Tokat"),
    mp("07 hangi ilin plakasıdır?", "Antalya", "Artvin", "Aydın", "Ağrı"),
    mp("Ağrı ilinin plaka kodu kaçtır?", "04", "03", "40", "02"),
    mp("34 hangi ilin plakasıdır?", "İstanbul", "İzmir", "Ağrı", "Hakkâri"),
    mp("Kars ilinin plaka kodu kaçtır?", "36", "46", "34", "37"),
    mp("54 hangi ilin plakasıdır?", "Sakarya", "Siirt", "Sivas", "Samsun"),
    mp("Bartın ilinin plaka kodu kaçtır?", "74", "73", "47", "76"),
    mp("81 hangi ilin plakasıdır?", "Düzce", "Denizli", "Diyarbakır", "Mersin"),
    mp("Mardin ilinin plaka kodu kaçtır?", "47", "57", "48", "46"),
    mp("40 hangi ilin plakasıdır?", "Kırşehir", "Kilis", "Karaman", "Konya"),
    mp("71 hangi ilin plakasıdır?", "Kırıkkale", "Kayseri", "Kütahya", "Kars"),
    mp("Gümüşhane ilinin plaka kodu kaçtır?", "29", "28", "19", "31"),
    mp("Karaman ilinin plaka kodu kaçtır?", "70", "69", "07", "72"),
    mp("Kırklareli ilinin plaka kodu kaçtır?", "39", "38", "29", "41"),
    mp("Rize ilinin plaka kodu kaçtır?", "53", "43", "54", "55"),
    mp("56 hangi ilin plakasıdır?", "Siirt", "Sivas", "Sakarya", "Samsun"),
    mp("Niğde ilinin plaka kodu kaçtır?", "51", "49", "50", "52"),
    mp("51 hangi ilin plakasıdır?", "Niğde", "Nevşehir", "Denizli", "Trabzon"),
    mp("18 hangi ilin plakasıdır?", "Çankırı", "Çorum", "Çanakkale", "Hakkâri"),
    mp("77 hangi ilin plakasıdır?", "Yalova", "Yozgat", "Rize", "Tunceli"),
    mp("01 hangi ilin plakasıdır?", "Adana", "Amasya", "Artvin", "Antalya"),
    mp("62 hangi ilin plakasıdır?", "Tunceli", "Tokat", "Tekirdağ", "Trabzon"),
    mp("Denizli ilinin plaka kodu kaçtır?", "20", "19", "22", "30"),
    mp("38 hangi ilin plakasıdır?", "Kayseri", "Karaman", "Konya", "Kahramanmaraş"),
    mp("11 hangi ilin plakasıdır?", "Bilecik", "Bingöl", "Bursa", "Balıkesir"),
    mp("Adıyaman ilinin plaka kodu kaçtır?", "02", "01", "20", "04"),
    mp("76 hangi ilin plakasıdır?", "Iğdır", "Isparta", "Bingöl", "Uşak"),
    mp("Sinop ilinin plaka kodu kaçtır?", "57", "75", "55", "58"),
    mp("15 hangi ilin plakasıdır?", "Burdur", "Bingöl", "Bartın", "Bolu"),
    mp("Muş ilinin plaka kodu kaçtır?", "49", "48", "39", "59"),
    mp("75 hangi ilin plakasıdır?", "Ardahan", "Ağrı", "Adana", "Amasya"),
    mp("İstanbul ilinin plaka kodu kaçtır?", "34", "44", "24", "33"),
    mp("Kahramanmaraş ilinin plaka kodu kaçtır?", "46", "56", "48", "47"),
    mp("Giresun ilinin plaka kodu kaçtır?", "28", "29", "26", "18"),
    mp("Ardahan ilinin plaka kodu kaçtır?", "75", "73", "76", "74"),
    mp("74 hangi ilin plakasıdır?", "Bartın", "Bolu", "Balıkesir", "Bayburt"),
    mp("39 hangi ilin plakasıdır?", "Kırklareli", "Kocaeli", "Kütahya", "Kahramanmaraş"),
    mp("48 hangi ilin plakasıdır?", "Muğla", "Malatya", "Mersin", "Manisa"),
    mp("Tokat ilinin plaka kodu kaçtır?", "60", "50", "70", "62"),
    mp("Iğdır ilinin plaka kodu kaçtır?", "76", "78", "67", "77"),
    mp("21 hangi ilin plakasıdır?", "Diyarbakır", "Denizli", "Düzce", "Gaziantep"),
    mp("50 hangi ilin plakasıdır?", "Nevşehir", "Niğde", "Sivas", "Tunceli"),
    mp("24 hangi ilin plakasıdır?", "Erzincan", "Edirne", "Elazığ", "Eskişehir"),
    mp("25 hangi ilin plakasıdır?", "Erzurum", "Erzincan", "Edirne", "Eskişehir"),
    mp("Aksaray ilinin plaka kodu kaçtır?", "68", "67", "69", "66"),
    mp("Konya ilinin plaka kodu kaçtır?", "42", "32", "24", "41"),
    mp("Yalova ilinin plaka kodu kaçtır?", "77", "67", "78", "79"),
    mp("46 hangi ilin plakasıdır?", "Kahramanmaraş", "Kocaeli", "Kütahya", "Konya"),
    mp("Bingöl ilinin plaka kodu kaçtır?", "12", "22", "02", "11"),
    mp("09 hangi ilin plakasıdır?", "Aydın", "Adana", "Ağrı", "Afyonkarahisar"),
    mp("Sakarya ilinin plaka kodu kaçtır?", "54", "56", "52", "55"),
    mp("Kayseri ilinin plaka kodu kaçtır?", "38", "28", "37", "48"),
    mp("Kırıkkale ilinin plaka kodu kaçtır?", "71", "73", "72", "81"),
    mp("33 hangi ilin plakasıdır?", "Mersin", "Muğla", "Manisa", "Mardin"),
    mp("08 hangi ilin plakasıdır?", "Artvin", "Adıyaman", "Aydın", "Amasya"),
    mp("Düzce ilinin plaka kodu kaçtır?", "81", "18", "80", "79"),
    mp("60 hangi ilin plakasıdır?", "Tokat", "Tunceli", "Trabzon", "Tekirdağ"),
    mp("59 hangi ilin plakasıdır?", "Tekirdağ", "Tokat", "Trabzon", "Tunceli"),
    mp("Nevşehir ilinin plaka kodu kaçtır?", "50", "51", "05", "40"),
    mp("49 hangi ilin plakasıdır?", "Muş", "Muğla", "Malatya", "Manisa"),
    mp("41 hangi ilin plakasıdır?", "Kocaeli", "Karaman", "Kahramanmaraş", "Kayseri"),
    mp("23 hangi ilin plakasıdır?", "Elazığ", "Eskişehir", "Erzincan", "Edirne"),
    mp("78 hangi ilin plakasıdır?", "Karabük", "Kars", "Kırklareli", "Kilis"),
    mp("03 hangi ilin plakasıdır?", "Afyonkarahisar", "Ardahan", "Ağrı", "Ankara"),
    mp("12 hangi ilin plakasıdır?", "Bingöl", "Bilecik", "Bartın", "Bayburt"),
    mp("02 hangi ilin plakasıdır?", "Adıyaman", "Adana", "Ardahan", "Ankara"),
    mp("36 hangi ilin plakasıdır?", "Kars", "Kütahya", "Karaman", "Konya"),
    mp("Muğla ilinin plaka kodu kaçtır?", "48", "46", "58", "38"),
    mp("31 hangi ilin plakasıdır?", "Hatay", "Hakkâri", "Kastamonu", "Ordu"),
    mp("37 hangi ilin plakasıdır?", "Kastamonu", "Konya", "Kocaeli", "Kırıkkale"),
    mp("79 hangi ilin plakasıdır?", "Kilis", "Karabük", "Konya", "Karaman"),
    mp("Aydın ilinin plaka kodu kaçtır?", "09", "11", "08", "19"),
    mp("Hatay ilinin plaka kodu kaçtır?", "31", "41", "13", "30"),
    mp("47 hangi ilin plakasıdır?", "Mardin", "Muş", "Malatya", "Muğla"),
    mp("19 hangi ilin plakasıdır?", "Çorum", "Çanakkale", "Çankırı", "Denizli"),
    mp("29 hangi ilin plakasıdır?", "Gümüşhane", "Gaziantep", "Giresun", "Zonguldak"),
    mp("70 hangi ilin plakasıdır?", "Karaman", "Konya", "Kilis", "Kayseri"),
    mp("32 hangi ilin plakasıdır?", "Isparta", "Iğdır", "Uşak", "Antalya"),
    mp("Ordu ilinin plaka kodu kaçtır?", "52", "25", "51", "42"),
    mp("80 hangi ilin plakasıdır?", "Osmaniye", "Ordu", "Kırşehir", "İstanbul"),
    mp("Çanakkale ilinin plaka kodu kaçtır?", "17", "07", "18", "15"),
    mp("Karabük ilinin plaka kodu kaçtır?", "78", "76", "80", "79"),
    mp("Mersin ilinin plaka kodu kaçtır?", "33", "32", "34", "43"),
    mp("Zonguldak ilinin plaka kodu kaçtır?", "67", "69", "57", "65"),
    mp("57 hangi ilin plakasıdır?", "Sinop", "Sivas", "Samsun", "Siirt"),
    mp("Kocaeli ilinin plaka kodu kaçtır?", "41", "39", "51", "14"),
    mp("63 hangi ilin plakasıdır?", "Şanlıurfa", "Şırnak", "Isparta", "Bitlis"),
    mp("Bitlis ilinin plaka kodu kaçtır?", "13", "03", "11", "12"),
    mp("35 hangi ilin plakasıdır?", "İzmir", "İstanbul", "Aydın", "Batman"),
    mp("04 hangi ilin plakasıdır?", "Ağrı", "Ardahan", "Amasya", "Antalya"),
    mp("05 hangi ilin plakasıdır?", "Amasya", "Ardahan", "Ağrı", "Antalya"),
    mp("69 hangi ilin plakasıdır?", "Bayburt", "Bitlis", "Burdur", "Bolu"),
    mp("10 hangi ilin plakasıdır?", "Balıkesir", "Burdur", "Bursa", "Bingöl"),
    mp("Amasya ilinin plaka kodu kaçtır?", "05", "50", "15", "03"),
    mp("Uşak ilinin plaka kodu kaçtır?", "64", "74", "54", "46"),
    mp("Manisa ilinin plaka kodu kaçtır?", "45", "54", "43", "55"),
    mp("72 hangi ilin plakasıdır?", "Batman", "Bursa", "Balıkesir", "Bingöl"),
    mp("26 hangi ilin plakasıdır?", "Eskişehir", "Elazığ", "Erzincan", "Erzurum"),
    mp("Afyonkarahisar ilinin plaka kodu kaçtır?", "03", "30", "02", "04"),
    mp("Tekirdağ ilinin plaka kodu kaçtır?", "59", "58", "57", "69"),
    mp("53 hangi ilin plakasıdır?", "Rize", "Çanakkale", "Zonguldak", "Yalova"),
    mp("Bayburt ilinin plaka kodu kaçtır?", "69", "71", "70", "67"),
    mp("Trabzon ilinin plaka kodu kaçtır?", "61", "51", "60", "62"),
    mp("Çankırı ilinin plaka kodu kaçtır?", "18", "28", "81", "20"),
    mp("Batman ilinin plaka kodu kaçtır?", "72", "73", "71", "27"),
    mp("73 hangi ilin plakasıdır?", "Şırnak", "Şanlıurfa", "Bilecik", "Gaziantep"),
    mp("Erzincan ilinin plaka kodu kaçtır?", "24", "23", "42", "26"),
    mp("Çorum ilinin plaka kodu kaçtır?", "19", "21", "29", "09"),
    mp("44 hangi ilin plakasıdır?", "Malatya", "Muş", "Mersin", "Manisa"),
    mp("İzmir ilinin plaka kodu kaçtır?", "35", "37", "33", "25"),
    mp("Tunceli ilinin plaka kodu kaçtır?", "62", "64", "52", "61"),
    mp("Gaziantep ilinin plaka kodu kaçtır?", "27", "29", "25", "37"),
    mp("13 hangi ilin plakasıdır?", "Bitlis", "Bartın", "Bingöl", "Burdur"),
    mp("68 hangi ilin plakasıdır?", "Aksaray", "Adıyaman", "Adana", "Aydın"),
    mp("Eskişehir ilinin plaka kodu kaçtır?", "26", "25", "28", "27"),
    mp("Şanlıurfa ilinin plaka kodu kaçtır?", "63", "61", "65", "36"),
    mp("Burdur ilinin plaka kodu kaçtır?", "15", "16", "05", "17"),
    mp("45 hangi ilin plakasıdır?", "Manisa", "Muğla", "Muş", "Mardin"),
    mp("Adana ilinin plaka kodu kaçtır?", "01", "03", "02", "10"),
    mp("30 hangi ilin plakasıdır?", "Hakkâri", "Hatay", "Sinop", "Siirt"),
    mp("58 hangi ilin plakasıdır?", "Sivas", "Sakarya", "Sinop", "Samsun"),
    mp("Bursa ilinin plaka kodu kaçtır?", "16", "14", "61", "17"),
    mp("Şırnak ilinin plaka kodu kaçtır?", "73", "63", "74", "75"),
    mp("Van ilinin plaka kodu kaçtır?", "65", "75", "63", "55"),
    mp("Kütahya ilinin plaka kodu kaçtır?", "43", "45", "41", "53"),
    mp("17 hangi ilin plakasıdır?", "Çanakkale", "Çankırı", "Çorum", "Bitlis"),
    mp("28 hangi ilin plakasıdır?", "Giresun", "Gaziantep", "Gümüşhane", "Konya"),
    mp("27 hangi ilin plakasıdır?", "Gaziantep", "Gümüşhane", "Giresun", "Bayburt"),
    mp("Hakkâri ilinin plaka kodu kaçtır?", "30", "29", "20", "28"),
    mp("22 hangi ilin plakasıdır?", "Edirne", "Erzurum", "Eskişehir", "Elazığ"),
    mp("52 hangi ilin plakasıdır?", "Ordu", "Osmaniye", "İstanbul", "Kırıkkale"),
    mp("Yozgat ilinin plaka kodu kaçtır?", "66", "65", "76", "67"),
    mp("Erzurum ilinin plaka kodu kaçtır?", "25", "24", "26", "27"),
    mp("67 hangi ilin plakasıdır?", "Zonguldak", "Düzce", "Siirt", "Ağrı"),
    mp("Bolu ilinin plaka kodu kaçtır?", "14", "15", "16", "24"),
    mp("Antalya ilinin plaka kodu kaçtır?", "07", "17", "05", "70"),
    mp("43 hangi ilin plakasıdır?", "Kütahya", "Kırıkkale", "Konya", "Kırklareli"),
    mp("Ankara ilinin plaka kodu kaçtır?", "06", "08", "04", "16"),
    mp("65 hangi ilin plakasıdır?", "Van", "Balıkesir", "Bayburt", "Kocaeli"),
    mp("Kastamonu ilinin plaka kodu kaçtır?", "37", "73", "36", "47"),
    mp("Artvin ilinin plaka kodu kaçtır?", "08", "18", "06", "10"),
    mp("Diyarbakır ilinin plaka kodu kaçtır?", "21", "11", "12", "22"),
    mp("16 hangi ilin plakasıdır?", "Bursa", "Bingöl", "Bolu", "Balıkesir"),
    mp("64 hangi ilin plakasıdır?", "Uşak", "Erzurum", "Ankara", "Kırklareli"),
    mp("06 hangi ilin plakasıdır?", "Ankara", "Aydın", "Aksaray", "Antalya"),
    mp("Edirne ilinin plaka kodu kaçtır?", "22", "23", "20", "32"),
    mp("55 hangi ilin plakasıdır?", "Samsun", "Sinop", "Sakarya", "Siirt"),
    mp("Kilis ilinin plaka kodu kaçtır?", "79", "78", "69", "80"),
    mp("14 hangi ilin plakasıdır?", "Bolu", "Balıkesir", "Burdur", "Bartın"),
    mp("42 hangi ilin plakasıdır?", "Konya", "Kars", "Kahramanmaraş", "Karaman"),
    mp("Siirt ilinin plaka kodu kaçtır?", "56", "46", "65", "54"),
    mp("Osmaniye ilinin plaka kodu kaçtır?", "80", "08", "78", "79"),
    mp("Elazığ ilinin plaka kodu kaçtır?", "23", "24", "25", "22"),
    mp("20 hangi ilin plakasıdır?", "Denizli", "Düzce", "Diyarbakır", "Bingöl"),
    mp("Isparta ilinin plaka kodu kaçtır?", "32", "33", "42", "31"),
    mp("Sivas ilinin plaka kodu kaçtır?", "58", "60", "57", "68"),
    mp("66 hangi ilin plakasıdır?", "Yozgat", "Yalova", "Erzurum", "Batman"),
    mp("Balıkesir ilinin plaka kodu kaçtır?", "10", "08", "09", "11"),
    mp("Kırşehir ilinin plaka kodu kaçtır?", "40", "04", "42", "39"),
    mp("Samsun ilinin plaka kodu kaçtır?", "55", "65", "57", "53"),
    mp("Bilecik ilinin plaka kodu kaçtır?", "11", "21", "13", "01"),
    mp("Malatya ilinin plaka kodu kaçtır?", "44", "45", "43", "46")
  ]},
  {id: 'baskent', name: 'Dünya başkentleri', icon: 'globe', desc: 'Başkentleri ne kadar biliyorsun?', qs: [
    mb("Bosna Hersek ülkesinin başkenti hangisidir?", "Saraybosna", "Kopenhag", "Amsterdam", "Minsk"),
    mb("Sofya hangi ülkenin başkentidir?", "Bulgaristan", "Portekiz", "Bosna Hersek", "İspanya"),
    mb("İsviçre ülkesinin başkenti hangisidir?", "Bern", "Kişinev", "Saraybosna", "Amsterdam"),
    mb("Berlin hangi ülkenin başkentidir?", "Almanya", "Macaristan", "Hollanda", "İzlanda"),
    mb("Brasilia hangi ülkenin başkentidir?", "Brezilya", "Amerika Birleşik Devletleri", "Avustralya", "Küba"),
    mb("Hırvatistan ülkesinin başkenti hangisidir?", "Zagreb", "Kiev", "Madrid", "Bratislava"),
    mb("Podgorica hangi ülkenin başkentidir?", "Karadağ", "Yunanistan", "Malta", "Bulgaristan"),
    mb("Bağdat hangi ülkenin başkentidir?", "Irak", "Pakistan", "Ürdün", "Vietnam"),
    mb("Brezilya ülkesinin başkenti hangisidir?", "Brasilia", "Washington", "Canberra", "Havana"),
    mb("Pakistan ülkesinin başkenti hangisidir?", "İslamabad", "Dakka", "Katmandu", "Astana"),
    mb("Nijerya ülkesinin başkenti hangisidir?", "Abuja", "Kahire", "Addis Ababa", "Rabat"),
    mb("Yeni Zelanda ülkesinin başkenti hangisidir?", "Wellington", "Lima", "Meksiko", "Ottawa"),
    mb("Hanoi hangi ülkenin başkentidir?", "Vietnam", "Pakistan", "Çin", "Nepal"),
    mb("Bern hangi ülkenin başkentidir?", "İsviçre", "Moldova", "Bosna Hersek", "Hollanda"),
    mb("Brüksel hangi ülkenin başkentidir?", "Belçika", "Slovakya", "Bosna Hersek", "Hollanda"),
    mb("Yunanistan ülkesinin başkenti hangisidir?", "Atina", "Paris", "Varşova", "Üsküp"),
    mb("Suudi Arabistan ülkesinin başkenti hangisidir?", "Riyad", "Amman", "İslamabad", "Beyrut"),
    mb("Amman hangi ülkenin başkentidir?", "Ürdün", "Pakistan", "Endonezya", "Ermenistan"),
    mb("Nepal ülkesinin başkenti hangisidir?", "Katmandu", "Astana", "Şam", "Hanoi"),
    mb("Bratislava hangi ülkenin başkentidir?", "Slovakya", "Yunanistan", "Norveç", "Slovenya"),
    mb("Slovenya ülkesinin başkenti hangisidir?", "Ljubljana", "Tallinn", "Dublin", "Roma"),
    mb("Reykjavik hangi ülkenin başkentidir?", "İzlanda", "Hollanda", "Yunanistan", "Ukrayna"),
    mb("Macaristan ülkesinin başkenti hangisidir?", "Budapeşte", "Belgrad", "Riga", "Ljubljana"),
    mb("Cezayir ülkesinin başkenti hangisidir?", "Cezayir", "Kahire", "Abuja", "Nairobi"),
    mb("Stockholm hangi ülkenin başkentidir?", "İsveç", "Hollanda", "Sırbistan", "Arnavutluk"),
    mb("Prag hangi ülkenin başkentidir?", "Çekya", "Yunanistan", "Ukrayna", "Moldova"),
    mb("Moldova ülkesinin başkenti hangisidir?", "Kişinev", "Prag", "Brüksel", "Vilnius"),
    mb("Arnavutluk ülkesinin başkenti hangisidir?", "Tiran", "Bern", "Tallinn", "Atina"),
    mb("Canberra hangi ülkenin başkentidir?", "Avustralya", "Brezilya", "Yeni Zelanda", "Şili"),
    mb("Slovakya ülkesinin başkenti hangisidir?", "Bratislava", "Atina", "Oslo", "Ljubljana"),
    mb("Belçika ülkesinin başkenti hangisidir?", "Brüksel", "Bratislava", "Saraybosna", "Amsterdam"),
    mb("Belarus ülkesinin başkenti hangisidir?", "Minsk", "Kiev", "Londra", "Viyana"),
    mb("Havana hangi ülkenin başkentidir?", "Küba", "Avustralya", "Kanada", "Kolombiya"),
    mb("Romanya ülkesinin başkenti hangisidir?", "Bükreş", "Madrid", "Roma", "Bern"),
    mb("Paris hangi ülkenin başkentidir?", "Fransa", "Rusya", "Ukrayna", "Slovakya"),
    mb("Üsküp hangi ülkenin başkentidir?", "Kuzey Makedonya", "Hırvatistan", "Moldova", "İspanya"),
    mb("Almanya ülkesinin başkenti hangisidir?", "Berlin", "Budapeşte", "Amsterdam", "Reykjavik"),
    mb("Çekya ülkesinin başkenti hangisidir?", "Prag", "Atina", "Kiev", "Kişinev"),
    mb("Gürcistan ülkesinin başkenti hangisidir?", "Tiflis", "Beyrut", "Riyad", "Bakü"),
    mb("Küba ülkesinin başkenti hangisidir?", "Havana", "Canberra", "Ottawa", "Bogota"),
    mb("Japonya ülkesinin başkenti hangisidir?", "Tokyo", "Kabil", "Amman", "Hanoi"),
    mb("Portekiz ülkesinin başkenti hangisidir?", "Lizbon", "Paris", "Helsinki", "Zagreb"),
    mb("Bangkok hangi ülkenin başkentidir?", "Tayland", "Pakistan", "Hindistan", "Afganistan"),
    mb("Taşkent hangi ülkenin başkentidir?", "Özbekistan", "Afganistan", "Ürdün", "Endonezya"),
    mb("İzlanda ülkesinin başkenti hangisidir?", "Reykjavik", "Amsterdam", "Atina", "Kiev"),
    mb("Polonya ülkesinin başkenti hangisidir?", "Varşova", "Podgorica", "Prag", "Üsküp"),
    mb("Kahire hangi ülkenin başkentidir?", "Mısır", "Fas", "Etiyopya", "Libya"),
    mb("Fas ülkesinin başkenti hangisidir?", "Rabat", "Tunus", "Kahire", "Cezayir"),
    mb("Meksika ülkesinin başkenti hangisidir?", "Meksiko", "Havana", "Lima", "Buenos Aires"),
    mb("Çin ülkesinin başkenti hangisidir?", "Pekin", "Yeni Delhi", "Bangkok", "Şam"),
    mb("Seul hangi ülkenin başkentidir?", "Güney Kore", "Afganistan", "Irak", "Vietnam"),
    mb("Karadağ ülkesinin başkenti hangisidir?", "Podgorica", "Atina", "Valletta", "Sofya"),
    mb("Hindistan ülkesinin başkenti hangisidir?", "Yeni Delhi", "Bakü", "Taşkent", "Tokyo"),
    mb("Rabat hangi ülkenin başkentidir?", "Fas", "Tunus", "Mısır", "Cezayir"),
    mb("Şili ülkesinin başkenti hangisidir?", "Santiago", "Bogota", "Lima", "Washington"),
    mb("Şam hangi ülkenin başkentidir?", "Suriye", "Lübnan", "Nepal", "Ürdün"),
    mb("Malta ülkesinin başkenti hangisidir?", "Valletta", "Reykjavik", "Tiran", "Helsinki"),
    mb("Özbekistan ülkesinin başkenti hangisidir?", "Taşkent", "Kabil", "Amman", "Cakarta"),
    mb("Bakü hangi ülkenin başkentidir?", "Azerbaycan", "Hindistan", "Tayland", "Gürcistan"),
    mb("Tayland ülkesinin başkenti hangisidir?", "Bangkok", "İslamabad", "Yeni Delhi", "Kabil"),
    mb("Buenos Aires hangi ülkenin başkentidir?", "Arjantin", "Brezilya", "Kolombiya", "Peru"),
    mb("Ljubljana hangi ülkenin başkentidir?", "Slovenya", "Estonya", "İrlanda", "İtalya"),
    mb("Vilnius hangi ülkenin başkentidir?", "Litvanya", "Hırvatistan", "İzlanda", "Fransa"),
    mb("Lizbon hangi ülkenin başkentidir?", "Portekiz", "Fransa", "Finlandiya", "Hırvatistan"),
    mb("Budapeşte hangi ülkenin başkentidir?", "Macaristan", "Sırbistan", "Letonya", "Slovenya"),
    mb("Tokyo hangi ülkenin başkentidir?", "Japonya", "Afganistan", "Ürdün", "Vietnam"),
    mb("Tiran hangi ülkenin başkentidir?", "Arnavutluk", "İsviçre", "Estonya", "Yunanistan"),
    mb("Etiyopya ülkesinin başkenti hangisidir?", "Addis Ababa", "Tunus", "Kahire", "Rabat"),
    mb("Riga hangi ülkenin başkentidir?", "Letonya", "Arnavutluk", "İtalya", "İsviçre"),
    mb("Zagreb hangi ülkenin başkentidir?", "Hırvatistan", "Ukrayna", "İspanya", "Slovakya"),
    mb("Mısır ülkesinin başkenti hangisidir?", "Kahire", "Rabat", "Addis Ababa", "Trablus"),
    mb("Dublin hangi ülkenin başkentidir?", "İrlanda", "Portekiz", "Çekya", "Slovakya"),
    mb("Pekin hangi ülkenin başkentidir?", "Çin", "Hindistan", "Tayland", "Suriye"),
    mb("Yeni Delhi hangi ülkenin başkentidir?", "Hindistan", "Azerbaycan", "Özbekistan", "Japonya"),
    mb("Afganistan ülkesinin başkenti hangisidir?", "Kabil", "Riyad", "Katmandu", "Manila"),
    mb("Kişinev hangi ülkenin başkentidir?", "Moldova", "Çekya", "Belçika", "Litvanya"),
    mb("Kabil hangi ülkenin başkentidir?", "Afganistan", "Suudi Arabistan", "Nepal", "Filipinler"),
    mb("Norveç ülkesinin başkenti hangisidir?", "Oslo", "Atina", "Podgorica", "Kişinev"),
    mb("Astana hangi ülkenin başkentidir?", "Kazakistan", "Japonya", "Çin", "Suudi Arabistan"),
    mb("Roma hangi ülkenin başkentidir?", "İtalya", "Danimarka", "Rusya", "Macaristan"),
    mb("Washington hangi ülkenin başkentidir?", "Amerika Birleşik Devletleri", "Küba", "Peru", "Kanada"),
    mb("Bangladeş ülkesinin başkenti hangisidir?", "Dakka", "Tokyo", "Seul", "Bağdat"),
    mb("Trablus hangi ülkenin başkentidir?", "Libya", "Etiyopya", "Fas", "Nijerya"),
    mb("Kopenhag hangi ülkenin başkentidir?", "Danimarka", "İsviçre", "Avusturya", "İzlanda"),
    mb("Amerika Birleşik Devletleri ülkesinin başkenti hangisidir?", "Washington", "Havana", "Lima", "Ottawa"),
    mb("Tunus ülkesinin başkenti hangisidir?", "Tunus", "Kahire", "Rabat", "Addis Ababa"),
    mb("Riyad hangi ülkenin başkentidir?", "Suudi Arabistan", "Ürdün", "Pakistan", "Lübnan"),
    mb("Moskova hangi ülkenin başkentidir?", "Rusya", "Belçika", "Ukrayna", "Slovenya"),
    mb("Avusturya ülkesinin başkenti hangisidir?", "Viyana", "Madrid", "Dublin", "Saraybosna"),
    mb("Madrid hangi ülkenin başkentidir?", "İspanya", "Slovakya", "İtalya", "Slovenya"),
    mb("Arjantin ülkesinin başkenti hangisidir?", "Buenos Aires", "Brasilia", "Bogota", "Lima"),
    mb("Kiev hangi ülkenin başkentidir?", "Ukrayna", "Fransa", "Rusya", "Moldova"),
    mb("Belgrad hangi ülkenin başkentidir?", "Sırbistan", "Macaristan", "Fransa", "Karadağ"),
    mb("Güney Kore ülkesinin başkenti hangisidir?", "Seul", "Kabil", "Bağdat", "Hanoi"),
    mb("Amsterdam hangi ülkenin başkentidir?", "Hollanda", "Danimarka", "Norveç", "Litvanya"),
    mb("Cakarta hangi ülkenin başkentidir?", "Endonezya", "Tayland", "Pakistan", "Afganistan"),
    mb("Tunus hangi ülkenin başkentidir?", "Tunus", "Mısır", "Fas", "Etiyopya"),
    mb("Endonezya ülkesinin başkenti hangisidir?", "Cakarta", "Bangkok", "İslamabad", "Kabil"),
    mb("Fransa ülkesinin başkenti hangisidir?", "Paris", "Moskova", "Kiev", "Bratislava"),
    mb("Sırbistan ülkesinin başkenti hangisidir?", "Belgrad", "Budapeşte", "Paris", "Podgorica"),
    mb("Helsinki hangi ülkenin başkentidir?", "Finlandiya", "Belçika", "Çekya", "İzlanda"),
    mb("Katmandu hangi ülkenin başkentidir?", "Nepal", "Kazakistan", "Suriye", "Vietnam"),
    mb("Viyana hangi ülkenin başkentidir?", "Avusturya", "İspanya", "İrlanda", "Bosna Hersek"),
    mb("Manila hangi ülkenin başkentidir?", "Filipinler", "Suudi Arabistan", "Afganistan", "Kazakistan"),
    mb("Azerbaycan ülkesinin başkenti hangisidir?", "Bakü", "Yeni Delhi", "Bangkok", "Tiflis"),
    mb("Nairobi hangi ülkenin başkentidir?", "Kenya", "Mısır", "Fas", "Cezayir"),
    mb("Estonya ülkesinin başkenti hangisidir?", "Tallinn", "Dublin", "Paris", "Berlin"),
    mb("Bogota hangi ülkenin başkentidir?", "Kolombiya", "Amerika Birleşik Devletleri", "Avustralya", "Brezilya"),
    mb("Tallinn hangi ülkenin başkentidir?", "Estonya", "İrlanda", "Fransa", "Almanya"),
    mb("Ermenistan ülkesinin başkenti hangisidir?", "Erivan", "Bakü", "Astana", "Katmandu"),
    mb("Libya ülkesinin başkenti hangisidir?", "Trablus", "Addis Ababa", "Rabat", "Abuja"),
    mb("Letonya ülkesinin başkenti hangisidir?", "Riga", "Tiran", "Roma", "Bern"),
    mb("Litvanya ülkesinin başkenti hangisidir?", "Vilnius", "Zagreb", "Reykjavik", "Paris"),
    mb("İran ülkesinin başkenti hangisidir?", "Tahran", "Şam", "Kabil", "Hanoi"),
    mb("Tahran hangi ülkenin başkentidir?", "İran", "Suriye", "Afganistan", "Vietnam"),
    mb("Bulgaristan ülkesinin başkenti hangisidir?", "Sofya", "Lizbon", "Saraybosna", "Madrid"),
    mb("Wellington hangi ülkenin başkentidir?", "Yeni Zelanda", "Peru", "Meksika", "Kanada"),
    mb("Vietnam ülkesinin başkenti hangisidir?", "Hanoi", "İslamabad", "Pekin", "Katmandu"),
    mb("Kuzey Makedonya ülkesinin başkenti hangisidir?", "Üsküp", "Zagreb", "Kişinev", "Madrid"),
    mb("Dakka hangi ülkenin başkentidir?", "Bangladeş", "Japonya", "Güney Kore", "Irak"),
    mb("Kenya ülkesinin başkenti hangisidir?", "Nairobi", "Kahire", "Rabat", "Cezayir"),
    mb("Abuja hangi ülkenin başkentidir?", "Nijerya", "Mısır", "Etiyopya", "Fas"),
    mb("Minsk hangi ülkenin başkentidir?", "Belarus", "Ukrayna", "Birleşik Krallık", "Avusturya"),
    mb("Atina hangi ülkenin başkentidir?", "Yunanistan", "Fransa", "Polonya", "Kuzey Makedonya"),
    mb("Suriye ülkesinin başkenti hangisidir?", "Şam", "Beyrut", "Katmandu", "Amman"),
    mb("Lübnan ülkesinin başkenti hangisidir?", "Beyrut", "Astana", "Bağdat", "Tahran"),
    mb("Kolombiya ülkesinin başkenti hangisidir?", "Bogota", "Washington", "Canberra", "Brasilia"),
    mb("Addis Ababa hangi ülkenin başkentidir?", "Etiyopya", "Tunus", "Mısır", "Fas"),
    mb("Saraybosna hangi ülkenin başkentidir?", "Bosna Hersek", "Danimarka", "Hollanda", "Belarus"),
    mb("Kazakistan ülkesinin başkenti hangisidir?", "Astana", "Tokyo", "Pekin", "Riyad"),
    mb("Ottawa hangi ülkenin başkentidir?", "Kanada", "Amerika Birleşik Devletleri", "Küba", "Yeni Zelanda"),
    mb("Irak ülkesinin başkenti hangisidir?", "Bağdat", "İslamabad", "Amman", "Hanoi"),
    mb("Peru ülkesinin başkenti hangisidir?", "Lima", "Wellington", "Brasilia", "Havana"),
    mb("Lima hangi ülkenin başkentidir?", "Peru", "Yeni Zelanda", "Brezilya", "Küba"),
    mb("Birleşik Krallık ülkesinin başkenti hangisidir?", "Londra", "Helsinki", "Viyana", "Prag"),
    mb("Beyrut hangi ülkenin başkentidir?", "Lübnan", "Kazakistan", "Irak", "İran"),
    mb("Meksiko hangi ülkenin başkentidir?", "Meksika", "Küba", "Peru", "Arjantin"),
    mb("Danimarka ülkesinin başkenti hangisidir?", "Kopenhag", "Bern", "Viyana", "Reykjavik"),
    mb("Filipinler ülkesinin başkenti hangisidir?", "Manila", "Riyad", "Kabil", "Astana"),
    mb("Rusya ülkesinin başkenti hangisidir?", "Moskova", "Brüksel", "Kiev", "Ljubljana"),
    mb("İrlanda ülkesinin başkenti hangisidir?", "Dublin", "Lizbon", "Prag", "Bratislava"),
    mb("Avustralya ülkesinin başkenti hangisidir?", "Canberra", "Brasilia", "Wellington", "Santiago"),
    mb("Santiago hangi ülkenin başkentidir?", "Şili", "Kolombiya", "Peru", "Amerika Birleşik Devletleri"),
    mb("Kanada ülkesinin başkenti hangisidir?", "Ottawa", "Washington", "Havana", "Wellington"),
    mb("Oslo hangi ülkenin başkentidir?", "Norveç", "Yunanistan", "Karadağ", "Moldova"),
    mb("Ürdün ülkesinin başkenti hangisidir?", "Amman", "İslamabad", "Cakarta", "Erivan"),
    mb("Finlandiya ülkesinin başkenti hangisidir?", "Helsinki", "Brüksel", "Prag", "Reykjavik"),
    mb("Cezayir hangi ülkenin başkentidir?", "Cezayir", "Mısır", "Nijerya", "Kenya"),
    mb("Varşova hangi ülkenin başkentidir?", "Polonya", "Karadağ", "Çekya", "Kuzey Makedonya"),
    mb("Valletta hangi ülkenin başkentidir?", "Malta", "İzlanda", "Arnavutluk", "Finlandiya"),
    mb("Tiflis hangi ülkenin başkentidir?", "Gürcistan", "Lübnan", "Suudi Arabistan", "Azerbaycan"),
    mb("Ukrayna ülkesinin başkenti hangisidir?", "Kiev", "Paris", "Moskova", "Kişinev"),
    mb("Londra hangi ülkenin başkentidir?", "Birleşik Krallık", "Finlandiya", "Avusturya", "Çekya"),
    mb("Bükreş hangi ülkenin başkentidir?", "Romanya", "İspanya", "İtalya", "İsviçre"),
    mb("İspanya ülkesinin başkenti hangisidir?", "Madrid", "Bratislava", "Roma", "Ljubljana"),
    mb("İsveç ülkesinin başkenti hangisidir?", "Stockholm", "Amsterdam", "Belgrad", "Tiran"),
    mb("Erivan hangi ülkenin başkentidir?", "Ermenistan", "Azerbaycan", "Kazakistan", "Nepal"),
    mb("İtalya ülkesinin başkenti hangisidir?", "Roma", "Kopenhag", "Moskova", "Budapeşte"),
    mb("Hollanda ülkesinin başkenti hangisidir?", "Amsterdam", "Kopenhag", "Oslo", "Vilnius"),
    mb("İslamabad hangi ülkenin başkentidir?", "Pakistan", "Bangladeş", "Nepal", "Kazakistan")
  ]},
  {id: 'element', name: 'Elementler', icon: 'flask', desc: 'Sembol ve atom numaraları', qs: [
    me("Bakır elementinin atom numarası kaçtır?", "29", "39", "32", "27"),
    me("Atom numarası 27 olan element hangisidir?", "Kobalt", "Krom", "Bakır", "Brom"),
    me("Berilyum elementinin sembolü hangisidir?", "Be", "Cu", "Br", "B"),
    me("Molibden elementinin sembolü hangisidir?", "Mo", "Mn", "Mg", "Rb"),
    me("Atom numarası 22 olan element hangisidir?", "Titanyum", "Mangan", "Krom", "Oksijen"),
    me("Atom numarası 36 olan element hangisidir?", "Kripton", "İtriyum", "Rubidyum", "Krom"),
    me("Fe sembolü hangi elemente aittir?", "Demir", "Mangan", "Krom", "Volfram"),
    me("Atom numarası 16 olan element hangisidir?", "Kükürt", "Klor", "Potasyum", "Arsenik"),
    me("Antimon elementinin sembolü hangisidir?", "Sb", "N", "Sr", "Sn"),
    me("Vanadyum elementinin atom numarası kaçtır?", "23", "25", "26", "13"),
    me("Kükürt elementinin sembolü hangisidir?", "S", "Sc", "Si", "Pb"),
    me("Cr sembolü hangi elemente aittir?", "Krom", "Vanadyum", "Skandiyum", "Tellür"),
    me("Antimon elementinin atom numarası kaçtır?", "51", "49", "53", "61"),
    me("Lityum elementinin sembolü hangisidir?", "Li", "Pd", "Ca", "P"),
    me("Atom numarası 20 olan element hangisidir?", "Kalsiyum", "Argon", "Potasyum", "Azot"),
    me("Atom numarası 25 olan element hangisidir?", "Mangan", "Demir", "Nikel", "Bor"),
    me("Nikel elementinin sembolü hangisidir?", "Ni", "N", "Na", "Nb"),
    me("Platin elementinin atom numarası kaçtır?", "78", "80", "77", "75"),
    me("Vanadyum elementinin sembolü hangisidir?", "V", "W", "Mo", "Pb"),
    me("Sc sembolü hangi elemente aittir?", "Skandiyum", "Vanadyum", "Krom", "Rutenyum"),
    me("Azot elementinin atom numarası kaçtır?", "7", "6", "8", "5"),
    me("Ca sembolü hangi elemente aittir?", "Kalsiyum", "Argon", "Potasyum", "Azot"),
    me("Magnezyum elementinin sembolü hangisidir?", "Mg", "Mn", "Mo", "In"),
    me("Plütonyum elementinin atom numarası kaçtır?", "94", "97", "96", "91"),
    me("Atom numarası 88 olan element hangisidir?", "Radyum", "Altın", "Cıva", "Alüminyum"),
    me("Sodyum elementinin atom numarası kaçtır?", "11", "14", "9", "10"),
    me("Atom numarası 19 olan element hangisidir?", "Potasyum", "Skandiyum", "Titanyum", "Stronsiyum"),
    me("Atom numarası 48 olan element hangisidir?", "Kadmiyum", "Rodyum", "Kalay", "Karbon"),
    me("Atom numarası 23 olan element hangisidir?", "Vanadyum", "Kalsiyum", "Demir", "Molibden"),
    me("Atom numarası 28 olan element hangisidir?", "Nikel", "Demir", "Kobalt", "İndiyum"),
    me("Krom elementinin atom numarası kaçtır?", "24", "14", "22", "21"),
    me("Kr sembolü hangi elemente aittir?", "Kripton", "İtriyum", "Rubidyum", "Krom"),
    me("Titanyum elementinin sembolü hangisidir?", "Ti", "Te", "Tc", "O"),
    me("K sembolü hangi elemente aittir?", "Potasyum", "Skandiyum", "Titanyum", "Stronsiyum"),
    me("Paladyum elementinin atom numarası kaçtır?", "46", "44", "56", "45"),
    me("Ag sembolü hangi elemente aittir?", "Gümüş", "İndiyum", "Paladyum", "Kobalt"),
    me("Ge sembolü hangi elemente aittir?", "Germanyum", "Bakır", "Galyum", "Stronsiyum"),
    me("Atom numarası 51 olan element hangisidir?", "Antimon", "İndiyum", "Ksenon", "Fosfor"),
    me("Uranyum elementinin sembolü hangisidir?", "U", "Mo", "Sc", "Ra"),
    me("Volfram elementinin sembolü hangisidir?", "W", "V", "Cu", "U"),
    me("Cl sembolü hangi elemente aittir?", "Klor", "Kükürt", "Kalsiyum", "Potasyum"),
    me("Ar sembolü hangi elemente aittir?", "Argon", "Skandiyum", "Potasyum", "Tellür"),
    me("S sembolü hangi elemente aittir?", "Kükürt", "Klor", "Potasyum", "Arsenik"),
    me("Fosfor elementinin sembolü hangisidir?", "P", "Pb", "F", "Pd"),
    me("Kükürt elementinin atom numarası kaçtır?", "16", "14", "18", "6"),
    me("Cıva elementinin atom numarası kaçtır?", "80", "78", "82", "83"),
    me("Au sembolü hangi elemente aittir?", "Altın", "Radon", "Platin", "Sodyum"),
    me("P sembolü hangi elemente aittir?", "Fosfor", "Alüminyum", "Argon", "Rodyum"),
    me("Lityum elementinin atom numarası kaçtır?", "3", "5", "1", "4"),
    me("Baryum elementinin sembolü hangisidir?", "Ba", "Cu", "B", "Be"),
    me("Hidrojen elementinin atom numarası kaçtır?", "1", "3", "4", "2"),
    me("Atom numarası 38 olan element hangisidir?", "Stronsiyum", "Zirkonyum", "Rubidyum", "Teknesyum"),
    me("Neon elementinin atom numarası kaçtır?", "10", "11", "9", "20"),
    me("Molibden elementinin atom numarası kaçtır?", "42", "43", "44", "32"),
    me("Atom numarası 55 olan element hangisidir?", "Sezyum", "Tellür", "Baryum", "Potasyum"),
    me("Atom numarası 50 olan element hangisidir?", "Kalay", "İyot", "Gümüş", "Demir"),
    me("Sr sembolü hangi elemente aittir?", "Stronsiyum", "Zirkonyum", "Rubidyum", "Teknesyum"),
    me("Se sembolü hangi elemente aittir?", "Selenyum", "Kripton", "Brom", "Gümüş"),
    me("Ti sembolü hangi elemente aittir?", "Titanyum", "Mangan", "Krom", "Oksijen"),
    me("Demir elementinin sembolü hangisidir?", "Fe", "F", "W", "Se"),
    me("Rodyum elementinin atom numarası kaçtır?", "45", "46", "44", "35"),
    me("Atom numarası 30 olan element hangisidir?", "Çinko", "Nikel", "Arsenik", "Uranyum"),
    me("Atom numarası 4 olan element hangisidir?", "Berilyum", "Azot", "Lityum", "Potasyum"),
    me("Brom elementinin sembolü hangisidir?", "Br", "Be", "B", "Cu"),
    me("O sembolü hangi elemente aittir?", "Oksijen", "Karbon", "Flor", "Demir"),
    me("Mangan elementinin atom numarası kaçtır?", "25", "35", "15", "24"),
    me("Alüminyum elementinin atom numarası kaçtır?", "13", "12", "14", "23"),
    me("Atom numarası 46 olan element hangisidir?", "Paladyum", "Rutenyum", "İndiyum", "Silisyum"),
    me("Kurşun elementinin sembolü hangisidir?", "Pb", "Pd", "Cd", "Kr"),
    me("Al sembolü hangi elemente aittir?", "Alüminyum", "Neon", "Silisyum", "Berilyum"),
    me("Atom numarası 21 olan element hangisidir?", "Skandiyum", "Vanadyum", "Krom", "Rutenyum"),
    me("Sodyum elementinin sembolü hangisidir?", "Na", "Cs", "N", "Si"),
    me("Oksijen elementinin sembolü hangisidir?", "O", "Fe", "F", "Li"),
    me("Atom numarası 32 olan element hangisidir?", "Germanyum", "Bakır", "Galyum", "Stronsiyum"),
    me("Brom elementinin atom numarası kaçtır?", "35", "36", "25", "37"),
    me("Karbon elementinin atom numarası kaçtır?", "6", "8", "7", "5"),
    me("H sembolü hangi elemente aittir?", "Hidrojen", "Berilyum", "Helyum", "Nikel"),
    me("Magnezyum elementinin atom numarası kaçtır?", "12", "13", "15", "10"),
    me("Rodyum elementinin sembolü hangisidir?", "Rh", "Ra", "Ru", "Rn"),
    me("Rb sembolü hangi elemente aittir?", "Rubidyum", "Zirkonyum", "Brom", "Gümüş"),
    me("Atom numarası 15 olan element hangisidir?", "Fosfor", "Alüminyum", "Argon", "Rodyum"),
    me("Te sembolü hangi elemente aittir?", "Tellür", "İndiyum", "Sezyum", "Skandiyum"),
    me("Altın elementinin sembolü hangisidir?", "Au", "Al", "N", "Ag"),
    me("Stronsiyum elementinin atom numarası kaçtır?", "38", "48", "39", "41"),
    me("Li sembolü hangi elemente aittir?", "Lityum", "Azot", "Helyum", "Paladyum"),
    me("Atom numarası 42 olan element hangisidir?", "Molibden", "Teknesyum", "Rutenyum", "Rubidyum"),
    me("Selenyum elementinin atom numarası kaçtır?", "34", "31", "36", "33"),
    me("Atom numarası 56 olan element hangisidir?", "Baryum", "Tellür", "Kalay", "Altın"),
    me("Pd sembolü hangi elemente aittir?", "Paladyum", "Rutenyum", "İndiyum", "Silisyum"),
    me("İtriyum elementinin sembolü hangisidir?", "Y", "I", "In", "Ba"),
    me("Rh sembolü hangi elemente aittir?", "Rodyum", "Molibden", "Kadmiyum", "Kalay"),
    me("Atom numarası 10 olan element hangisidir?", "Neon", "Alüminyum", "Sodyum", "Niyobyum"),
    me("Kadmiyum elementinin sembolü hangisidir?", "Cd", "S", "Co", "Ca"),
    me("Platin elementinin sembolü hangisidir?", "Pt", "Pu", "K", "P"),
    me("F sembolü hangi elemente aittir?", "Flor", "Magnezyum", "Sodyum", "Nikel"),
    me("Atom numarası 1 olan element hangisidir?", "Hidrojen", "Berilyum", "Helyum", "Nikel"),
    me("Ra sembolü hangi elemente aittir?", "Radyum", "Altın", "Cıva", "Alüminyum"),
    me("Radon elementinin atom numarası kaçtır?", "86", "85", "96", "76"),
    me("Paladyum elementinin sembolü hangisidir?", "Pd", "Pb", "Pu", "P"),
    me("Atom numarası 31 olan element hangisidir?", "Galyum", "Çinko", "Nikel", "Rutenyum"),
    me("İtriyum elementinin atom numarası kaçtır?", "39", "38", "42", "37"),
    me("Hg sembolü hangi elemente aittir?", "Cıva", "Radyum", "Altın", "Kalsiyum"),
    me("Titanyum elementinin atom numarası kaçtır?", "22", "25", "12", "21"),
    me("Atom numarası 26 olan element hangisidir?", "Demir", "Mangan", "Krom", "Volfram"),
    me("Kurşun elementinin atom numarası kaçtır?", "82", "85", "80", "81"),
    me("Radyum elementinin atom numarası kaçtır?", "88", "87", "98", "90"),
    me("Teknesyum elementinin atom numarası kaçtır?", "43", "44", "42", "46"),
    me("Mangan elementinin sembolü hangisidir?", "Mn", "Mo", "Mg", "B"),
    me("Flor elementinin sembolü hangisidir?", "F", "Fe", "P", "Na"),
    me("Atom numarası 43 olan element hangisidir?", "Teknesyum", "Niyobyum", "Zirkonyum", "Flor"),
    me("Atom numarası 18 olan element hangisidir?", "Argon", "Skandiyum", "Potasyum", "Tellür"),
    me("Sb sembolü hangi elemente aittir?", "Antimon", "İndiyum", "Ksenon", "Fosfor"),
    me("Atom numarası 47 olan element hangisidir?", "Gümüş", "İndiyum", "Paladyum", "Kobalt"),
    me("Niyobyum elementinin atom numarası kaçtır?", "41", "44", "51", "39"),
    me("Atom numarası 17 olan element hangisidir?", "Klor", "Kükürt", "Kalsiyum", "Potasyum"),
    me("Atom numarası 24 olan element hangisidir?", "Krom", "Vanadyum", "Skandiyum", "Tellür"),
    me("Zn sembolü hangi elemente aittir?", "Çinko", "Nikel", "Arsenik", "Uranyum"),
    me("Azot elementinin sembolü hangisidir?", "N", "Al", "Sb", "Nb"),
    me("Kalsiyum elementinin atom numarası kaçtır?", "20", "22", "19", "30"),
    me("As sembolü hangi elemente aittir?", "Arsenik", "Galyum", "Brom", "Skandiyum"),
    me("Atom numarası 44 olan element hangisidir?", "Rutenyum", "Rodyum", "Molibden", "Karbon"),
    me("Atom numarası 11 olan element hangisidir?", "Sodyum", "Alüminyum", "Oksijen", "Hidrojen"),
    me("Potasyum elementinin sembolü hangisidir?", "K", "Pt", "Kr", "Pu"),
    me("Mg sembolü hangi elemente aittir?", "Magnezyum", "Alüminyum", "Neon", "İndiyum"),
    me("Hidrojen elementinin sembolü hangisidir?", "H", "He", "Hg", "Ni"),
    me("Skandiyum elementinin atom numarası kaçtır?", "21", "18", "31", "19"),
    me("Nb sembolü hangi elemente aittir?", "Niyobyum", "İtriyum", "Stronsiyum", "Helyum"),
    me("Pb sembolü hangi elemente aittir?", "Kurşun", "Altın", "Radyum", "Bakır"),
    me("Atom numarası 6 olan element hangisidir?", "Karbon", "Azot", "Oksijen", "İndiyum"),
    me("Cıva elementinin sembolü hangisidir?", "Hg", "He", "H", "Ca"),
    me("Kobalt elementinin sembolü hangisidir?", "Co", "Ca", "Cu", "Xe"),
    me("He sembolü hangi elemente aittir?", "Helyum", "Bor", "Berilyum", "Lityum"),
    me("Silisyum elementinin atom numarası kaçtır?", "14", "4", "12", "13"),
    me("Atom numarası 34 olan element hangisidir?", "Selenyum", "Kripton", "Brom", "Gümüş"),
    me("Ga sembolü hangi elemente aittir?", "Galyum", "Çinko", "Nikel", "Rutenyum"),
    me("Si sembolü hangi elemente aittir?", "Silisyum", "Fosfor", "Sodyum", "Alüminyum"),
    me("Atom numarası 33 olan element hangisidir?", "Arsenik", "Galyum", "Brom", "Skandiyum"),
    me("Ru sembolü hangi elemente aittir?", "Rutenyum", "Rodyum", "Molibden", "Karbon"),
    me("Atom numarası 37 olan element hangisidir?", "Rubidyum", "Zirkonyum", "Brom", "Gümüş"),
    me("Ba sembolü hangi elemente aittir?", "Baryum", "Tellür", "Kalay", "Altın"),
    me("Atom numarası 3 olan element hangisidir?", "Lityum", "Azot", "Helyum", "Paladyum"),
    me("Atom numarası 39 olan element hangisidir?", "İtriyum", "Stronsiyum", "Molibden", "Baryum"),
    me("Klor elementinin atom numarası kaçtır?", "17", "14", "19", "7"),
    me("Bor elementinin sembolü hangisidir?", "B", "Br", "Ba", "Be"),
    me("İyot elementinin atom numarası kaçtır?", "53", "52", "56", "43"),
    me("N sembolü hangi elemente aittir?", "Azot", "Neon", "Karbon", "Mangan"),
    me("Atom numarası 52 olan element hangisidir?", "Tellür", "İndiyum", "Sezyum", "Skandiyum"),
    me("Sezyum elementinin atom numarası kaçtır?", "55", "56", "58", "65"),
    me("Sezyum elementinin sembolü hangisidir?", "Cs", "Sr", "Co", "Sc"),
    me("Helyum elementinin sembolü hangisidir?", "He", "Hg", "H", "Li"),
    me("Be sembolü hangi elemente aittir?", "Berilyum", "Azot", "Lityum", "Potasyum"),
    me("Atom numarası 35 olan element hangisidir?", "Brom", "Arsenik", "Rubidyum", "Fosfor"),
    me("Rubidyum elementinin atom numarası kaçtır?", "37", "36", "40", "39"),
    me("Rn sembolü hangi elemente aittir?", "Radon", "Uranyum", "Kurşun", "Oksijen"),
    me("I sembolü hangi elemente aittir?", "İyot", "Kalay", "Tellür", "Demir"),
    me("Altın elementinin atom numarası kaçtır?", "79", "89", "81", "69"),
    me("Kalay elementinin atom numarası kaçtır?", "50", "40", "53", "48"),
    me("Atom numarası 54 olan element hangisidir?", "Ksenon", "Sezyum", "Antimon", "Germanyum"),
    me("Bor elementinin atom numarası kaçtır?", "5", "7", "3", "2"),
    me("Zr sembolü hangi elemente aittir?", "Zirkonyum", "İtriyum", "Stronsiyum", "Silisyum"),
    me("Atom numarası 5 olan element hangisidir?", "Bor", "Azot", "Berilyum", "Zirkonyum"),
    me("Atom numarası 41 olan element hangisidir?", "Niyobyum", "İtriyum", "Stronsiyum", "Helyum"),
    me("Tc sembolü hangi elemente aittir?", "Teknesyum", "Niyobyum", "Zirkonyum", "Flor"),
    me("Atom numarası 7 olan element hangisidir?", "Azot", "Neon", "Karbon", "Mangan"),
    me("Ni sembolü hangi elemente aittir?", "Nikel", "Demir", "Kobalt", "İndiyum"),
    me("Gümüş elementinin sembolü hangisidir?", "Ag", "Ar", "Ge", "Au"),
    me("Arsenik elementinin atom numarası kaçtır?", "33", "30", "23", "43"),
    me("Oksijen elementinin atom numarası kaçtır?", "8", "11", "10", "6"),
    me("Radon elementinin sembolü hangisidir?", "Rn", "Rb", "Ra", "Ru"),
    me("Cd sembolü hangi elemente aittir?", "Kadmiyum", "Rodyum", "Kalay", "Karbon"),
    me("Atom numarası 45 olan element hangisidir?", "Rodyum", "Molibden", "Kadmiyum", "Kalay"),
    me("In sembolü hangi elemente aittir?", "İndiyum", "Kalay", "Antimon", "Nikel"),
    me("Co sembolü hangi elemente aittir?", "Kobalt", "Krom", "Bakır", "Brom"),
    me("Atom numarası 40 olan element hangisidir?", "Zirkonyum", "İtriyum", "Stronsiyum", "Silisyum"),
    me("Kadmiyum elementinin atom numarası kaçtır?", "48", "51", "47", "50"),
    me("Atom numarası 8 olan element hangisidir?", "Oksijen", "Karbon", "Flor", "Demir"),
    me("Cs sembolü hangi elemente aittir?", "Sezyum", "Tellür", "Baryum", "Potasyum"),
    me("Atom numarası 86 olan element hangisidir?", "Radon", "Uranyum", "Kurşun", "Oksijen"),
    me("İndiyum elementinin atom numarası kaçtır?", "49", "52", "46", "39"),
    me("Pt sembolü hangi elemente aittir?", "Platin", "Radon", "Radyum", "Uranyum"),
    me("Mn sembolü hangi elemente aittir?", "Mangan", "Demir", "Nikel", "Bor"),
    me("Karbon elementinin sembolü hangisidir?", "C", "Cu", "Cd", "Cs"),
    me("Silisyum elementinin sembolü hangisidir?", "Si", "Na", "Sn", "Cs"),
    me("Galyum elementinin atom numarası kaçtır?", "31", "33", "34", "21"),
    me("Kobalt elementinin atom numarası kaçtır?", "27", "29", "28", "26"),
    me("C sembolü hangi elemente aittir?", "Karbon", "Azot", "Oksijen", "İndiyum"),
    me("Çinko elementinin atom numarası kaçtır?", "30", "32", "27", "31"),
    me("Krom elementinin sembolü hangisidir?", "Cr", "Cu", "Cs", "Cd"),
    me("Kalay elementinin sembolü hangisidir?", "Sn", "Se", "Cr", "Cl"),
    me("Br sembolü hangi elemente aittir?", "Brom", "Arsenik", "Rubidyum", "Fosfor"),
    me("Ksenon elementinin atom numarası kaçtır?", "54", "53", "52", "55"),
    me("Kripton elementinin atom numarası kaçtır?", "36", "46", "26", "35"),
    me("Neon elementinin sembolü hangisidir?", "Ne", "N", "Na", "Nb"),
    me("Zirkonyum elementinin atom numarası kaçtır?", "40", "37", "50", "42"),
    me("Arsenik elementinin sembolü hangisidir?", "As", "Au", "Al", "Sb"),
    me("Atom numarası 92 olan element hangisidir?", "Uranyum", "Altın", "Plütonyum", "Molibden"),
    me("Rutenyum elementinin sembolü hangisidir?", "Ru", "Rh", "Rb", "Ra"),
    me("B sembolü hangi elemente aittir?", "Bor", "Azot", "Berilyum", "Zirkonyum"),
    me("Kripton elementinin sembolü hangisidir?", "Kr", "S", "Xe", "K"),
    me("Zirkonyum elementinin sembolü hangisidir?", "Zr", "Zn", "Si", "Tc"),
    me("Atom numarası 82 olan element hangisidir?", "Kurşun", "Altın", "Radyum", "Bakır"),
    me("Argon elementinin sembolü hangisidir?", "Ar", "Sb", "Au", "Ag"),
    me("Atom numarası 79 olan element hangisidir?", "Altın", "Radon", "Platin", "Sodyum"),
    me("Alüminyum elementinin sembolü hangisidir?", "Al", "N", "Sb", "As"),
    me("İndiyum elementinin sembolü hangisidir?", "In", "Y", "I", "Ni"),
    me("İyot elementinin sembolü hangisidir?", "I", "Y", "In", "Fe"),
    me("Sn sembolü hangi elemente aittir?", "Kalay", "İyot", "Gümüş", "Demir"),
    me("Nikel elementinin atom numarası kaçtır?", "28", "25", "31", "27"),
    me("Pu sembolü hangi elemente aittir?", "Plütonyum", "Radon", "Altın", "Antimon"),
    me("Potasyum elementinin atom numarası kaçtır?", "19", "9", "20", "18"),
    me("Uranyum elementinin atom numarası kaçtır?", "92", "89", "102", "93"),
    me("Cu sembolü hangi elemente aittir?", "Bakır", "Germanyum", "Çinko", "Krom"),
    me("Galyum elementinin sembolü hangisidir?", "Ga", "Ag", "Ge", "Ru"),
    me("Çinko elementinin sembolü hangisidir?", "Zn", "Zr", "U", "Be"),
    me("Atom numarası 49 olan element hangisidir?", "İndiyum", "Kalay", "Antimon", "Nikel"),
    me("Bakır elementinin sembolü hangisidir?", "Cu", "C", "Co", "Br"),
    me("Berilyum elementinin atom numarası kaçtır?", "4", "6", "14", "3"),
    me("Atom numarası 13 olan element hangisidir?", "Alüminyum", "Neon", "Silisyum", "Berilyum"),
    me("V sembolü hangi elemente aittir?", "Vanadyum", "Kalsiyum", "Demir", "Molibden"),
    me("Skandiyum elementinin sembolü hangisidir?", "Sc", "Si", "Sn", "S"),
    me("Atom numarası 14 olan element hangisidir?", "Silisyum", "Fosfor", "Sodyum", "Alüminyum"),
    me("W sembolü hangi elemente aittir?", "Volfram", "Radon", "Altın", "Bakır"),
    me("Radyum elementinin sembolü hangisidir?", "Ra", "Rb", "Ru", "Rh"),
    me("Gümüş elementinin atom numarası kaçtır?", "47", "37", "57", "50"),
    me("Xe sembolü hangi elemente aittir?", "Ksenon", "Sezyum", "Antimon", "Germanyum"),
    me("Germanyum elementinin atom numarası kaçtır?", "32", "34", "31", "42"),
    me("Atom numarası 94 olan element hangisidir?", "Plütonyum", "Radon", "Altın", "Antimon"),
    me("Atom numarası 12 olan element hangisidir?", "Magnezyum", "Alüminyum", "Neon", "İndiyum"),
    me("Volfram elementinin atom numarası kaçtır?", "74", "73", "64", "77"),
    me("Atom numarası 80 olan element hangisidir?", "Cıva", "Radyum", "Altın", "Kalsiyum"),
    me("Teknesyum elementinin sembolü hangisidir?", "Tc", "Ti", "Te", "F"),
    me("Tellür elementinin atom numarası kaçtır?", "52", "42", "55", "54"),
    me("Atom numarası 74 olan element hangisidir?", "Volfram", "Radon", "Altın", "Bakır"),
    me("Rutenyum elementinin atom numarası kaçtır?", "44", "34", "47", "54"),
    me("Na sembolü hangi elemente aittir?", "Sodyum", "Alüminyum", "Oksijen", "Hidrojen"),
    me("Baryum elementinin atom numarası kaçtır?", "56", "54", "55", "57"),
    me("Niyobyum elementinin sembolü hangisidir?", "Nb", "N", "Ni", "Ne"),
    me("Plütonyum elementinin sembolü hangisidir?", "Pu", "K", "Pb", "Pd"),
    me("Selenyum elementinin sembolü hangisidir?", "Se", "S", "Sn", "Sc"),
    me("Germanyum elementinin sembolü hangisidir?", "Ge", "Ag", "Ga", "Sr"),
    me("Demir elementinin atom numarası kaçtır?", "26", "23", "36", "27"),
    me("Ne sembolü hangi elemente aittir?", "Neon", "Alüminyum", "Sodyum", "Niyobyum"),
    me("Atom numarası 29 olan element hangisidir?", "Bakır", "Germanyum", "Çinko", "Krom"),
    me("Kalsiyum elementinin sembolü hangisidir?", "Ca", "Cl", "C", "Cu"),
    me("Stronsiyum elementinin sembolü hangisidir?", "Sr", "Se", "S", "Na"),
    me("Atom numarası 9 olan element hangisidir?", "Flor", "Magnezyum", "Sodyum", "Nikel"),
    me("U sembolü hangi elemente aittir?", "Uranyum", "Altın", "Plütonyum", "Molibden"),
    me("Atom numarası 53 olan element hangisidir?", "İyot", "Kalay", "Tellür", "Demir"),
    me("Tellür elementinin sembolü hangisidir?", "Te", "Tc", "Ti", "Sc"),
    me("Atom numarası 78 olan element hangisidir?", "Platin", "Radon", "Radyum", "Uranyum"),
    me("Mo sembolü hangi elemente aittir?", "Molibden", "Teknesyum", "Rutenyum", "Rubidyum"),
    me("Klor elementinin sembolü hangisidir?", "Cl", "Cs", "Co", "Kr"),
    me("Y sembolü hangi elemente aittir?", "İtriyum", "Stronsiyum", "Molibden", "Baryum"),
    me("Helyum elementinin atom numarası kaçtır?", "2", "3", "5", "1"),
    me("Flor elementinin atom numarası kaçtır?", "9", "8", "12", "19"),
    me("Rubidyum elementinin sembolü hangisidir?", "Rb", "Rn", "Rh", "Ru"),
    me("Argon elementinin atom numarası kaçtır?", "18", "28", "8", "21"),
    me("Atom numarası 2 olan element hangisidir?", "Helyum", "Bor", "Berilyum", "Lityum"),
    me("Fosfor elementinin atom numarası kaçtır?", "15", "14", "25", "5"),
    me("Ksenon elementinin sembolü hangisidir?", "Xe", "S", "Cr", "Sn")
  ]},
  {id: 'bolge', name: 'Türkiye bölgeleri', icon: 'pin', desc: 'İller hangi bölgede?', qs: [
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Artvin", "Aydın", "Şanlıurfa", "Muğla"),
    mr("Sinop ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Ege", "İç Anadolu", "Marmara"),
    mr("Hangisi Doğu Anadolu Bölgesi’nde yer alan bir ildir?", "Elazığ", "Osmaniye", "Aksaray", "Bursa"),
    mr("Hangisi Ege Bölgesi’nde yer alan bir ildir?", "Manisa", "İstanbul", "Burdur", "Çankırı"),
    mr("Tokat ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Marmara", "İç Anadolu", "Doğu Anadolu"),
    mr("Hangisi Doğu Anadolu Bölgesi’nde yer alan bir ildir?", "Iğdır", "Kocaeli", "Uşak", "Amasya"),
    mr("Manisa ilimiz hangi coğrafi bölgededir?", "Ege", "Doğu Anadolu", "Marmara", "Akdeniz"),
    mr("Hangisi Doğu Anadolu Bölgesi’nde yer alan bir ildir?", "Van", "Tokat", "Kayseri", "Çorum"),
    mr("Hatay ilimiz hangi coğrafi bölgededir?", "Akdeniz", "Doğu Anadolu", "Ege", "Karadeniz"),
    mr("Konya ilimiz hangi coğrafi bölgededir?", "İç Anadolu", "Ege", "Karadeniz", "Marmara"),
    mr("Nevşehir ilimiz hangi coğrafi bölgededir?", "İç Anadolu", "Karadeniz", "Güneydoğu Anadolu", "Akdeniz"),
    mr("Adana ilimiz hangi coğrafi bölgededir?", "Akdeniz", "Karadeniz", "Ege", "Marmara"),
    mr("Hangisi Akdeniz Bölgesi’nde yer alan bir ildir?", "Hatay", "Kırıkkale", "Malatya", "Şırnak"),
    mr("Balıkesir ilimiz hangi coğrafi bölgededir?", "Marmara", "İç Anadolu", "Akdeniz", "Güneydoğu Anadolu"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Samsun", "Balıkesir", "Şırnak", "Siirt"),
    mr("Diyarbakır ilimiz hangi coğrafi bölgededir?", "Güneydoğu Anadolu", "İç Anadolu", "Marmara", "Ege"),
    mr("Hangisi İç Anadolu Bölgesi’nde yer alan bir ildir?", "Karaman", "Şırnak", "Bolu", "Sakarya"),
    mr("Kayseri ilimiz hangi coğrafi bölgededir?", "İç Anadolu", "Güneydoğu Anadolu", "Marmara", "Karadeniz"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Amasya", "Muş", "Kayseri", "Hatay"),
    mr("Hangisi Güneydoğu Anadolu Bölgesi’nde yer alan bir ildir?", "Şanlıurfa", "Isparta", "Edirne", "Iğdır"),
    mr("Niğde ilimiz hangi coğrafi bölgededir?", "İç Anadolu", "Karadeniz", "Akdeniz", "Marmara"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Giresun", "Edirne", "Malatya", "Uşak"),
    mr("Artvin ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Doğu Anadolu", "İç Anadolu", "Güneydoğu Anadolu"),
    mr("Hangisi Doğu Anadolu Bölgesi’nde yer alan bir ildir?", "Bitlis", "Eskişehir", "Adıyaman", "Giresun"),
    mr("Kilis ilimiz hangi coğrafi bölgededir?", "Güneydoğu Anadolu", "İç Anadolu", "Karadeniz", "Doğu Anadolu"),
    mr("Sivas ilimiz hangi coğrafi bölgededir?", "İç Anadolu", "Doğu Anadolu", "Marmara", "Akdeniz"),
    mr("Karaman ilimiz hangi coğrafi bölgededir?", "İç Anadolu", "Ege", "Akdeniz", "Marmara"),
    mr("Hangisi İç Anadolu Bölgesi’nde yer alan bir ildir?", "Çankırı", "Manisa", "Bayburt", "Ardahan"),
    mr("Gaziantep ilimiz hangi coğrafi bölgededir?", "Güneydoğu Anadolu", "Doğu Anadolu", "Karadeniz", "Akdeniz"),
    mr("Adıyaman ilimiz hangi coğrafi bölgededir?", "Güneydoğu Anadolu", "Doğu Anadolu", "Marmara", "Akdeniz"),
    mr("Hangisi Marmara Bölgesi’nde yer alan bir ildir?", "Kocaeli", "Mersin", "Uşak", "İzmir"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Bartın", "Hakkâri", "Sakarya", "Kırklareli"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Bayburt", "Gaziantep", "Kütahya", "Tekirdağ"),
    mr("Hangisi Akdeniz Bölgesi’nde yer alan bir ildir?", "Mersin", "Iğdır", "Afyonkarahisar", "Konya"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Bolu", "Ankara", "Kars", "Hakkâri"),
    mr("Hangisi Marmara Bölgesi’nde yer alan bir ildir?", "Sakarya", "Artvin", "Sivas", "Osmaniye"),
    mr("Hangisi İç Anadolu Bölgesi’nde yer alan bir ildir?", "Ankara", "Mersin", "Adana", "Antalya"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Gümüşhane", "Malatya", "Kayseri", "Şırnak"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Karabük", "Hatay", "Kütahya", "Elazığ"),
    mr("Hangisi Güneydoğu Anadolu Bölgesi’nde yer alan bir ildir?", "Batman", "Muğla", "Denizli", "Bitlis"),
    mr("Çorum ilimiz hangi coğrafi bölgededir?", "Karadeniz", "İç Anadolu", "Akdeniz", "Marmara"),
    mr("Hangisi Marmara Bölgesi’nde yer alan bir ildir?", "İstanbul", "Kars", "Rize", "Isparta"),
    mr("Hangisi İç Anadolu Bölgesi’nde yer alan bir ildir?", "Nevşehir", "Batman", "Erzincan", "Hatay"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Sinop", "Kocaeli", "Osmaniye", "Niğde"),
    mr("Karabük ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Akdeniz", "İç Anadolu", "Ege"),
    mr("Hangisi Güneydoğu Anadolu Bölgesi’nde yer alan bir ildir?", "Kilis", "Bursa", "Kütahya", "Kocaeli"),
    mr("Yalova ilimiz hangi coğrafi bölgededir?", "Marmara", "İç Anadolu", "Karadeniz", "Doğu Anadolu"),
    mr("Hangisi Akdeniz Bölgesi’nde yer alan bir ildir?", "Burdur", "Van", "Amasya", "Karabük"),
    mr("Hangisi Doğu Anadolu Bölgesi’nde yer alan bir ildir?", "Erzurum", "Kütahya", "Bartın", "Kırşehir"),
    mr("Hangisi Marmara Bölgesi’nde yer alan bir ildir?", "Balıkesir", "Batman", "Isparta", "Karaman"),
    mr("Van ilimiz hangi coğrafi bölgededir?", "Doğu Anadolu", "İç Anadolu", "Ege", "Marmara"),
    mr("Eskişehir ilimiz hangi coğrafi bölgededir?", "İç Anadolu", "Marmara", "Akdeniz", "Doğu Anadolu"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Zonguldak", "Afyonkarahisar", "Elazığ", "Gaziantep"),
    mr("Uşak ilimiz hangi coğrafi bölgededir?", "Ege", "Karadeniz", "Doğu Anadolu", "Güneydoğu Anadolu"),
    mr("Çanakkale ilimiz hangi coğrafi bölgededir?", "Marmara", "Karadeniz", "Akdeniz", "Doğu Anadolu"),
    mr("İzmir ilimiz hangi coğrafi bölgededir?", "Ege", "Doğu Anadolu", "Güneydoğu Anadolu", "Marmara"),
    mr("Kars ilimiz hangi coğrafi bölgededir?", "Doğu Anadolu", "Karadeniz", "Marmara", "Akdeniz"),
    mr("Ağrı ilimiz hangi coğrafi bölgededir?", "Doğu Anadolu", "Ege", "İç Anadolu", "Güneydoğu Anadolu"),
    mr("Mardin ilimiz hangi coğrafi bölgededir?", "Güneydoğu Anadolu", "Akdeniz", "Marmara", "İç Anadolu"),
    mr("Tunceli ilimiz hangi coğrafi bölgededir?", "Doğu Anadolu", "Güneydoğu Anadolu", "İç Anadolu", "Marmara"),
    mr("Afyonkarahisar ilimiz hangi coğrafi bölgededir?", "Ege", "Karadeniz", "Güneydoğu Anadolu", "Doğu Anadolu"),
    mr("Düzce ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Güneydoğu Anadolu", "Ege", "Akdeniz"),
    mr("Aksaray ilimiz hangi coğrafi bölgededir?", "İç Anadolu", "Karadeniz", "Doğu Anadolu", "Ege"),
    mr("Hangisi Marmara Bölgesi’nde yer alan bir ildir?", "Kırklareli", "Kastamonu", "Bolu", "Tunceli"),
    mr("Batman ilimiz hangi coğrafi bölgededir?", "Güneydoğu Anadolu", "Ege", "Karadeniz", "Akdeniz"),
    mr("Hangisi Akdeniz Bölgesi’nde yer alan bir ildir?", "Adana", "Trabzon", "Düzce", "Karaman"),
    mr("Hangisi Marmara Bölgesi’nde yer alan bir ildir?", "Edirne", "Bitlis", "Uşak", "Kars"),
    mr("Bolu ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Marmara", "Ege", "İç Anadolu"),
    mr("Osmaniye ilimiz hangi coğrafi bölgededir?", "Akdeniz", "Ege", "Doğu Anadolu", "İç Anadolu"),
    mr("Kırşehir ilimiz hangi coğrafi bölgededir?", "İç Anadolu", "Doğu Anadolu", "Güneydoğu Anadolu", "Karadeniz"),
    mr("Kastamonu ilimiz hangi coğrafi bölgededir?", "Karadeniz", "İç Anadolu", "Akdeniz", "Ege"),
    mr("Rize ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Ege", "Akdeniz", "İç Anadolu"),
    mr("Burdur ilimiz hangi coğrafi bölgededir?", "Akdeniz", "Marmara", "Güneydoğu Anadolu", "İç Anadolu"),
    mr("Hakkâri ilimiz hangi coğrafi bölgededir?", "Doğu Anadolu", "Akdeniz", "Marmara", "Ege"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Çorum", "Erzurum", "Diyarbakır", "Kütahya"),
    mr("Aydın ilimiz hangi coğrafi bölgededir?", "Ege", "Doğu Anadolu", "İç Anadolu", "Karadeniz"),
    mr("Samsun ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Ege", "Doğu Anadolu", "İç Anadolu"),
    mr("İstanbul ilimiz hangi coğrafi bölgededir?", "Marmara", "İç Anadolu", "Karadeniz", "Akdeniz"),
    mr("Kütahya ilimiz hangi coğrafi bölgededir?", "Ege", "İç Anadolu", "Marmara", "Güneydoğu Anadolu"),
    mr("Muş ilimiz hangi coğrafi bölgededir?", "Doğu Anadolu", "Karadeniz", "Ege", "İç Anadolu"),
    mr("Hangisi Güneydoğu Anadolu Bölgesi’nde yer alan bir ildir?", "Adıyaman", "Muş", "Amasya", "Zonguldak"),
    mr("Giresun ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Akdeniz", "İç Anadolu", "Ege"),
    mr("Hangisi Akdeniz Bölgesi’nde yer alan bir ildir?", "Kahramanmaraş", "Manisa", "Sivas", "Aksaray"),
    mr("Hangisi Doğu Anadolu Bölgesi’nde yer alan bir ildir?", "Hakkâri", "Mersin", "Kırşehir", "Kırıkkale"),
    mr("Denizli ilimiz hangi coğrafi bölgededir?", "Ege", "Doğu Anadolu", "Marmara", "Güneydoğu Anadolu"),
    mr("Hangisi Doğu Anadolu Bölgesi’nde yer alan bir ildir?", "Kars", "Düzce", "Bartın", "Trabzon"),
    mr("Hangisi İç Anadolu Bölgesi’nde yer alan bir ildir?", "Sivas", "Kahramanmaraş", "Bilecik", "İstanbul"),
    mr("Hangisi İç Anadolu Bölgesi’nde yer alan bir ildir?", "Kırıkkale", "Ağrı", "Balıkesir", "Amasya"),
    mr("Hangisi İç Anadolu Bölgesi’nde yer alan bir ildir?", "Aksaray", "Balıkesir", "Afyonkarahisar", "Zonguldak"),
    mr("Kahramanmaraş ilimiz hangi coğrafi bölgededir?", "Akdeniz", "Karadeniz", "Güneydoğu Anadolu", "Ege"),
    mr("Hangisi Ege Bölgesi’nde yer alan bir ildir?", "Afyonkarahisar", "Şanlıurfa", "Erzurum", "Kırşehir"),
    mr("Amasya ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Güneydoğu Anadolu", "Ege", "Doğu Anadolu"),
    mr("Hangisi İç Anadolu Bölgesi’nde yer alan bir ildir?", "Eskişehir", "Aydın", "Tunceli", "Kilis"),
    mr("Bitlis ilimiz hangi coğrafi bölgededir?", "Doğu Anadolu", "Marmara", "Güneydoğu Anadolu", "İç Anadolu"),
    mr("Bingöl ilimiz hangi coğrafi bölgededir?", "Doğu Anadolu", "Akdeniz", "Marmara", "Karadeniz"),
    mr("Hangisi Ege Bölgesi’nde yer alan bir ildir?", "Denizli", "Çankırı", "Mardin", "Sinop"),
    mr("Bayburt ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Güneydoğu Anadolu", "Marmara", "İç Anadolu"),
    mr("Ordu ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Güneydoğu Anadolu", "İç Anadolu", "Doğu Anadolu"),
    mr("Hangisi Ege Bölgesi’nde yer alan bir ildir?", "Kütahya", "Batman", "Bayburt", "Kilis"),
    mr("Şanlıurfa ilimiz hangi coğrafi bölgededir?", "Güneydoğu Anadolu", "İç Anadolu", "Ege", "Karadeniz"),
    mr("Hangisi Akdeniz Bölgesi’nde yer alan bir ildir?", "Antalya", "Gaziantep", "Amasya", "Yalova"),
    mr("Hangisi İç Anadolu Bölgesi’nde yer alan bir ildir?", "Kayseri", "Sakarya", "Manisa", "Kütahya"),
    mr("Hangisi Güneydoğu Anadolu Bölgesi’nde yer alan bir ildir?", "Diyarbakır", "Bartın", "Muş", "Isparta"),
    mr("Hangisi İç Anadolu Bölgesi’nde yer alan bir ildir?", "Yozgat", "Düzce", "Yalova", "Burdur"),
    mr("Kocaeli ilimiz hangi coğrafi bölgededir?", "Marmara", "Karadeniz", "Akdeniz", "Doğu Anadolu"),
    mr("Hangisi Akdeniz Bölgesi’nde yer alan bir ildir?", "Isparta", "Bitlis", "Denizli", "Kayseri"),
    mr("Isparta ilimiz hangi coğrafi bölgededir?", "Akdeniz", "İç Anadolu", "Ege", "Doğu Anadolu"),
    mr("Hangisi Ege Bölgesi’nde yer alan bir ildir?", "Uşak", "Erzurum", "Bartın", "Ardahan"),
    mr("Mersin ilimiz hangi coğrafi bölgededir?", "Akdeniz", "İç Anadolu", "Ege", "Güneydoğu Anadolu"),
    mr("Malatya ilimiz hangi coğrafi bölgededir?", "Doğu Anadolu", "Karadeniz", "Akdeniz", "Güneydoğu Anadolu"),
    mr("Muğla ilimiz hangi coğrafi bölgededir?", "Ege", "Marmara", "Akdeniz", "İç Anadolu"),
    mr("Hangisi Doğu Anadolu Bölgesi’nde yer alan bir ildir?", "Ağrı", "Muğla", "Nevşehir", "Çankırı"),
    mr("Hangisi Güneydoğu Anadolu Bölgesi’nde yer alan bir ildir?", "Gaziantep", "Sakarya", "Balıkesir", "İzmir"),
    mr("Kırklareli ilimiz hangi coğrafi bölgededir?", "Marmara", "İç Anadolu", "Karadeniz", "Doğu Anadolu"),
    mr("Hangisi Marmara Bölgesi’nde yer alan bir ildir?", "Yalova", "Kırıkkale", "Elazığ", "Amasya"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Kastamonu", "İstanbul", "Edirne", "Malatya"),
    mr("Hangisi Doğu Anadolu Bölgesi’nde yer alan bir ildir?", "Malatya", "Balıkesir", "Burdur", "İzmir"),
    mr("Hangisi Doğu Anadolu Bölgesi’nde yer alan bir ildir?", "Tunceli", "Hatay", "Konya", "Adıyaman"),
    mr("Hangisi Doğu Anadolu Bölgesi’nde yer alan bir ildir?", "Muş", "Adana", "Batman", "Kilis"),
    mr("Hangisi Marmara Bölgesi’nde yer alan bir ildir?", "Bursa", "Adana", "Kayseri", "Düzce"),
    mr("Trabzon ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Ege", "Marmara", "Güneydoğu Anadolu"),
    mr("Siirt ilimiz hangi coğrafi bölgededir?", "Güneydoğu Anadolu", "Ege", "İç Anadolu", "Akdeniz"),
    mr("Tekirdağ ilimiz hangi coğrafi bölgededir?", "Marmara", "Karadeniz", "İç Anadolu", "Doğu Anadolu"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Tokat", "Adana", "Tunceli", "Hatay"),
    mr("Edirne ilimiz hangi coğrafi bölgededir?", "Marmara", "Ege", "İç Anadolu", "Doğu Anadolu"),
    mr("Hangisi İç Anadolu Bölgesi’nde yer alan bir ildir?", "Kırşehir", "Giresun", "Antalya", "Muş"),
    mr("Çankırı ilimiz hangi coğrafi bölgededir?", "İç Anadolu", "Akdeniz", "Güneydoğu Anadolu", "Doğu Anadolu"),
    mr("Gümüşhane ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Güneydoğu Anadolu", "İç Anadolu", "Marmara"),
    mr("Elazığ ilimiz hangi coğrafi bölgededir?", "Doğu Anadolu", "Marmara", "Güneydoğu Anadolu", "Akdeniz"),
    mr("Iğdır ilimiz hangi coğrafi bölgededir?", "Doğu Anadolu", "Karadeniz", "Akdeniz", "Güneydoğu Anadolu"),
    mr("Sakarya ilimiz hangi coğrafi bölgededir?", "Marmara", "İç Anadolu", "Güneydoğu Anadolu", "Karadeniz"),
    mr("Hangisi Marmara Bölgesi’nde yer alan bir ildir?", "Tekirdağ", "Kırşehir", "Rize", "Adana"),
    mr("Zonguldak ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Marmara", "Akdeniz", "İç Anadolu"),
    mr("Hangisi Ege Bölgesi’nde yer alan bir ildir?", "İzmir", "Mardin", "Erzincan", "Eskişehir"),
    mr("Bartın ilimiz hangi coğrafi bölgededir?", "Karadeniz", "Doğu Anadolu", "Güneydoğu Anadolu", "Ege"),
    mr("Bursa ilimiz hangi coğrafi bölgededir?", "Marmara", "Güneydoğu Anadolu", "İç Anadolu", "Akdeniz"),
    mr("Hangisi İç Anadolu Bölgesi’nde yer alan bir ildir?", "Niğde", "Kastamonu", "İstanbul", "Denizli"),
    mr("Hangisi Güneydoğu Anadolu Bölgesi’nde yer alan bir ildir?", "Şırnak", "Giresun", "Adana", "Tekirdağ"),
    mr("Hangisi Ege Bölgesi’nde yer alan bir ildir?", "Muğla", "Sivas", "Yozgat", "Şanlıurfa"),
    mr("Şırnak ilimiz hangi coğrafi bölgededir?", "Güneydoğu Anadolu", "Marmara", "İç Anadolu", "Akdeniz"),
    mr("Hangisi İç Anadolu Bölgesi’nde yer alan bir ildir?", "Konya", "Rize", "Balıkesir", "Gaziantep"),
    mr("Hangisi Güneydoğu Anadolu Bölgesi’nde yer alan bir ildir?", "Mardin", "Giresun", "Artvin", "Tokat"),
    mr("Bilecik ilimiz hangi coğrafi bölgededir?", "Marmara", "Doğu Anadolu", "İç Anadolu", "Güneydoğu Anadolu"),
    mr("Hangisi Marmara Bölgesi’nde yer alan bir ildir?", "Çanakkale", "Kahramanmaraş", "Muğla", "Eskişehir"),
    mr("Yozgat ilimiz hangi coğrafi bölgededir?", "İç Anadolu", "Karadeniz", "Marmara", "Güneydoğu Anadolu"),
    mr("Kırıkkale ilimiz hangi coğrafi bölgededir?", "İç Anadolu", "Doğu Anadolu", "Karadeniz", "Ege"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Ordu", "Batman", "Gaziantep", "Şırnak"),
    mr("Erzincan ilimiz hangi coğrafi bölgededir?", "Doğu Anadolu", "Akdeniz", "Karadeniz", "Marmara"),
    mr("Hangisi Akdeniz Bölgesi’nde yer alan bir ildir?", "Osmaniye", "Eskişehir", "Zonguldak", "Nevşehir"),
    mr("Hangisi Doğu Anadolu Bölgesi’nde yer alan bir ildir?", "Bingöl", "Nevşehir", "Siirt", "Mersin"),
    mr("Hangisi Güneydoğu Anadolu Bölgesi’nde yer alan bir ildir?", "Siirt", "İzmir", "Gümüşhane", "Denizli"),
    mr("Hangisi Doğu Anadolu Bölgesi’nde yer alan bir ildir?", "Ardahan", "Şanlıurfa", "Kilis", "Gümüşhane"),
    mr("Hangisi Doğu Anadolu Bölgesi’nde yer alan bir ildir?", "Erzincan", "Konya", "İstanbul", "Ordu"),
    mr("Antalya ilimiz hangi coğrafi bölgededir?", "Akdeniz", "Marmara", "Ege", "Güneydoğu Anadolu"),
    mr("Hangisi Marmara Bölgesi’nde yer alan bir ildir?", "Bilecik", "Ordu", "Bayburt", "Karaman"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Düzce", "Yozgat", "Kütahya", "Afyonkarahisar"),
    mr("Erzurum ilimiz hangi coğrafi bölgededir?", "Doğu Anadolu", "Güneydoğu Anadolu", "Akdeniz", "Marmara"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Trabzon", "Iğdır", "Uşak", "Kocaeli"),
    mr("Ardahan ilimiz hangi coğrafi bölgededir?", "Doğu Anadolu", "Güneydoğu Anadolu", "Marmara", "Karadeniz"),
    mr("Hangisi Karadeniz Bölgesi’nde yer alan bir ildir?", "Rize", "Çankırı", "Edirne", "Siirt"),
    mr("Hangisi Ege Bölgesi’nde yer alan bir ildir?", "Aydın", "Kayseri", "Iğdır", "Yalova"),
    mr("Ankara ilimiz hangi coğrafi bölgededir?", "İç Anadolu", "Güneydoğu Anadolu", "Karadeniz", "Ege")
  ]},
  {id: 'atasozu', name: 'Atasözleri', icon: 'quote', desc: 'Atasözünü tamamlayabilir misin?', qs: [
    ma("“Damlaya damlaya ___ olur.” atasözündeki boşluğa ne gelir?", "göl", "nehir", "deniz", "bataklık"),
    ma("“Sakla samanı, ___ zamanı.” atasözündeki boşluğa ne gelir?", "gelir", "geçer", "biter", "kalır"),
    ma("“Ağaç yaşken ___.” atasözündeki boşluğa ne gelir?", "eğilir", "kurur", "büyür", "kırılır"),
    ma("“Bugünün işini yarına ___.” atasözündeki boşluğa ne gelir?", "bırakma", "sakla", "taşıma", "unutma"),
    ma("“Akıllı düşman, ___ dosttan iyidir.” atasözündeki boşluğa ne gelir?", "akılsız", "zengin", "yalancı", "uzak"),
    ma("“Kervan yolda ___.” atasözündeki boşluğa ne gelir?", "düzülür", "yürür", "durur", "bozulur"),
    ma("“Üzüm üzüme baka baka ___.” atasözündeki boşluğa ne gelir?", "kararır", "büyür", "tatlanır", "olgunlaşır"),
    ma("“Komşu komşunun ___ muhtaçtır.” atasözündeki boşluğa ne gelir?", "külüne", "ekmeğine", "suyuna", "tuzuna"),
    ma("“Bir elin nesi var, iki elin ___ var.” atasözündeki boşluğa ne gelir?", "sesi", "gücü", "işi", "adı"),
    ma("“Gülü seven dikenine ___.” atasözündeki boşluğa ne gelir?", "katlanır", "kızar", "bakar", "dokunur"),
    ma("“Ne ekersen onu ___.” atasözündeki boşluğa ne gelir?", "biçersin", "yersin", "görürsün", "bulursun"),
    ma("“Sütten ağzı yanan yoğurdu ___ yer.” atasözündeki boşluğa ne gelir?", "üfleyerek", "soğutarak", "karıştırarak", "bekleyerek"),
    ma("“Havlayan köpek ___.” atasözündeki boşluğa ne gelir?", "ısırmaz", "kaçmaz", "susmaz", "bekler"),
    ma("“Dost acı ___.” atasözündeki boşluğa ne gelir?", "söyler", "verir", "çeker", "gülümser"),
    ma("“Güneş girmeyen eve ___ girer.” atasözündeki boşluğa ne gelir?", "doktor", "hırsız", "soğuk", "rüzgâr"),
    ma("“Bir musibet bin ___ den iyidir.” atasözündeki boşluğa ne gelir?", "nasihatten", "duadan", "ilaçtan", "sözden"),
    ma("“Dereyi görmeden paçaları ___.” atasözündeki boşluğa ne gelir?", "sıvama", "çıkarma", "ıslatma", "bağlama"),
    ma("“Tatlı dil yılanı ___ çıkarır.” atasözündeki boşluğa ne gelir?", "deliğinden", "yuvasından", "kabuğundan", "sepetinden"),
    ma("“Taşıma su ile ___ dönmez.” atasözündeki boşluğa ne gelir?", "değirmen", "araba", "gemi", "çark"),
    ma("“Ayağını yorganına göre ___.” atasözündeki boşluğa ne gelir?", "uzat", "çek", "sar", "koy"),
    ma("“Rüzgâr eken ___ biçer.” atasözündeki boşluğa ne gelir?", "fırtına", "yağmur", "sel", "kar"),
    ma("“Bin bilsen de bir ___ danış.” atasözündeki boşluğa ne gelir?", "bilene", "büyüğe", "dosta", "hocaya"),
    ma("“Sabreden derviş muradına ___.” atasözündeki boşluğa ne gelir?", "ermiş", "varmış", "yetmiş", "gelmiş"),
    ma("“Ak akçe kara gün ___.” atasözündeki boşluğa ne gelir?", "içindir", "kalır", "biter", "gelir"),
    ma("“Terzi kendi ___ dikemez.” atasözündeki boşluğa ne gelir?", "söküğünü", "kumaşını", "iğnesini", "ipini"),
    ma("“Armut dibine ___.” atasözündeki boşluğa ne gelir?", "düşer", "uzanır", "bakar", "yaslanır"),
    ma("“Keskin sirke ___ zarar.” atasözündeki boşluğa ne gelir?", "küpüne", "şişesine", "tenceresine", "kabına"),
    ma("“Bir fincan kahvenin ___ yıl hatırı vardır.” atasözündeki boşluğa ne gelir?", "kırk", "yüz", "yedi", "otuz"),
    ma("“İnsan yedisinde ne ise ___ de odur.” atasözündeki boşluğa ne gelir?", "yetmişinde", "kırkında", "ellisinde", "altmışında"),
    ma("“Ateş olmayan yerden ___ çıkmaz.” atasözündeki boşluğa ne gelir?", "duman", "alev", "koku", "kıvılcım"),
    ma("“Atı alan ___ geçti.” atasözündeki boşluğa ne gelir?", "Üsküdar’ı", "Boğaz’ı", "köprüyü", "İstanbul’u"),
    ma("“Görünen köy ___ ister mi?” atasözündeki boşluğa ne gelir?", "kılavuz", "harita", "yol", "rehber"),
    ma("“Eşek ölür, ___ kalır.” atasözündeki boşluğa ne gelir?", "semeri", "yükü", "kuyruğu", "eyeri"),
    ma("“Su akar, çukurunu ___.” atasözündeki boşluğa ne gelir?", "bulur", "kazar", "doldurur", "arar"),
    ma("“Az olsun, ___ olsun.” atasözündeki boşluğa ne gelir?", "öz", "çok", "tatlı", "yeter"),
    ma("“Çok yaşayan bilmez, çok ___ bilir.” atasözündeki boşluğa ne gelir?", "gezen", "uyuyan", "konuşan", "yiyen"),
    ma("“Korkunun ecele faydası ___.” atasözündeki boşluğa ne gelir?", "yok", "var", "olur", "görünür"),
    ma("“Beşikten mezara kadar ___ öğren.” atasözündeki boşluğa ne gelir?", "ilim", "zanaat", "sanat", "dil"),
    ma("“Yalancının mumu ___ kadar yanar.” atasözündeki boşluğa ne gelir?", "yatsıya", "sabaha", "akşama", "geceye")
  ]},
  {id: 'edebiyat', name: 'Edebiyat', icon: 'book', desc: 'Eser ve yazar eşleştirmesi', qs: [
    mx("“Çile” adlı eserin yazarı kimdir?", "Necip Fazıl Kısakürek", "Orhan Pamuk", "Yusuf Atılgan", "Recaizade Mahmut Ekrem"),
    mx("Aşağıdakilerden hangisi Orhan Pamuk tarafından yazılmıştır?", "Benim Adım Kırmızı", "Yılanı Öldürseler", "Şair Evlenmesi", "Yaban"),
    mx("Aşağıdakilerden hangisi Latife Tekin tarafından yazılmıştır?", "Berci Kristin Çöp Masalları", "Araba Sevdası", "Çile", "Fatih-Harbiye"),
    mx("“Kuyucaklı Yusuf” adlı eserin yazarı kimdir?", "Sabahattin Ali", "Ahmet Hamdi Tanpınar", "Şinasi", "Nâzım Hikmet"),
    mx("Aşağıdakilerden hangisi Reşat Nuri Güntekin tarafından yazılmıştır?", "Çalıkuşu", "Aylak Adam", "Berci Kristin Çöp Masalları", "Han Duvarları"),
    mx("Aşağıdakilerden hangisi Sabahattin Ali tarafından yazılmıştır?", "Kürk Mantolu Madonna", "Aylak Adam", "Alemdağ’da Var Bir Yılan", "İnce Memed"),
    mx("“Yaban” adlı eserin yazarı kimdir?", "Yakup Kadri Karaosmanoğlu", "Nâzım Hikmet", "Halide Edib Adıvar", "Halit Ziya Uşaklıgil"),
    mx("Aşağıdakilerden hangisi Yakup Kadri Karaosmanoğlu tarafından yazılmıştır?", "Yaban", "Kürk Mantolu Madonna", "Huzur", "Tutunamayanlar"),
    mx("“Sinekli Bakkal” adlı eserin yazarı kimdir?", "Halide Edib Adıvar", "Faruk Nafiz Çamlıbel", "Yusuf Atılgan", "Şinasi"),
    mx("Aşağıdakilerden hangisi Halide Edib Adıvar tarafından yazılmıştır?", "Sinekli Bakkal", "Kar", "Şair Evlenmesi", "Benim Adım Kırmızı"),
    mx("Aşağıdakilerden hangisi Ahmet Hamdi Tanpınar tarafından yazılmıştır?", "Huzur", "Han Duvarları", "Sinekli Bakkal", "Çile"),
    mx("Aşağıdakilerden hangisi Mehmet Akif Ersoy tarafından yazılmıştır?", "Safahat", "Fatih-Harbiye", "Han Duvarları", "Tutunamayanlar"),
    mx("“Kürk Mantolu Madonna” adlı eserin yazarı kimdir?", "Sabahattin Ali", "Halide Edib Adıvar", "Necip Fazıl Kısakürek", "Latife Tekin"),
    mx("Aşağıdakilerden hangisi Orhan Pamuk tarafından yazılmıştır?", "Masumiyet Müzesi", "Aşk-ı Memnu", "Huzur", "Yılanı Öldürseler"),
    mx("“Kiralık Konak” adlı eserin yazarı kimdir?", "Yakup Kadri Karaosmanoğlu", "Nâzım Hikmet", "Peyami Safa", "Latife Tekin"),
    mx("“Safahat” adlı eserin yazarı kimdir?", "Mehmet Akif Ersoy", "Nâzım Hikmet", "Sait Faik Abasıyanık", "Recaizade Mahmut Ekrem"),
    mx("Aşağıdakilerden hangisi Yaşar Kemal tarafından yazılmıştır?", "Yılanı Öldürseler", "Memleketimden İnsan Manzaraları", "Aşk-ı Memnu", "Kuyucaklı Yusuf"),
    mx("Aşağıdakilerden hangisi Recaizade Mahmut Ekrem tarafından yazılmıştır?", "Araba Sevdası", "Safahat", "Vatan Yahut Silistre", "Han Duvarları"),
    mx("Aşağıdakilerden hangisi Namık Kemal tarafından yazılmıştır?", "Vatan Yahut Silistre", "Sevgili Arsız Ölüm", "Şair Evlenmesi", "Aşk-ı Memnu"),
    mx("Aşağıdakilerden hangisi Sait Faik Abasıyanık tarafından yazılmıştır?", "Alemdağ’da Var Bir Yılan", "Huzur", "Aylak Adam", "Araba Sevdası"),
    mx("“Yılanı Öldürseler” adlı eserin yazarı kimdir?", "Yaşar Kemal", "Ahmet Hamdi Tanpınar", "Şinasi", "Namık Kemal"),
    mx("“Saatleri Ayarlama Enstitüsü” adlı eserin yazarı kimdir?", "Ahmet Hamdi Tanpınar", "Orhan Pamuk", "Peyami Safa", "Halide Edib Adıvar"),
    mx("Aşağıdakilerden hangisi Peyami Safa tarafından yazılmıştır?", "Fatih-Harbiye", "Şair Evlenmesi", "Semaver", "Sinekli Bakkal"),
    mx("Aşağıdakilerden hangisi Necip Fazıl Kısakürek tarafından yazılmıştır?", "Çile", "Masumiyet Müzesi", "Mai ve Siyah", "Aşk-ı Memnu"),
    mx("Aşağıdakilerden hangisi Sabahattin Ali tarafından yazılmıştır?", "Kuyucaklı Yusuf", "Sinekli Bakkal", "Mai ve Siyah", "Kiralık Konak"),
    mx("“Şair Evlenmesi” adlı eserin yazarı kimdir?", "Şinasi", "Oğuz Atay", "Halide Edib Adıvar", "Namık Kemal"),
    mx("Aşağıdakilerden hangisi Yakup Kadri Karaosmanoğlu tarafından yazılmıştır?", "Kiralık Konak", "Masumiyet Müzesi", "Mai ve Siyah", "Alemdağ’da Var Bir Yılan"),
    mx("“Masumiyet Müzesi” adlı eserin yazarı kimdir?", "Orhan Pamuk", "Yaşar Kemal", "Sait Faik Abasıyanık", "Sabahattin Ali"),
    mx("“Fatih-Harbiye” adlı eserin yazarı kimdir?", "Peyami Safa", "Faruk Nafiz Çamlıbel", "Recaizade Mahmut Ekrem", "Ahmet Hamdi Tanpınar"),
    mx("Aşağıdakilerden hangisi Nâzım Hikmet tarafından yazılmıştır?", "Kuvayi Milliye Destanı", "Han Duvarları", "Berci Kristin Çöp Masalları", "Tutunamayanlar"),
    mx("“Çalıkuşu” adlı eserin yazarı kimdir?", "Reşat Nuri Güntekin", "Halit Ziya Uşaklıgil", "Peyami Safa", "Sabahattin Ali"),
    mx("“Han Duvarları” adlı eserin yazarı kimdir?", "Faruk Nafiz Çamlıbel", "Oğuz Atay", "Recaizade Mahmut Ekrem", "Sait Faik Abasıyanık"),
    mx("Aşağıdakilerden hangisi Sait Faik Abasıyanık tarafından yazılmıştır?", "Semaver", "Saatleri Ayarlama Enstitüsü", "Yılanı Öldürseler", "Aylak Adam"),
    mx("Aşağıdakilerden hangisi Faruk Nafiz Çamlıbel tarafından yazılmıştır?", "Han Duvarları", "Memleketimden İnsan Manzaraları", "Kiralık Konak", "Sevgili Arsız Ölüm"),
    mx("“Araba Sevdası” adlı eserin yazarı kimdir?", "Recaizade Mahmut Ekrem", "Yusuf Atılgan", "Namık Kemal", "Halit Ziya Uşaklıgil"),
    mx("“Semaver” adlı eserin yazarı kimdir?", "Sait Faik Abasıyanık", "Recaizade Mahmut Ekrem", "Yusuf Atılgan", "Yaşar Kemal"),
    mx("“Sevgili Arsız Ölüm” adlı eserin yazarı kimdir?", "Latife Tekin", "Faruk Nafiz Çamlıbel", "Halide Edib Adıvar", "Yusuf Atılgan"),
    mx("Aşağıdakilerden hangisi Oğuz Atay tarafından yazılmıştır?", "Tutunamayanlar", "İnce Memed", "Han Duvarları", "Aylak Adam"),
    mx("“Memleketimden İnsan Manzaraları” adlı eserin yazarı kimdir?", "Nâzım Hikmet", "Halide Edib Adıvar", "Sabahattin Ali", "Latife Tekin"),
    mx("Aşağıdakilerden hangisi Orhan Pamuk tarafından yazılmıştır?", "Kar", "Tutunamayanlar", "Berci Kristin Çöp Masalları", "Memleketimden İnsan Manzaraları"),
    mx("Aşağıdakilerden hangisi Halit Ziya Uşaklıgil tarafından yazılmıştır?", "Mai ve Siyah", "Fatih-Harbiye", "Yılanı Öldürseler", "Safahat"),
    mx("Aşağıdakilerden hangisi Yusuf Atılgan tarafından yazılmıştır?", "Aylak Adam", "Kiralık Konak", "Çile", "Kuvayi Milliye Destanı"),
    mx("“Aşk-ı Memnu” adlı eserin yazarı kimdir?", "Halit Ziya Uşaklıgil", "Halide Edib Adıvar", "Yaşar Kemal", "Yakup Kadri Karaosmanoğlu"),
    mx("“Aylak Adam” adlı eserin yazarı kimdir?", "Yusuf Atılgan", "Halide Edib Adıvar", "Faruk Nafiz Çamlıbel", "Halit Ziya Uşaklıgil"),
    mx("Aşağıdakilerden hangisi Şinasi tarafından yazılmıştır?", "Şair Evlenmesi", "Yaban", "Saatleri Ayarlama Enstitüsü", "Yılanı Öldürseler"),
    mx("“Benim Adım Kırmızı” adlı eserin yazarı kimdir?", "Orhan Pamuk", "Reşat Nuri Güntekin", "Şinasi", "Necip Fazıl Kısakürek"),
    mx("“İnce Memed” adlı eserin yazarı kimdir?", "Yaşar Kemal", "Yakup Kadri Karaosmanoğlu", "Sabahattin Ali", "Orhan Pamuk"),
    mx("Aşağıdakilerden hangisi Latife Tekin tarafından yazılmıştır?", "Sevgili Arsız Ölüm", "Çile", "Kürk Mantolu Madonna", "Aylak Adam"),
    mx("Aşağıdakilerden hangisi Yaşar Kemal tarafından yazılmıştır?", "İnce Memed", "Çile", "Şair Evlenmesi", "Memleketimden İnsan Manzaraları"),
    mx("“Dokuzuncu Hariciye Koğuşu” adlı eserin yazarı kimdir?", "Peyami Safa", "Halide Edib Adıvar", "Namık Kemal", "Yaşar Kemal"),
    mx("“Huzur” adlı eserin yazarı kimdir?", "Ahmet Hamdi Tanpınar", "Latife Tekin", "Peyami Safa", "Orhan Pamuk"),
    mx("“Kuvayi Milliye Destanı” adlı eserin yazarı kimdir?", "Nâzım Hikmet", "Necip Fazıl Kısakürek", "Sabahattin Ali", "Faruk Nafiz Çamlıbel"),
    mx("“Vatan Yahut Silistre” adlı eserin yazarı kimdir?", "Namık Kemal", "Latife Tekin", "Mehmet Akif Ersoy", "Yusuf Atılgan"),
    mx("“Kar” adlı eserin yazarı kimdir?", "Orhan Pamuk", "Nâzım Hikmet", "Halit Ziya Uşaklıgil", "Sabahattin Ali"),
    mx("Aşağıdakilerden hangisi Peyami Safa tarafından yazılmıştır?", "Dokuzuncu Hariciye Koğuşu", "Kürk Mantolu Madonna", "Mai ve Siyah", "Kar"),
    mx("Aşağıdakilerden hangisi Ahmet Hamdi Tanpınar tarafından yazılmıştır?", "Saatleri Ayarlama Enstitüsü", "Semaver", "Yaban", "Alemdağ’da Var Bir Yılan"),
    mx("“Berci Kristin Çöp Masalları” adlı eserin yazarı kimdir?", "Latife Tekin", "Yusuf Atılgan", "Yaşar Kemal", "Peyami Safa"),
    mx("Aşağıdakilerden hangisi Halit Ziya Uşaklıgil tarafından yazılmıştır?", "Aşk-ı Memnu", "Dokuzuncu Hariciye Koğuşu", "Araba Sevdası", "Aylak Adam"),
    mx("“Tutunamayanlar” adlı eserin yazarı kimdir?", "Oğuz Atay", "Orhan Pamuk", "Yakup Kadri Karaosmanoğlu", "Yaşar Kemal"),
    mx("“Alemdağ’da Var Bir Yılan” adlı eserin yazarı kimdir?", "Sait Faik Abasıyanık", "Reşat Nuri Güntekin", "Necip Fazıl Kısakürek", "Halide Edib Adıvar"),
    mx("“Mai ve Siyah” adlı eserin yazarı kimdir?", "Halit Ziya Uşaklıgil", "Nâzım Hikmet", "Namık Kemal", "Necip Fazıl Kısakürek"),
    mx("Aşağıdakilerden hangisi Nâzım Hikmet tarafından yazılmıştır?", "Memleketimden İnsan Manzaraları", "Sevgili Arsız Ölüm", "Kuyucaklı Yusuf", "Aşk-ı Memnu")
  ]},
  {id: 'uzay', name: 'Uzay', icon: 'planet', desc: 'Gezegenler ve uzay bilgisi', qs: [
    mu("Güneş’e en yakın gezegen hangisidir?", "Merkür", "Venüs", "Mars", "Dünya"),
    mu("Güneş sisteminin en büyük gezegeni hangisidir?", "Jüpiter", "Satürn", "Neptün", "Uranüs"),
    mu("Halkalarıyla ünlü gezegen hangisidir?", "Satürn", "Mars", "Venüs", "Merkür"),
    mu("“Kızıl gezegen” olarak bilinen gezegen hangisidir?", "Mars", "Venüs", "Jüpiter", "Merkür"),
    mu("Güneş sisteminde kaç gezegen vardır?", "8", "7", "9", "10"),
    mu("Güneş’e en uzak gezegen hangisidir?", "Neptün", "Uranüs", "Satürn", "Jüpiter"),
    mu("Güneş sisteminin en sıcak gezegeni hangisidir?", "Venüs", "Merkür", "Mars", "Jüpiter"),
    mu("Güneş sisteminin en küçük gezegeni hangisidir?", "Merkür", "Mars", "Venüs", "Dünya"),
    mu("Dünya’nın doğal uydusu hangisidir?", "Ay", "Titan", "Europa", "Fobos"),
    mu("Güneş’in ışığı Dünya’ya yaklaşık kaç dakikada ulaşır?", "8", "1", "30", "60"),
    mu("Ay’a ilk ayak basan insan kimdir?", "Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "John Glenn"),
    mu("İnsanlı ilk Ay yolculuğunu gerçekleştiren Apollo 11 hangi yıl gerçekleşti?", "1969", "1961", "1975", "1957"),
    mu("Uzaya çıkan ilk insan kimdir?", "Yuri Gagarin", "Neil Armstrong", "Alan Shepard", "Valentina Tereshkova"),
    mu("Dünya’nın ilk yapay uydusu hangisidir?", "Sputnik 1", "Apollo 11", "Voyager 1", "Hubble"),
    mu("Uzaya giden ilk Türk astronot kimdir?", "Alper Gezeravcı", "Tuva Atasever", "Cahit Arf", "Aziz Sancar"),
    mu("Samanyolu’na en yakın büyük sarmal galaksi hangisidir?", "Andromeda", "Üçgen", "Girdap", "Sombrero"),
    mu("Halley Kuyruklu Yıldızı yaklaşık kaç yılda bir görülür?", "76", "10", "150", "30"),
    mu("Mars’ın uyduları hangileridir?", "Fobos ve Deimos", "Io ve Europa", "Titan ve Rhea", "Ay ve Charon"),
    mu("Jüpiter’deki dev fırtınanın adı nedir?", "Büyük Kızıl Leke", "Büyük Karanlık Leke", "Kuzey Işıkları", "Halka Fırtınası"),
    mu("2006’da cüce gezegen sınıfına alınan gök cismi hangisidir?", "Plüton", "Uranüs", "Neptün", "Ceres"),
    mu("Satürn’ün en büyük uydusu hangisidir?", "Titan", "Europa", "Ay", "Triton"),
    mu("Işık yılı neyi ölçen bir birimdir?", "Mesafe", "Zaman", "Hız", "Kütle"),
    mu("Güneş tutulması sırasında hangi gök cismi Güneş ile Dünya arasına girer?", "Ay", "Mars", "Venüs", "Merkür"),
    mu("Gece ve gündüzün oluşmasının nedeni nedir?", "Dünya’nın kendi ekseni etrafında dönmesi", "Dünya’nın Güneş etrafında dönmesi", "Ay’ın Dünya etrafında dönmesi", "Güneş’in kendi etrafında dönmesi"),
    mu("Güneş sisteminin en yüksek dağı olan Olympus Mons hangi gezegendedir?", "Mars", "Venüs", "Jüpiter", "Dünya"),
    mu("Güneş nasıl bir gök cismidir?", "Yıldız", "Gezegen", "Uydu", "Kuyruklu yıldız"),
    mu("Dünya, Güneş çevresindeki bir turunu yaklaşık ne kadar sürede tamamlar?", "365 gün", "30 gün", "24 saat", "12 ay 3 gün")
  ]}
];
