// Zuqio İngilizce kategorisi · ek sorular. Biçim questions-en.js ile aynıdır.
const e = (sub, d, q, ...rest) => {
  const info = rest.pop();
  return {t: 'mc', cat: 'İngilizce', sub, d, q, o: rest, info};
};

export const EN2 = [
  /* ===== Kelime ===== */
  e('Kelime','k','“Elma” İngilizcede nedir?','apple','apply','ankle','animal','apple = elma · I eat an apple every day. (Her gün bir elma yerim.)'),
  e('Kelime','k','“Kitap” İngilizcede nedir?','book','boot','box','back','book = kitap · This book is interesting. (Bu kitap ilginç.)'),
  e('Kelime','k','“Pencere” İngilizcede nedir?','window','wind','winter','wall','window = pencere · Please open the window. (Lütfen pencereyi aç.)'),
  e('Kelime','k','“Arkadaş” İngilizcede nedir?','friend','fiend','fried','fresh','friend = arkadaş · She is my best friend. (O benim en iyi arkadaşım.)'),
  e('Kelime','k','“Okul” İngilizcede nedir?','school','shoe','scool','skull','school = okul · I go to school by bus. (Okula otobüsle giderim.)'),
  e('Kelime','k','“Mutfak” İngilizcede nedir?','kitchen','chicken','kitten','king','kitchen = mutfak · Mom is in the kitchen. (Annem mutfakta.)'),
  e('Kelime','k','“Yağmur” İngilizcede nedir?','rain','train','road','rice','rain = yağmur · It is raining today. (Bugün yağmur yağıyor.)'),
  e('Kelime','k','“Ekmek” İngilizcede nedir?','bread','breath','bed','brush','bread = ekmek · I want some bread. (Biraz ekmek istiyorum.)'),
  e('Kelime','k','“Mavi” İngilizcede nedir?','blue','black','blow','bone','blue = mavi · The sky is blue. (Gökyüzü mavi.)'),
  e('Kelime','k','“Hafta” İngilizcede nedir?','week','weak','wick','wake','week = hafta (weak = zayıf ile karışmasın) · There are seven days in a week.'),
  e('Kelime','k','“Doktor” İngilizcede nedir?','doctor','dentist','teacher','driver','doctor = doktor · The doctor helps sick people. (Doktor hastalara yardım eder.)'),
  e('Kelime','k','“Küçük” İngilizcede nedir?','small','tall','smell','smile','small = küçük · It is a small house. (Küçük bir ev.)'),
  e('Kelime','k','“Seyahat etmek” İngilizcede nedir?','travel','trouble','tray','treat','travel = seyahat etmek · I love to travel. (Seyahat etmeyi severim.)'),
  e('Kelime','o','“Borç almak” anlamı hangisidir?','borrow','lend','lose','keep','borrow = ödünç almak · lend = ödünç vermek · Can I borrow your pen?'),
  e('Kelime','o','“Zor, güç” anlamında hangisi kullanılır?','difficult','delicious','dangerous','different','difficult = zor · This exam is difficult. (Bu sınav zor.)'),
  e('Kelime','o','“Kaçırmak (otobüsü)” anlamında hangi fiil kullanılır?','miss','lose','skip','pass','miss = kaçırmak · I missed the bus. (Otobüsü kaçırdım.)'),
  e('Kelime','o','“Aklında tutmak” anlamında hangisi doğrudur?','remember','remind','repeat','return','remember = hatırlamak · I remember his name. (Adını hatırlıyorum.)'),
  e('Kelime','o','“Sağlıklı” için hangisi kullanılır?','healthy','wealthy','heavy','happy','healthy = sağlıklı · wealthy = zengin · Eat healthy food. (Sağlıklı yemek ye.)'),
  e('Kelime','o','“Deneyim” anlamı hangisidir?','experience','experiment','expert','explain','experience = deneyim · experiment = deney · She has a lot of experience.'),
  e('Kelime','o','“Başarmak” anlamında hangisi kullanılır?','achieve','arrive','attack','avoid','achieve = başarmak · He achieved his goal. (Hedefine ulaştı.)'),
  e('Kelime','o','“Kaçınmak” anlamı hangisidir?','avoid','allow','admit','adopt','avoid = kaçınmak · Avoid sugary drinks. (Şekerli içeceklerden kaçın.)'),
  e('Kelime','o','“Yaklaşık, tahminen” anlamı hangisidir?','approximately','absolutely','accidentally','apparently','approximately = yaklaşık olarak · It costs approximately ten dollars.'),
  e('Kelime','z','“Çok kısa süreli” anlamına gelen sıfat hangisidir?','brief','broad','brittle','bright','brief = kısa, özlü · Please keep your speech brief.'),
  e('Kelime','z','“Eşi benzeri olmayan” anlamında hangisi kullanılır?','unique','common','similar','ordinary','unique = tek, eşsiz · Every fingerprint is unique.'),
  e('Kelime','z','“Gereksiz, fazlalık” anlamı hangisidir?','redundant','relevant','reluctant','reliable','redundant = gereksiz, fazla · The second paragraph is redundant.'),
  e('Kelime','z','“Tereddütlü, isteksiz” anlamı hangisidir?','reluctant','relevant','reliable','relative','reluctant = isteksiz · He was reluctant to help.'),
  e('Kelime','z','“Hafifletmek (acıyı vb.)” anlamında hangi fiil kullanılır?','alleviate','aggravate','accelerate','accumulate','alleviate = hafifletmek · This medicine will alleviate the pain.'),
  e('Kelime','z','“Güvenilir” anlamı hangisidir?','reliable','reluctant','relevant','reasonable','reliable = güvenilir · He is a reliable friend.'),
  e('Kelime','z','“Çelişkili, tutarsız” anlamı hangisidir?','inconsistent','independent','inevitable','incredible','inconsistent = tutarsız · His stories were inconsistent.'),

  /* ===== Dilbilgisi ===== */
  e('Dilbilgisi','k','She ___ a student.','is','am','are','be','She/He/It ile “is” kullanılır. She is a student. (O bir öğrenci.)'),
  e('Dilbilgisi','k','I ___ from Turkey.','am','is','are','be','I ile “am” kullanılır. I am from Turkey. (Türkiye’denim.)'),
  e('Dilbilgisi','k','They ___ at home.','are','is','am','be','They/We/You ile “are”. They are at home. (Onlar evde.)'),
  e('Dilbilgisi','k','He ___ football every Sunday.','plays','play','playing','played','He/She/It ile geniş zamanda fiile -s gelir. He plays football.'),
  e('Dilbilgisi','k','There ___ two cats in the garden.','are','is','be','am','Çoğul isimle “there are”. There are two cats. (Bahçede iki kedi var.)'),
  e('Dilbilgisi','k','___ you like tea?','Do','Does','Are','Is','You ile “Do”. Do you like tea? (Çay sever misin?)'),
  e('Dilbilgisi','k','This is ___ apple.','an','a','the','some','Ünlü sesle başlayan kelimeden önce “an”. an apple, a book.'),
  e('Dilbilgisi','k','She ___ not like coffee.','does','do','is','are','Olumsuz geniş zamanda “does not”. She does not like coffee.'),
  e('Dilbilgisi','o','I have lived here ___ 2015.','since','for','from','during','since + başlangıç noktası · for + süre. I have lived here since 2015.'),
  e('Dilbilgisi','o','If it rains, we ___ at home.','will stay','would stay','stayed','are staying','If + geniş zaman, will + fiil (Tip 1). If it rains, we will stay at home.'),
  e('Dilbilgisi','o','He is ___ than his brother.','taller','tallest','more tall','the taller','Kısa sıfatlarda -er: taller than. He is taller than his brother.'),
  e('Dilbilgisi','o','She is the ___ girl in the class.','smartest','smarter','more smart','smartly','En üstünlük: the + -est. the smartest girl.'),
  e('Dilbilgisi','o','We ___ dinner when the phone rang.','were having','had','have','are having','Süregelen eylem + kesen eylem: past continuous. We were having dinner when…'),
  e('Dilbilgisi','o','How ___ water do you drink a day?','much','many','few','a few','Sayılamayan isimle “much”. How much water…?'),
  e('Dilbilgisi','o','How ___ books did you read?','many','much','little','a little','Sayılabilen çoğul isimle “many”. How many books…?'),
  e('Dilbilgisi','o','He asked me where I ___.','lived','live','am living','have lived','Dolaylı anlatımda zaman bir adım geriye gider. He asked me where I lived.'),
  e('Dilbilgisi','z','Had I known, I ___ come.','would have','will have','would','had','Tip 3 devrik yapı: Had I known = If I had known. I would have come.'),
  e('Dilbilgisi','z','Not only ___ late, but he also forgot the keys.','did he arrive','he arrived','he did arrive','arrived he','“Not only” başta gelince devrik cümle: Not only did he arrive late…'),
  e('Dilbilgisi','z','The man ___ car was stolen called the police.','whose','who','which','whom','whose = kimin (sahiplik). The man whose car was stolen…'),
  e('Dilbilgisi','z','She suggested ___ early.','leaving','to leave','leave','left','suggest + -ing. She suggested leaving early.'),
  e('Dilbilgisi','z','By next year, I ___ here for ten years.','will have worked','will work','have worked','would work','Future perfect: will have + V3. By next year, I will have worked here…'),
  e('Dilbilgisi','z','It’s high time we ___.','left','leave','leaving','will leave','“It’s high time” + geçmiş zaman. It’s high time we left. (Gitme vakti geldi.)'),

  /* ===== Kalıp ===== */
  e('Kalıp','k','Birine “Nasılsın?” demek için hangisi kullanılır?','How are you?','Who are you?','Where are you?','What are you?','How are you? = Nasılsın? · Cevap: I’m fine, thank you.'),
  e('Kalıp','k','“Teşekkür ederim” nasıl söylenir?','Thank you','Excuse me','Good night','See you','Thank you = Teşekkür ederim.'),
  e('Kalıp','k','“Rica ederim” karşılığı hangisidir?','You’re welcome','I’m sorry','Good luck','Never mind','You’re welcome = Rica ederim.'),
  e('Kalıp','k','Sabah selamı hangisidir?','Good morning','Good night','Good evening','Good bye','Good morning = Günaydın.'),
  e('Kalıp','k','“Adın ne?” nasıl sorulur?','What’s your name?','Where’s your name?','Who’s your name?','How’s your name?','What’s your name? = Adın ne? · My name is Ali.'),
  e('Kalıp','k','“Özür dilerim” hangisidir?','I’m sorry','I’m fine','I’m tired','I’m ready','I’m sorry = Özür dilerim.'),
  e('Kalıp','o','Birinin sözünü kesmeden önce kibarca ne denir?','Excuse me','Never mind','Take care','Good luck','Excuse me = Affedersiniz, pardon.'),
  e('Kalıp','o','“Anlamadım, tekrar eder misiniz?” hangisidir?','Could you repeat that, please?','Could you eat that?','Can you repair that?','Would you retreat that?','Could you repeat that, please? = Tekrar eder misiniz?'),
  e('Kalıp','o','“Katılıyorum” nasıl söylenir?','I agree','I argue','I allow','I accept to','I agree = Katılıyorum.'),
  e('Kalıp','o','“Fark etmez” anlamında hangisi kullanılır?','It doesn’t matter','It doesn’t make','It doesn’t care','It doesn’t mind','It doesn’t matter = Fark etmez, önemli değil.'),
  e('Kalıp','o','“Kendine iyi bak” hangisidir?','Take care','Take off','Take over','Take place','Take care! = Kendine iyi bak.'),
  e('Kalıp','o','“Bol şans” hangisidir?','Good luck','Good job','Good time','Good lucky','Good luck! = Bol şans!'),
  e('Kalıp','z','“Sizi tanıdığıma memnun oldum” hangisidir?','Pleased to meet you','Pleased to miss you','Please to meet you','Pleasure to met you','Pleased to meet you = Tanıştığımıza memnun oldum.'),
  e('Kalıp','z','“Bir saniye lütfen” hangisidir?','Just a moment, please','Just a movement, please','Just a month, please','Just a minute’s, please','Just a moment, please = Bir dakika lütfen.'),
  e('Kalıp','z','“Aynı fikirde değilim” nasıl söylenir?','I beg to differ','I beg to agree','I beg to defer','I beg for different','I beg to differ = Kibarca katılmıyorum.'),

  /* ===== Edat ===== */
  e('Edat','k','I get up ___ 7 o’clock.','at','in','on','to','Saatlerle “at” kullanılır. at 7 o’clock.'),
  e('Edat','k','My birthday is ___ May.','in','at','on','to','Aylarla “in” kullanılır. in May.'),
  e('Edat','k','We have a meeting ___ Monday.','on','in','at','to','Günlerle “on” kullanılır. on Monday.'),
  e('Edat','k','The cat is ___ the table. (altında)','under','over','above','across','under = altında. The cat is under the table.'),
  e('Edat','o','He is good ___ math.','at','in','on','for','good at = -de iyi. He is good at math.'),
  e('Edat','o','I am interested ___ music.','in','on','at','for','interested in = -ile ilgilenmek. I am interested in music.'),
  e('Edat','o','He depends ___ his parents.','on','of','at','to','depend on = -e bağlı olmak. He depends on his parents.'),
  e('Edat','z','She is married ___ a doctor.','to','with','by','for','married to = ile evli. She is married to a doctor.'),
  e('Edat','z','This is different ___ what I expected.','from','with','at','of','different from = -den farklı. (İng.-İng. “to”, Amr.-İng. “than” da görülür.)'),
  e('Edat','z','He is responsible ___ the project.','for','of','to at','on','responsible for = -den sorumlu. He is responsible for the project.'),

  /* ===== Phrasal verb ===== */
  e('Phrasal verb','k','“Put on” ne demektir?','giymek','çıkarmak','atmak','almak','put on = giymek · Put on your coat. (Montunu giy.)'),
  e('Phrasal verb','k','“Turn off” ne demektir?','kapatmak','açmak','çevirmek','büyütmek','turn off = kapatmak · Turn off the light. (Işığı kapat.)'),
  e('Phrasal verb','k','“Sit down” ne demektir?','oturmak','ayağa kalkmak','yürümek','uyumak','sit down = oturmak · Please sit down. (Lütfen oturun.)'),
  e('Phrasal verb','o','“Give up” ne demektir?','vazgeçmek','vermek','yukarı çıkmak','beklemek','give up = vazgeçmek · Don’t give up! (Pes etme!)'),
  e('Phrasal verb','o','“Look for” ne demektir?','aramak','bakmak','görmek','beklemek','look for = aramak · I’m looking for my keys. (Anahtarlarımı arıyorum.)'),
  e('Phrasal verb','o','“Find out” ne demektir?','öğrenmek (keşfetmek)','kaybetmek','dışarı çıkmak','bulaşmak','find out = öğrenmek · I found out the truth. (Gerçeği öğrendim.)'),
  e('Phrasal verb','o','“Get along with” ne demektir?','iyi geçinmek','binmek','anlatmak','uzaklaşmak','get along with = iyi anlaşmak · I get along with my neighbors.'),
  e('Phrasal verb','o','“Run out of” ne demektir?','bitmek, tükenmek','dışarı koşmak','kaçmak','yarışmak','run out of = tükenmek · We ran out of milk. (Sütümüz bitti.)'),
  e('Phrasal verb','o','“Break down” araç için ne demektir?','bozulmak, arızalanmak','hızlanmak','park etmek','ısınmak','break down = arızalanmak · The car broke down. (Araba bozuldu.)'),
  e('Phrasal verb','z','“Call off” ne demektir?','iptal etmek','çağırmak','telefon etmek','ertelemek','call off = iptal etmek · The match was called off. (Maç iptal edildi.)'),
  e('Phrasal verb','z','“Come up with” ne demektir?','(fikir) bulmak, üretmek','yaklaşmak','yukarı çıkmak','karşılaşmak','come up with = fikir bulmak · She came up with a great idea.'),
  e('Phrasal verb','z','“Put up with” ne demektir?','katlanmak, tahammül etmek','kurmak','kaldırmak','koymak','put up with = katlanmak · I can’t put up with this noise.'),
  e('Phrasal verb','z','“Look up to” ne demektir?','saygı duymak, örnek almak','yukarı bakmak','araştırmak','aramak','look up to = saygı duymak · I look up to my teacher.'),
  e('Phrasal verb','z','“Bring up” (çocuk için) ne demektir?','yetiştirmek, büyütmek','getirmek','yukarı taşımak','sormak','bring up = büyütmek · She was brought up by her grandparents.'),

  /* ===== Dikkat ===== */
  e('Dikkat','k','“Yarın” hangi yazımla doğrudur?','tomorrow','tommorow','tomorow','tomorrw','tomorrow = yarın. İki r, tek m: to-mor-row.'),
  e('Dikkat','k','“Güzel” hangi yazımla doğrudur?','beautiful','beatiful','beautifull','butiful','beautiful = güzel. beau-ti-ful.'),
  e('Dikkat','o','Their/there: hangi cümle doğru?','Their house is big.','There house is big.','They’re house is big.','Thier house is big.','their = onların · there = orada · they’re = they are.'),
  e('Dikkat','o','You’re/your: hangi cümle doğru?','You’re my friend.','Your my friend.','You’r my friend.','Youre my friend.','you’re = you are · your = senin. You’re my friend.'),
  e('Dikkat','o','“Almak” (receive) hangi yazımla doğrudur?','receive','recieve','receeve','receve','“i before e, except after c” → receive.'),
  e('Dikkat','z','Less/fewer: hangi cümle doğrudur?','I have less friends than you.','I have fewer friends than you.','I have a few friend.','I have lesser friend.','Sayılabilir isimle “fewer”, sayılamayanla “less”. Doğrusu: fewer friends.'),
  e('Dikkat','z','“Etkilemek” için hangi kelime kullanılır?','affect','effect','affection','effection','affect (fiil) = etkilemek · effect (isim) = etki.'),
  e('Dikkat','z','“Principal” ile “principle” farkı nedir?','principal = müdür; principle = ilke','principal = ilke; principle = müdür','İkisi de müdür demek','İkisi de ilke demek','principal (müdür/ana) · principle (ilke). The school principal… / a moral principle.'),
  e('Dikkat','z','Hangisi “geçmek, ilerlemek” anlamına gelen doğru yazımdır?','proceed','procede','proceede','proseed','proceed = ilerlemek (procedure ile aynı kök). Please proceed to the gate.'),

  /* ===== Deyim ===== */
  e('Deyim','o','“It’s raining cats and dogs” ne demektir?','Bardaktan boşanırcasına yağmur yağıyor','Kedi ve köpekler yağıyor','Hava çok sıcak','Sis var','Bu deyim sağanak yağmur demektir. (Hayvanlarla ilgisi yoktur.)'),
  e('Deyim','o','“Break the ice” ne demektir?','Buzları eritmek, ortamı yumuşatmak','Buzu kırmak, soğuk içmek','Kavga etmek','Bir şey kırmak','break the ice = tanışma sırasında gerginliği azaltmak.'),
  e('Deyim','o','“Piece of cake” ne demektir?','Çok kolay iş','Tatlı yemek','Küçük hediye','Pasta parçası alma','piece of cake = çocuk oyuncağı. The exam was a piece of cake.'),
  e('Deyim','o','“Once in a blue moon” ne demektir?','Çok nadiren','Her gece','Hiçbir zaman','Her ay','once in a blue moon = ayda yılda bir, çok seyrek.'),
  e('Deyim','o','“Under the weather” ne demektir?','Keyifsiz, hasta gibi','Yağmurda','Hava durumu raporu','Çok mutlu','under the weather = biraz rahatsız. I’m feeling under the weather.'),
  e('Deyim','o','“Hit the books” ne demektir?','Ders çalışmaya koyulmak','Kitaplara vurmak','Kitap satın almak','Kütüphaneye gitmek','hit the books = çok çalışmak. I have to hit the books tonight.'),
  e('Deyim','z','“Spill the beans” ne demektir?','Sırrı ağzından kaçırmak','Fasulye dökmek','Yemek yapmak','Hata yapmak','spill the beans = sır vermek. Who spilled the beans?'),
  e('Deyim','z','“Cost an arm and a leg” ne demektir?','Çok pahalı olmak','Kolunu ve bacağını kaybetmek','Sağlığa zararlı olmak','Ucuz olmak','cost an arm and a leg = çok pahalıya mal olmak.'),
  e('Deyim','z','“Burn the midnight oil” ne demektir?','Gece geç saatlere kadar çalışmak','Yağ yakmak','Isıtma yapmak','Yemek pişirmek','burn the midnight oil = gece geç saate kadar çalışmak.'),
  e('Deyim','z','“The ball is in your court” ne demektir?','Karar sırası sende','Top senin sahanda','Maçı kazandın','Tenis oynayalım','the ball is in your court = Sıra sende, karar senin.'),
  e('Deyim','z','“Bite the bullet” ne demektir?','Dişini sıkıp zor işe katlanmak','Kurşun ısırmak','Silah kullanmak','Yemek yemek','bite the bullet = zor bir şeyi cesaretle yapmak.')
];
