// Zuqio ek soru havuzu · bölüm 1 (Genel kültür, Türkiye tarihi, Dünya tarihi, Coğrafya, Bilim)
// Biçim questions.js ile aynıdır: ilk şık doğrudur, oyunda karıştırılır.
const m = (cat, d, q, ...o) => ({t: 'mc', cat, d, q, o});
const n = (cat, d, q, a, unit, tolAbs) => tolAbs ? {t: 'num', cat, d, q, a, unit, tolAbs} : {t: 'num', cat, d, q, a, unit};

export const MORE1 = [
  /* ================= Genel kültür ================= */
  m('Genel kültür','k','Bir yılda kaç ay vardır?','12','10','11','13'),
  m('Genel kültür','k','Hangi hayvan “çöl gemisi” olarak bilinir?','Deve','At','Eşek','Katır'),
  m('Genel kültür','k','Su deniz seviyesinde kaç derecede donar?','0 °C','10 °C','–5 °C','100 °C'),
  m('Genel kültür','k','Aşağıdakilerden hangisi bir sebzedir?','Havuç','Elma','Üzüm','Kiraz'),
  m('Genel kültür','k','Güneş hangi yönden doğar?','Doğu','Batı','Kuzey','Güney'),
  m('Genel kültür','k','Bir haftada kaç gün vardır?','7','5','6','8'),
  m('Genel kültür','k','Bir dakikada kaç saniye vardır?','60','50','100','30'),
  m('Genel kültür','o','Dünyanın en kalabalık kıtası hangisidir?','Asya','Afrika','Avrupa','Güney Amerika'),
  m('Genel kültür','o','İstanbul hangi iki kıtada yer alır?','Avrupa ve Asya','Asya ve Afrika','Avrupa ve Afrika','Asya ve Okyanusya'),
  m('Genel kültür','o','Olimpiyat Oyunları kaç yılda bir yapılır?','4 yılda bir','2 yılda bir','3 yılda bir','5 yılda bir'),
  m('Genel kültür','o','Roma rakamlarında “M” kaç eder?','1000','500','100','5000'),
  m('Genel kültür','o','Hangi renk, kırmızı ile sarının karışımından elde edilir?','Turuncu','Yeşil','Mor','Kahverengi'),
  m('Genel kültür','o','Hangi hayvan yumurtadan çıkar?','Penguen','Fil','Yunus','Yarasa'),
  n('Genel kültür','o','Satrançta her oyuncu kaç taşla başlar?',16,'taş'),
  n('Genel kültür','o','Piyanonun standart olarak kaç tuşu vardır?',88,'tuş'),
  n('Genel kültür','o','Artık yıllarda şubat ayı kaç gün çeker?',29,'gün'),
  n('Genel kültür','o','Tavlada her oyuncunun kaç pulu vardır?',15,'pul'),
  m('Genel kültür','z','Dünyada ana dil olarak en çok konuşulan dil hangisidir?','Mandarin Çincesi','İngilizce','İspanyolca','Hintçe'),
  m('Genel kültür','z','Uluslararası imdat çağrısı SOS, mors alfabesinde nasıl gösterilir?','Üç nokta, üç çizgi, üç nokta','Üç çizgi, üç nokta, üç çizgi','Beş nokta','Üç nokta, üç nokta, üç çizgi'),
  m('Genel kültür','z','Aşağıdakilerden hangisi bir Nobel Ödülü dalı değildir?','Matematik','Fizik','Kimya','Edebiyat'),
  m('Genel kültür','z','Bir dolarlık banknotun üzerindeki portre kime aittir?','George Washington','Abraham Lincoln','Benjamin Franklin','Thomas Jefferson'),
  m('Genel kültür','z','Aşağıdaki sayılardan hangisi hem asaldır hem de çifttir?','2','1','4','0'),
  m('Genel kültür','z','Aşağıdaki hayvanlardan hangisi Kuzey Kutbu’nda yaşamaz?','Penguen','Kutup ayısı','Mors','Kutup tilkisi'),

  /* ================= Türkiye tarihi ================= */
  m('Türkiye tarihi','k','Atatürk hangi şehirde doğmuştur?','Selanik','İstanbul','Ankara','Manastır'),
  m('Türkiye tarihi','k','İstiklal Marşı’nı kim yazmıştır?','Mehmet Âkif Ersoy','Ziya Gökalp','Namık Kemal','Yahya Kemal Beyatlı'),
  m('Türkiye tarihi','k','Cumhuriyet Bayramı hangi tarihte kutlanır?','29 Ekim','23 Nisan','19 Mayıs','30 Ağustos'),
  m('Türkiye tarihi','k','23 Nisan hangi bayramdır?','Ulusal Egemenlik ve Çocuk Bayramı','Zafer Bayramı','Gençlik ve Spor Bayramı','Cumhuriyet Bayramı'),
  m('Türkiye tarihi','k','Cumhuriyet ilan edildiğinde başkent olan şehir hangisidir?','Ankara','İstanbul','İzmir','Bursa'),
  m('Türkiye tarihi','k','Atatürk’ün manevi kızı olan ve ilk Türk kadın pilotlarından biri sayılan kişi kimdir?','Sabiha Gökçen','Halide Edib Adıvar','Afet İnan','Nezihe Muhiddin'),
  m('Türkiye tarihi','o','Fetihten önce Osmanlı Devleti’nin başkenti hangi şehirdi?','Edirne','Bursa','Konya','Ankara'),
  m('Türkiye tarihi','o','İstiklal Marşı’nın bestecisi kimdir?','Osman Zeki Üngör','Ali Ufkî','Hamamizade İsmail Dede Efendi','Cemal Reşit Rey'),
  m('Türkiye tarihi','o','Cumhuriyet’in ilk başbakanı kimdir?','İsmet İnönü','Fethi Okyar','Celal Bayar','Refik Saydam'),
  m('Türkiye tarihi','o','Çanakkale Savaşları’nda Mustafa Kemal hangi tümenin komutanıydı?','19. Tümen','57. Tümen','9. Tümen','5. Tümen'),
  m('Türkiye tarihi','o','Malazgirt Meydan Muharebesi’ni kazanan Selçuklu sultanı kimdir?','Alp Arslan','Melikşah','Tuğrul Bey','I. Kılıçarslan'),
  m('Türkiye tarihi','o','Anadolu Selçuklu Devleti’nin başkenti hangi şehirdi?','Konya','Sivas','Kayseri','Ankara'),
  m('Türkiye tarihi','o','Yeniçeri Ocağı hangi padişah döneminde kaldırıldı?','II. Mahmud','III. Selim','Abdülhamid II','II. Mehmed'),
  m('Türkiye tarihi','o','Orhun Yazıtları hangi Türk devletine aittir?','Göktürkler','Hunlar','Uygurlar','Karahanlılar'),
  m('Türkiye tarihi','o','Sultanahmet Camii hangi padişah döneminde yaptırıldı?','I. Ahmed','Kanuni Sultan Süleyman','II. Bayezid','IV. Murad'),
  m('Türkiye tarihi','o','Nene Hatun hangi savaşta kahramanlık göstermiştir?','93 Harbi (Osmanlı-Rus Savaşı)','Çanakkale Savaşı','Kurtuluş Savaşı','Balkan Savaşı'),
  n('Türkiye tarihi','o','Saltanat hangi yıl kaldırıldı?',1922,'yılı',20),
  n('Türkiye tarihi','o','Halifelik hangi yıl kaldırıldı?',1924,'yılı',20),
  n('Türkiye tarihi','o','Türk Medeni Kanunu hangi yıl kabul edildi?',1926,'yılı',20),
  n('Türkiye tarihi','o','İstanbul Boğaz Köprüsü hangi yıl hizmete açıldı?',1973,'yılı',20),
  n('Türkiye tarihi','z','Yavuz Sultan Selim’in Safevilere karşı kazandığı Çaldıran Savaşı hangi yıl yapıldı?',1514,'yılı',30),
  n('Türkiye tarihi','z','Birinci Viyana Kuşatması hangi yıl yapıldı?',1529,'yılı',30),
  n('Türkiye tarihi','z','Hatay hangi yıl Türkiye’ye katıldı?',1939,'yılı',20),
  n('Türkiye tarihi','z','Türkiye hangi yıl Birleşmiş Milletler’in kurucu üyelerinden biri oldu?',1945,'yılı',20),
  m('Türkiye tarihi','z','Orhun Yazıtları’nı ilk çözen Danimarkalı dil bilimci kimdir?','Vilhelm Thomsen','Wilhelm Radloff','Johann Gutenberg','Heinrich Schliemann'),
  m('Türkiye tarihi','z','Hun İmparatorluğu’nun kurucusu kabul edilen hükümdar kimdir?','Mete Han','Attila','Bumin Kağan','Bilge Kağan'),
  m('Türkiye tarihi','z','Selçukluların Gazneliler’i yendiği 1040 savaşı hangisidir?','Dandanakan','Malazgirt','Miryokefalon','Kösedağ'),
  m('Türkiye tarihi','z','Osmanlı tarihinde en uzun süre tahtta kalan padişah kimdir?','Kanuni Sultan Süleyman','II. Abdülhamid','IV. Mehmed','I. Ahmed'),

  /* ================= Dünya tarihi ================= */
  m('Dünya tarihi','k','Antik Mısır’da firavunların mezarı olarak yapılan dev yapılara ne denir?','Piramit','Ziggurat','Kale','Tapınak'),
  m('Dünya tarihi','k','Amerika Birleşik Devletleri’nin ilk başkanı kimdir?','George Washington','Abraham Lincoln','Thomas Jefferson','John Adams'),
  m('Dünya tarihi','k','Roma İmparatorluğu’nun başkenti neresiydi?','Roma','Atina','İskenderiye','Kartaca'),
  m('Dünya tarihi','k','Cengiz Han hangi halkın lideriydi?','Moğollar','Türkler','Çinliler','Persler'),
  m('Dünya tarihi','k','Vikingler hangi bölgeden çıkmıştır?','İskandinavya','Akdeniz','Balkanlar','Anadolu'),
  m('Dünya tarihi','o','Matbaayı Avrupa’da geliştiren kişi olarak bilinen isim kimdir?','Johannes Gutenberg','Leonardo da Vinci','Galileo Galilei','Martin Luther'),
  m('Dünya tarihi','o','Antik Olimpiyat Oyunları hangi kentte düzenlenirdi?','Olympia','Atina','Sparta','Korint'),
  m('Dünya tarihi','o','1945’te atom bombası atılan iki Japon şehri hangileridir?','Hiroşima ve Nagazaki','Tokyo ve Osaka','Kyoto ve Kobe','Nagoya ve Sapporo'),
  m('Dünya tarihi','o','Fransız İhtilali’nin simgesi olan 14 Temmuz 1789’da basılan yapı nedir?','Bastille Hapishanesi','Versay Sarayı','Louvre','Notre-Dame'),
  m('Dünya tarihi','o','Dünyanın çevresini dolaşan ilk seferi başlatan kaşif kimdir?','Macellan','Kristof Kolomb','Vasco da Gama','James Cook'),
  m('Dünya tarihi','o','Venedikli ünlü gezgin Marco Polo hangi ülkeye yaptığı seyahatle tanınır?','Çin','Hindistan','Mısır','Japonya'),
  m('Dünya tarihi','o','Hindistan’ın bağımsızlık mücadelesinin ünlü lideri kimdir?','Mahatma Gandi','Nelson Mandela','Mao Zedong','Ho Şi Min'),
  m('Dünya tarihi','o','İstanbul’un fethiyle birlikte hangi çağın sona erdiği kabul edilir?','Orta Çağ','İlk Çağ','Yeni Çağ','Yakın Çağ'),
  m('Dünya tarihi','o','Amerika’da sivil haklar hareketinin lideri olan ve “Bir hayalim var” konuşmasıyla tanınan kişi kimdir?','Martin Luther King','Malcolm X','Barack Obama','Muhammed Ali'),
  n('Dünya tarihi','o','Amerika Birleşik Devletleri’nin bağımsızlığı hangi yıl ilan edildi?',1776,'yılı',30),
  n('Dünya tarihi','o','Sovyetler Birliği hangi yıl dağıldı?',1991,'yılı',20),
  n('Dünya tarihi','o','Küba Füze Krizi hangi yıl yaşandı?',1962,'yılı',20),
  n('Dünya tarihi','z','İlk Haçlı Seferi hangi yıl başladı?',1096,'yılı',40),
  m('Dünya tarihi','z','Rusya’nın son çarı kimdir?','II. Nikolay','III. Aleksandr','I. Petro','II. Katerina'),
  m('Dünya tarihi','z','Napolyon’un ölümüne kadar sürgünde kaldığı ada hangisidir?','Saint Helena','Elba','Korsika','Malta'),
  m('Dünya tarihi','z','Roma’da kölelerin isyanına önderlik eden ünlü gladyatör kimdir?','Spartaküs','Brutus','Maksimus','Hannibal'),
  m('Dünya tarihi','z','Jül Sezar hangi yöntemle öldürülmüştür?','Senatoda suikast sonucu','Savaşta','Zehirlenerek','Hastalıktan'),
  m('Dünya tarihi','z','Mısır Kraliçesi Kleopatra hangi hanedana mensuptu?','Ptolemaios','Fatımi','Memlük','Eyyubi'),
  m('Dünya tarihi','z','Güney Afrika’da ırk ayrımcılığına karşı mücadele eden ve cumhurbaşkanı seçilen lider kimdir?','Nelson Mandela','Desmond Tutu','Kofi Annan','Patrice Lumumba'),

  /* ================= Coğrafya ================= */
  m('Coğrafya','k','Türkiye’nin en kalabalık şehri hangisidir?','İstanbul','Ankara','İzmir','Bursa'),
  m('Coğrafya','k','Japonya’nın başkenti neresidir?','Tokyo','Kyoto','Osaka','Seul'),
  m('Coğrafya','k','Mısır’ın başkenti neresidir?','Kahire','İskenderiye','Cidde','Tunus'),
  m('Coğrafya','k','Rusya’nın başkenti neresidir?','Moskova','St. Petersburg','Kiev','Minsk'),
  m('Coğrafya','k','Almanya’nın başkenti neresidir?','Berlin','Münih','Hamburg','Frankfurt'),
  m('Coğrafya','k','Dünyanın en soğuk kıtası hangisidir?','Antarktika','Asya','Kuzey Amerika','Avrupa'),
  m('Coğrafya','k','Fuji Dağı hangi ülkededir?','Japonya','Çin','Güney Kore','Nepal'),
  m('Coğrafya','o','Amazon Nehri hangi kıtadadır?','Güney Amerika','Afrika','Asya','Kuzey Amerika'),
  m('Coğrafya','o','Dünyanın en büyük adası hangisidir?','Grönland','Madagaskar','Borneo','Yeni Gine'),
  m('Coğrafya','o','Machu Picchu antik kenti hangi ülkededir?','Peru','Meksika','Şili','Bolivya'),
  m('Coğrafya','o','Petra Antik Kenti hangi ülkededir?','Ürdün','Suriye','Mısır','Lübnan'),
  m('Coğrafya','o','Büyük Set Resifi hangi ülkenin kıyısındadır?','Avustralya','Endonezya','Filipinler','Yeni Zelanda'),
  m('Coğrafya','o','Yüzölçümü bakımından dünyanın en büyük gölü hangisidir?','Hazar Denizi','Superior Gölü','Victoria Gölü','Baykal Gölü'),
  m('Coğrafya','o','ABD’nin başkenti neresidir?','Washington D.C.','New York','Los Angeles','Chicago'),
  m('Coğrafya','o','Türkiye’nin en kuzeydeki ili hangisidir?','Sinop','Samsun','Rize','Kırklareli'),
  m('Coğrafya','o','Tuz Gölü hangi coğrafi bölgemizdedir?','İç Anadolu','Ege','Akdeniz','Marmara'),
  m('Coğrafya','o','Kızılırmak hangi denize dökülür?','Karadeniz','Akdeniz','Ege Denizi','Marmara Denizi'),
  n('Coğrafya','k','Türkiye’de kaç coğrafi bölge vardır?',7,'bölge'),
  n('Coğrafya','o','Dünyada kaç kıta vardır (en yaygın sınıflandırmayla)?',7,'kıta'),
  m('Coğrafya','z','Avrupa’nın en uzun nehri hangisidir?','Volga','Tuna','Ren','Dinyeper'),
  m('Coğrafya','z','Kamboçya’daki ünlü tapınak kenti hangisidir?','Angkor Wat','Borobudur','Bagan','Hampi'),
  m('Coğrafya','z','Afrika’nın en yüksek dağı olan Kilimanjaro hangi ülkededir?','Tanzanya','Kenya','Uganda','Etiyopya'),
  m('Coğrafya','z','Kazakistan’ın başkenti neresidir?','Astana','Almatı','Taşkent','Bişkek'),
  m('Coğrafya','z','Bosna-Hersek’in başkenti neresidir?','Saraybosna','Belgrad','Zagreb','Podgorica'),
  m('Coğrafya','z','Nüfusu en az olan ilimiz hangisidir?','Bayburt','Tunceli','Ardahan','Gümüşhane'),
  m('Coğrafya','z','Türkiye’nin en batıdaki ili hangisidir?','Edirne','Çanakkale','Kırklareli','İzmir'),

  /* ================= Bilim ================= */
  m('Bilim','k','Dünya’nın tek doğal uydusu hangisidir?','Ay','Güneş','Mars','Venüs'),
  m('Bilim','k','Mıknatıs hangi metali çeker?','Demir','Bakır','Altın','Alüminyum'),
  m('Bilim','k','Kemik ve dişlerin yapısında bulunan mineral hangisidir?','Kalsiyum','Sodyum','Potasyum','Demir'),
  m('Bilim','k','Canlıların soluması için gerekli olan gaz hangisidir?','Oksijen','Azot','Helyum','Karbonmonoksit'),
  m('Bilim','k','Hangi organımız düşünmemizi sağlar?','Beyin','Kalp','Mide','Akciğer'),
  m('Bilim','o','Elektrik akımının birimi nedir?','Amper','Volt','Watt','Ohm'),
  m('Bilim','o','Kuvvetin SI birimi nedir?','Newton','Joule','Pascal','Watt'),
  m('Bilim','o','Hücrenin “enerji santrali” olarak bilinen organeli hangisidir?','Mitokondri','Ribozom','Çekirdek','Koful'),
  m('Bilim','o','Güneş merkezli sistemi öne süren bilim insanı kimdir?','Kopernik','Batlamyus','Aristo','Kepler'),
  m('Bilim','o','“Türlerin Kökeni” kitabının yazarı kimdir?','Charles Darwin','Gregor Mendel','Louis Pasteur','Isaac Newton'),
  m('Bilim','o','Bitkiler fotosentez için havadan hangi gazı alır?','Karbondioksit','Oksijen','Azot','Hidrojen'),
  m('Bilim','o','En hafif element hangisidir?','Hidrojen','Helyum','Lityum','Oksijen'),
  m('Bilim','o','Yemek tuzunun kimyasal formülü nedir?','NaCl','KCl','CaCO₃','NaOH'),
  m('Bilim','o','Teleskopla ilk kez Jüpiter’in uydularını gözlemleyen bilim insanı kimdir?','Galileo Galilei','Johannes Kepler','Isaac Newton','Kopernik'),
  n('Bilim','o','Sağlıklı bir yetişkin insanda kaç kromozom bulunur?',46,'kromozom'),
  n('Bilim','o','İnsan kalbinde kaç oda (boşluk) vardır?',4,'oda'),
  n('Bilim','o','Yetişkin bir insanda (akıl dişleri dahil) kaç kalıcı diş bulunur?',32,'diş'),
  m('Bilim','z','Sıcaklığın SI birimi nedir?','Kelvin','Celsius','Fahrenheit','Joule'),
  m('Bilim','z','Frekansın birimi nedir?','Hertz','Watt','Pascal','Tesla'),
  m('Bilim','z','Bitki hücrelerinde fotosentezin gerçekleştiği organel hangisidir?','Kloroplast','Mitokondri','Golgi','Lizozom'),
  m('Bilim','z','Çiçek hastalığına karşı ilk aşıyı geliştiren hekim kimdir?','Edward Jenner','Louis Pasteur','Robert Koch','Alexander Fleming'),
  m('Bilim','z','Hem Fizik hem Kimya dalında Nobel Ödülü alan bilim insanı kimdir?','Marie Curie','Albert Einstein','Niels Bohr','Rosalind Franklin'),
  m('Bilim','z','Marie Curie’nin keşfettiği iki radyoaktif element hangileridir?','Polonyum ve Radyum','Uranyum ve Toryum','Plütonyum ve Neptünyum','Kripton ve Ksenon'),
  m('Bilim','z','Saf suyun pH değeri yaklaşık kaçtır?','7','1','10','14'),
  m('Bilim','z','Kanda oksijeni taşıyan hücreler hangileridir?','Alyuvarlar','Akyuvarlar','Trombositler','Plazma hücreleri'),
  m('Bilim','z','Gökyüzünün mavi görünmesinin nedeni nedir?','Işığın atmosferde saçılması','Okyanusun yansıması','Ozon tabakasının rengi','Güneş’in mavi olması')
];
