import { EN } from './questions-en.js';
import { EN2 } from './questions-en2.js';
import { MORE1 } from './questions-more1.js';
import { MORE2 } from './questions-more2.js';
import { MORE3 } from './questions-more3.js';

// Zuqio soru havuzu.
//  m(kategori, zorluk, soru, doğru, yanlış1, yanlış2, yanlış3)  → çoktan seçmeli (ilk şık doğrudur, oyunda karıştırılır)
//  n(kategori, zorluk, soru, cevap, birim, [yıl toleransı])      → tahmin sorusu (sayı yazılır)
// zorluk: 'k' kolay, 'o' orta, 'z' zor
const m = (cat, d, q, ...o) => ({t: 'mc', cat, d, q, o});
const n = (cat, d, q, a, unit, tolAbs) => tolAbs ? {t: 'num', cat, d, q, a, unit, tolAbs} : {t: 'num', cat, d, q, a, unit};

const BASE = [
  /* ================= Genel kültür ================= */
  m('Genel kültür','k','Hangi renk, sarı ile mavinin karışımından elde edilir?','Yeşil','Turuncu','Mor','Kahverengi'),
  m('Genel kültür','k','Trafik ışıklarında “geç” anlamına gelen renk hangisidir?','Yeşil','Kırmızı','Sarı','Mavi'),
  m('Genel kültür','k','Hangi organımız kanı vücuda pompalar?','Kalp','Karaciğer','Böbrek','Akciğer'),
  m('Genel kültür','k','Hangi hayvan “ormanlar kralı” olarak bilinir?','Aslan','Kaplan','Ayı','Kurt'),
  m('Genel kültür','k','Türkiye’nin para birimi nedir?','Türk lirası','Dolar','Euro','Dinar'),
  m('Genel kültür','o','Japonya’nın para birimi nedir?','Yen','Won','Yuan','Ringgit'),
  m('Genel kültür','o','Romen rakamlarında “X” kaçı gösterir?','10','5','50','100'),
  m('Genel kültür','o','Nobel Barış Ödülü hangi şehirde verilir?','Oslo','Stockholm','Cenevre','Kopenhag'),
  m('Genel kültür','o','Hangi şehir “Büyük Elma” takma adıyla bilinir?','New York','Los Angeles','Chicago','Boston'),
  m('Genel kültür','o','Hindistan’ın para birimi nedir?','Rupi','Dolar','Taka','Dinar'),
  m('Genel kültür','o','Hangi ülke “Doğan Güneşin Ülkesi” olarak bilinir?','Japonya','Çin','Güney Kore','Tayland'),
  m('Genel kültür','o','Hangi ülkenin bayrağı dikdörtgen değildir?','Nepal','Polonya','Brezilya','Meksika'),
  m('Genel kültür','o','Birleşmiş Milletler’in genel merkezi hangi şehirdedir?','New York','Cenevre','Brüksel','Paris'),
  m('Genel kültür','o','Birleşmiş Milletler Güvenlik Konseyi’nin daimi üyelerinden biri olmayan ülke hangisidir?','Almanya','Fransa','Çin','Rusya'),
  m('Genel kültür','z','Yapay dil Esperanto’yu kim geliştirmiştir?','L. L. Zamenhof','Alfred Nobel','Jules Verne','Ferdinand de Saussure'),
  m('Genel kültür','z','Satrançta şahın tehdit altında olmadığı ama oyuncunun hamle yapamadığı duruma ne denir?','Pat','Mat','Rok','Şah'),
  m('Genel kültür','z','Kızılhaç hareketinin kurucusu kimdir?','Henry Dunant','Florence Nightingale','Louis Pasteur','Alfred Nobel'),
  n('Genel kültür','k','Gökkuşağında kaç renk vardır?',7,'renk'),
  n('Genel kültür','k','Bir düzinede kaç adet vardır?',12,'adet'),
  n('Genel kültür','k','Jokersiz bir deste iskambil kâğıdında kaç kâğıt vardır?',52,'kâğıt'),
  n('Genel kültür','o','Bir tavla takımında kaç pul vardır?',15,'pul'),
  n('Genel kültür','o','Bir Rubik küpünün tek bir yüzünde kaç küçük kare bulunur?',9,'kare'),
  n('Genel kültür','o','Standart bir piyanoda kaç tuş vardır?',88,'tuş'),
  n('Genel kültür','z','Birleşmiş Milletler’in kaç üye ülkesi vardır?',193,'ülke'),

  /* ================= Türkiye tarihi ================= */
  m('Türkiye tarihi','k','Türkiye Cumhuriyeti’nin ilk cumhurbaşkanı kimdir?','Mustafa Kemal Atatürk','İsmet İnönü','Celal Bayar','Fevzi Çakmak'),
  m('Türkiye tarihi','k','İstanbul’u fetheden Osmanlı padişahı kimdir?','II. Mehmed (Fatih)','I. Murad','Yıldırım Bayezid','Kanuni Sultan Süleyman'),
  m('Türkiye tarihi','k','Osmanlı Devleti’nin kurucusu kimdir?','Osman Bey','Orhan Bey','Ertuğrul Gazi','I. Murad'),
  m('Türkiye tarihi','k','30 Ağustos hangi zaferin yıl dönümüdür?','Başkomutanlık Meydan Muharebesi','Sakarya Meydan Muharebesi','Çanakkale Zaferi','Malazgirt Zaferi'),
  m('Türkiye tarihi','k','TBMM hangi tarihte açıldı?','23 Nisan 1920','29 Ekim 1923','19 Mayıs 1919','30 Ağustos 1922'),
  m('Türkiye tarihi','k','Atatürk’ün Samsun’a çıktığı tarih olan 19 Mayıs 1919, hangi sürecin başlangıcı sayılır?','Millî Mücadele','Tanzimat','Meşrutiyet','Lale Devri'),
  m('Türkiye tarihi','o','Lozan Antlaşması hangi yıl imzalandı?','1923','1920','1921','1925'),
  m('Türkiye tarihi','o','Harf Devrimi (yeni Türk harflerinin kabulü) hangi yıl gerçekleşti?','1928','1923','1925','1934'),
  m('Türkiye tarihi','o','Türk kadınına milletvekili seçme ve seçilme hakkı hangi yıl verildi?','1934','1923','1930','1945'),
  m('Türkiye tarihi','o','Soyadı Kanunu hangi yıl çıkarıldı?','1934','1925','1928','1938'),
  m('Türkiye tarihi','o','Lale Devri hangi padişah döneminde yaşanmıştır?','III. Ahmed','II. Mahmud','IV. Murad','I. Abdülhamid'),
  m('Türkiye tarihi','o','Mohaç Meydan Muharebesi hangi padişah döneminde yapıldı?','Kanuni Sultan Süleyman','Yavuz Sultan Selim','II. Bayezid','Fatih Sultan Mehmed'),
  m('Türkiye tarihi','o','Ankara Savaşı’nda (1402) Yıldırım Bayezid kime yenildi?','Timur','Cengiz Han','Haçlılar','Memlükler'),
  m('Türkiye tarihi','o','Sakarya Meydan Muharebesi sırasında başkomutanlık görevini kim yürütüyordu?','Mustafa Kemal Paşa','İsmet Paşa','Fevzi Çakmak','Kâzım Karabekir'),
  m('Türkiye tarihi','o','Preveze Deniz Savaşı’nda Osmanlı donanmasını kim komuta etti?','Barbaros Hayreddin Paşa','Piri Reis','Turgut Reis','Kemal Reis'),
  m('Türkiye tarihi','z','Osmanlı’da ilk anayasa olan Kanun-i Esasi hangi yıl ilan edildi?','1876','1839','1856','1908'),
  m('Türkiye tarihi','z','Tanzimat Fermanı hangi yıl ilan edildi?','1839','1856','1876','1908'),
  m('Türkiye tarihi','z','Türkiye hangi yıl NATO’ya üye oldu?','1952','1945','1949','1960'),
  m('Türkiye tarihi','z','Sivas Kongresi hangi yıl toplandı?','1919','1920','1921','1922'),
  m('Türkiye tarihi','z','Misak-ı Millî hangi mecliste kabul edildi?','Son Osmanlı Mebusan Meclisi','TBMM','Erzurum Kongresi','Sivas Kongresi'),
  m('Türkiye tarihi','z','1950 seçimlerinden sonra hangi isim başbakan oldu?','Adnan Menderes','İsmet İnönü','Celal Bayar','Süleyman Demirel'),
  n('Türkiye tarihi','k','Türkiye Cumhuriyeti hangi yıl ilan edildi?',1923,'yılı',40),
  n('Türkiye tarihi','o','Fatih Sultan Mehmed İstanbul’u hangi yıl fethetti?',1453,'yılı',100),
  n('Türkiye tarihi','o','Atatürk hangi yıl vefat etti?',1938,'yılı',40),
  n('Türkiye tarihi','o','Çanakkale Deniz Zaferi hangi yıl kazanıldı?',1915,'yılı',40),
  n('Türkiye tarihi','z','Malazgirt Meydan Muharebesi hangi yıl yapıldı?',1071,'yılı',100),
  n('Türkiye tarihi','z','Osmanlı Devleti yaklaşık hangi yıl kuruldu?',1299,'yılı',200),

  /* ================= Dünya tarihi ================= */
  m('Dünya tarihi','k','İkinci Dünya Savaşı hangi yıl başladı?','1939','1914','1941','1945'),
  m('Dünya tarihi','k','Atlas Okyanusu’nu aşıp Amerika kıtasına ulaşan ünlü Avrupalı denizci kimdir?','Kristof Kolomb','Vasco da Gama','Macellan','Marco Polo'),
  m('Dünya tarihi','k','Ay’a ayak basan ilk insan kimdir?','Neil Armstrong','Buzz Aldrin','Yuri Gagarin','Michael Collins'),
  m('Dünya tarihi','k','Gize’deki piramitlerin en büyüğü hangisidir?','Keops Piramidi','Kefren Piramidi','Mikerinos Piramidi','Djoser Piramidi'),
  m('Dünya tarihi','k','Troya Savaşı’nı anlatan destan hangisidir?','İlyada','Odysseia','Aeneis','Gılgamış'),
  m('Dünya tarihi','o','Berlin Duvarı hangi yıl yıkıldı?','1989','1961','1991','1975'),
  m('Dünya tarihi','o','Birinci Dünya Savaşı’nı tetikleyen olay hangisidir?','Saraybosna suikastı','Versay Antlaşması','Rus Devrimi','Lusitania’nın batırılması'),
  m('Dünya tarihi','o','Magna Carta hangi ülkede imzalandı?','İngiltere','Fransa','İspanya','Almanya'),
  m('Dünya tarihi','o','Rönesans hareketi ilk olarak hangi ülkede başlamıştır?','İtalya','Fransa','İngiltere','Almanya'),
  m('Dünya tarihi','o','Sanayi Devrimi ilk olarak hangi ülkede başladı?','İngiltere','Almanya','ABD','Fransa'),
  m('Dünya tarihi','o','Napolyon 1815’te hangi savaşta kesin yenilgiye uğradı?','Waterloo','Austerlitz','Borodino','Leipzig'),
  m('Dünya tarihi','o','Soğuk Savaş hangi iki güç arasında yaşandı?','ABD ve SSCB','İngiltere ve Fransa','Çin ve Japonya','Almanya ve İtalya'),
  m('Dünya tarihi','o','Modern Olimpiyat Oyunları ilk kez (1896) hangi şehirde yapıldı?','Atina','Paris','Londra','Roma'),
  m('Dünya tarihi','o','Hammurabi Kanunları hangi uygarlığa aittir?','Babil','Sümer','Asur','Hitit'),
  m('Dünya tarihi','z','Büyük İskender hangi kralın oğludur?','II. Philippos','Leonidas','Perikles','Dareios'),
  m('Dünya tarihi','z','Konstantinopolis şehrini kuran Roma imparatoru kimdir?','I. Konstantin','Jüstinyen','Augustus','Theodosius'),
  m('Dünya tarihi','z','1337–1453 arasında İngiltere ile Fransa arasında yaşanan savaşlara ne ad verilir?','Yüz Yıl Savaşları','Otuz Yıl Savaşları','Gül Savaşları','Kırım Savaşı'),
  m('Dünya tarihi','z','1917 Bolşevik Devrimi’ni yöneten lider kimdir?','Lenin','Stalin','Troçki','II. Nikolay'),
  m('Dünya tarihi','z','Birinci Dünya Savaşı’nı Almanya açısından sona erdiren antlaşma hangisidir?','Versay','Sevr','Trianon','Neuilly'),
  m('Dünya tarihi','z','Çin’de farklı krallıkları birleştirip ilk imparator olan ve Çin Seddi’nin birleştirilmesini başlatan hükümdar kimdir?','Qin Shi Huang','Kubilay Han','Hongwu','Kangxi'),
  n('Dünya tarihi','o','Fransız İhtilali hangi yıl başladı?',1789,'yılı',40),
  n('Dünya tarihi','o','İnsan ilk kez hangi yıl Ay’a ayak bastı?',1969,'yılı',40),
  n('Dünya tarihi','o','İkinci Dünya Savaşı hangi yıl sona erdi?',1945,'yılı',40),
  n('Dünya tarihi','o','Titanik hangi yıl battı?',1912,'yılı',40),
  n('Dünya tarihi','o','Eyfel Kulesi hangi yıl tamamlandı?',1889,'yılı',40),
  n('Dünya tarihi','z','Kristof Kolomb ilk seferinde hangi yıl Amerika’ya ulaştı?',1492,'yılı',100),
  n('Dünya tarihi','z','Magna Carta hangi yıl imzalandı?',1215,'yılı',150),

  /* ================= Coğrafya ================= */
  m('Coğrafya','k','Türkiye’nin başkenti neresidir?','Ankara','İstanbul','İzmir','Bursa'),
  m('Coğrafya','k','Türkiye’nin en yüksek dağı hangisidir?','Ağrı Dağı','Erciyes Dağı','Uludağ','Süphan Dağı'),
  m('Coğrafya','k','Eyfel Kulesi hangi şehirdedir?','Paris','Londra','Roma','Berlin'),
  m('Coğrafya','k','Pisa Kulesi hangi ülkededir?','İtalya','İspanya','Fransa','Portekiz'),
  m('Coğrafya','k','Dünyanın en büyük okyanusu hangisidir?','Büyük Okyanus','Atlas Okyanusu','Hint Okyanusu','Arktik Okyanusu'),
  m('Coğrafya','k','Pamukkale hangi ilimizdedir?','Denizli','Aydın','Muğla','Burdur'),
  m('Coğrafya','k','Anıtkabir hangi şehirdedir?','Ankara','İstanbul','Samsun','Eskişehir'),
  m('Coğrafya','o','Tamamı Türkiye sınırları içinde kalan en uzun nehir hangisidir?','Kızılırmak','Fırat','Sakarya','Yeşilırmak'),
  m('Coğrafya','o','Türkiye’nin yüzölçümü en büyük gölü hangisidir?','Van Gölü','Tuz Gölü','Beyşehir Gölü','Eğirdir Gölü'),
  m('Coğrafya','o','Avustralya’nın başkenti neresidir?','Kanberra','Sidney','Melbourne','Perth'),
  m('Coğrafya','o','Kanada’nın başkenti neresidir?','Ottawa','Toronto','Montreal','Vancouver'),
  m('Coğrafya','o','Yüzölçümü en büyük ülke hangisidir?','Rusya','Kanada','Çin','ABD'),
  m('Coğrafya','o','Nil Nehri hangi denize dökülür?','Akdeniz','Kızıldeniz','Ölü Deniz','Karadeniz'),
  m('Coğrafya','o','Kapadokya bölgesinin merkezi sayılan Göreme hangi ilimizdedir?','Nevşehir','Konya','Kayseri','Aksaray'),
  m('Coğrafya','o','Nemrut Dağı’ndaki dev heykellerin bulunduğu il hangisidir?','Adıyaman','Malatya','Kahramanmaraş','Elazığ'),
  m('Coğrafya','o','Efes Antik Kenti hangi ilimizdedir?','İzmir','Aydın','Manisa','Muğla'),
  m('Coğrafya','o','Sümela Manastırı hangi ilimizdedir?','Trabzon','Rize','Giresun','Artvin'),
  m('Coğrafya','o','Hangi şehir hem Avrupa’da hem Asya’da yer alır?','İstanbul','Moskova','Roma','Viyana'),
  m('Coğrafya','o','Dünyanın en büyük sıcak çölü hangisidir?','Sahra Çölü','Gobi Çölü','Kalahari Çölü','Atacama Çölü'),
  m('Coğrafya','z','Brezilya’nın başkenti neresidir?','Brasília','Rio de Janeiro','São Paulo','Salvador'),
  m('Coğrafya','z','Dünyanın en derin gölü hangisidir?','Baykal Gölü','Hazar Denizi','Tanganika Gölü','Superior Gölü'),
  m('Coğrafya','z','Türkiye’nin en büyük adası hangisidir?','Gökçeada','Bozcaada','Marmara Adası','Avşa Adası'),
  m('Coğrafya','z','Cebelitarık Boğazı hangi iki su kütlesini birbirine bağlar?','Akdeniz ile Atlas Okyanusu','Karadeniz ile Akdeniz','Kızıldeniz ile Akdeniz','Baltık Denizi ile Kuzey Denizi'),
  m('Coğrafya','z','Zambezi Nehri üzerinde bulunan ünlü şelale hangisidir?','Victoria Şelalesi','Niagara Şelalesi','Iguazu Şelalesi','Angel Şelalesi'),
  m('Coğrafya','z','Dünyanın en yüksek şelalesi olan Angel Şelalesi hangi ülkededir?','Venezuela','Brezilya','Peru','Arjantin'),
  m('Coğrafya','z','Kolombiya’nın başkenti neresidir?','Bogota','Lima','Quito','Caracas'),
  n('Coğrafya','k','Türkiye kaç ilden oluşur?',81,'il'),
  n('Coğrafya','o','Türkiye’nin kaç komşu ülkesi vardır?',8,'ülke'),
  n('Coğrafya','o','Ağrı Dağı’nın yüksekliği yaklaşık kaç metredir?',5137,'metre'),
  n('Coğrafya','o','Everest Dağı’nın yüksekliği yaklaşık kaç metredir?',8849,'metre'),
  n('Coğrafya','o','Dünya’nın ekvator çevresi yaklaşık kaç kilometredir?',40075,'km'),
  n('Coğrafya','z','Afrika kıtasında kaç bağımsız ülke vardır?',54,'ülke'),
  n('Coğrafya','z','Dünyanın en derin noktası olan Mariana Çukuru yaklaşık kaç metre derinliktedir?',10935,'metre'),

  /* ================= Bilim ================= */
  m('Bilim','k','Güneş Sistemi’nin en büyük gezegeni hangisidir?','Jüpiter','Satürn','Neptün','Uranüs'),
  m('Bilim','k','Suyun kimyasal formülü nedir?','H₂O','CO₂','H₂O₂','O₂'),
  m('Bilim','k','“Kızıl gezegen” olarak bilinen gezegen hangisidir?','Mars','Venüs','Merkür','Jüpiter'),
  m('Bilim','k','İnsan vücudunun en büyük organı hangisidir?','Deri','Karaciğer','Akciğer','Beyin'),
  m('Bilim','k','Güneş’e en yakın gezegen hangisidir?','Merkür','Venüs','Mars','Dünya'),
  m('Bilim','k','Halkalarıyla ünlü gezegen hangisidir?','Satürn','Mars','Venüs','Merkür'),
  m('Bilim','k','Bitkiler fotosentez sırasında havaya hangi gazı verir?','Oksijen','Karbondioksit','Azot','Hidrojen'),
  m('Bilim','o','Altının kimyasal sembolü nedir?','Au','Ag','Al','Fe'),
  m('Bilim','o','Evrensel çekim yasasını ortaya koyan bilim insanı kimdir?','Isaac Newton','Albert Einstein','Galileo Galilei','Nikola Tesla'),
  m('Bilim','o','Elmas hangi elementten oluşur?','Karbon','Silisyum','Kalsiyum','Azot'),
  m('Bilim','o','DNA’nın açılımı nedir?','Deoksiribonükleik asit','Dinükleik asit','Dioksit nükleik asit','Deoksi nitrojen asit'),
  m('Bilim','o','Periyodik tabloda “O” sembolü hangi elementi gösterir?','Oksijen','Osmiyum','Azot','Hidrojen'),
  m('Bilim','o','Güneş’ten gelen ışıkla ciltte sentezlenen vitamin hangisidir?','D vitamini','C vitamini','A vitamini','K vitamini'),
  m('Bilim','o','Kanda oksijen taşıyan protein hangisidir?','Hemoglobin','İnsülin','Kolajen','Keratin'),
  m('Bilim','o','Atmosferin en büyük bölümünü hangi gaz oluşturur?','Azot','Oksijen','Karbondioksit','Argon'),
  m('Bilim','o','Atomun çekirdeğinde hangi parçacıklar bulunur?','Proton ve nötron','Elektron ve proton','Elektron ve nötron','Sadece elektron'),
  m('Bilim','o','Görelilik kuramını kim geliştirmiştir?','Albert Einstein','Isaac Newton','Niels Bohr','Max Planck'),
  m('Bilim','o','Newton’un birinci yasası hangi kavramla ilgilidir?','Eylemsizlik','Yerçekimi','Sürtünme','Enerji korunumu'),
  m('Bilim','z','Penisilini keşfeden bilim insanı kimdir?','Alexander Fleming','Louis Pasteur','Robert Koch','Edward Jenner'),
  m('Bilim','z','Gregor Mendel kalıtım deneylerini hangi bitki üzerinde yapmıştır?','Bezelye','Buğday','Mısır','Gül'),
  m('Bilim','z','Güneş’in enerjisini hangi süreç üretir?','Çekirdek füzyonu','Çekirdek fisyonu','Yanma','Kimyasal oksidasyon'),
  m('Bilim','z','“Işık yılı” neyin birimidir?','Uzaklık','Zaman','Hız','Kütle'),
  m('Bilim','z','Hangi gezegende bir gün (kendi etrafında dönüş), bir yıldan (Güneş çevresinde dönüş) daha uzundur?','Venüs','Mars','Jüpiter','Merkür'),
  m('Bilim','z','Kütle çekim dalgalarını ilk kez doğrudan gözlemleyen gözlemevi hangisidir?','LIGO','Hubble','Kepler','CERN'),
  m('Bilim','z','Dünya’nın manyetik alanı canlıları en çok hangisinden korur?','Güneş rüzgârı','Meteorlardan','Depremlerden','Deniz akıntılarından'),
  n('Bilim','k','Güneş Sistemi’nde kaç gezegen vardır?',8,'gezegen'),
  n('Bilim','k','Su deniz seviyesinde kaç santigrat derecede kaynar?',100,'°C'),
  n('Bilim','o','Yetişkin bir insanın iskeletinde kaç kemik vardır?',206,'kemik'),
  n('Bilim','o','Ay ile Dünya arasındaki ortalama uzaklık kaç kilometredir?',384400,'km'),
  n('Bilim','o','Yetişkin bir insanın vücudunda yaklaşık kaç litre kan vardır?',5,'litre'),
  n('Bilim','z','Işık boşlukta saniyede yaklaşık kaç kilometre yol alır?',299792,'km'),
  n('Bilim','z','Dünya ile Güneş arasındaki ortalama uzaklık yaklaşık kaç milyon kilometredir?',150,'milyon km'),
  n('Bilim','z','Periyodik tabloda şu ana kadar kaç element bulunur?',118,'element'),
  n('Bilim','z','Ses havada saniyede yaklaşık kaç metre yol alır?',343,'metre'),
  n('Bilim','z','Dünya’nın yaşı yaklaşık kaç milyon yıldır?',4540,'milyon yıl'),

  /* ================= Spor ================= */
  m('Spor','k','Wimbledon hangi spor dalının turnuvasıdır?','Tenis','Golf','Kriket','Atıcılık'),
  m('Spor','k','Voleybolda bir takım sahada kaç oyuncuyla oynar?','6','5','7','11'),
  m('Spor','k','Basketbolda başarılı bir serbest atış kaç sayı değerindedir?','1','2','3','4'),
  m('Spor','k','Naim Süleymanoğlu hangi spor dalında şampiyon olmuştur?','Halter','Güreş','Boks','Atletizm'),
  m('Spor','o','Antik çağda Olimpiyat Oyunları hangi ülkede başlamıştır?','Yunanistan','İtalya','Mısır','Türkiye'),
  m('Spor','o','Hangi ülke sumo güreşiyle özdeşleşmiştir?','Japonya','Çin','Güney Kore','Moğolistan'),
  m('Spor','o','Satrançta yalnızca çapraz hareket edebilen taş hangisidir?','Fil','Kale','At','Piyon'),
  m('Spor','o','“Ace” terimi hangi sporda kullanılır?','Tenis','Boks','Eskrim','Güreş'),
  m('Spor','o','Tour de France hangi spor dalının yarışıdır?','Bisiklet','Koşu','Yelken','Motosiklet'),
  m('Spor','o','Golfte bir deliği par’ın bir vuruş altında tamamlamaya ne denir?','Birdie','Bogey','Eagle','Ace'),
  m('Spor','o','Olimpiyat meşalesi geleneksel olarak nerede yakılır?','Olimpiya (Yunanistan)','Atina','Paris','Roma'),
  m('Spor','z','Modern Olimpiyat Oyunları’nın kurucusu kimdir?','Pierre de Coubertin','Avery Brundage','Juan Antonio Samaranch','Thomas Bach'),
  m('Spor','z','Judo hangi ülkede ortaya çıkmıştır?','Japonya','Çin','Güney Kore','Tayland'),
  m('Spor','z','Basketbolu kim icat etmiştir?','James Naismith','Michael Jordan','Pierre de Coubertin','William Morgan'),
  m('Spor','z','Voleybolu kim icat etmiştir?','William G. Morgan','James Naismith','Walter Camp','Abner Doubleday'),
  n('Spor','k','Bir basketbol takımı sahada kaç oyuncuyla oynar?',5,'oyuncu'),
  n('Spor','k','Olimpiyat bayrağında kaç halka vardır?',5,'halka'),
  n('Spor','k','Satranç tahtasında toplam kaç kare vardır?',64,'kare'),
  n('Spor','o','Bir maraton yaklaşık kaç kilometredir?',42,'km'),
  n('Spor','o','Yaz Olimpiyatları kaç yılda bir yapılır?',4,'yıl'),
  n('Spor','o','Bir bowling oyununda kaç labut vardır?',10,'labut'),
  n('Spor','o','Voleybolda ilk dört set kaç sayıda biter (en az)?',25,'sayı'),
  n('Spor','z','Hentbolda bir takım sahada kaleci dahil kaç oyuncuyla oynar?',7,'oyuncu'),
  n('Spor','z','Buz hokeyinde bir takım sahada kaleci dahil kaç oyuncuyla oynar?',6,'oyuncu'),
  n('Spor','z','Ragbi (rugby union) takımında sahada kaç oyuncu bulunur?',15,'oyuncu'),

  /* ================= Futbol ================= */
  m('Futbol','k','Türkiye Millî Takımı 2002 Dünya Kupası’nda kaçıncı oldu?','Üçüncü','İkinci','Dördüncü','Çeyrek finalist'),
  m('Futbol','k','Maracanã stadyumu hangi ülkededir?','Brezilya','Arjantin','Şili','Meksika'),
  m('Futbol','k','Premier Lig hangi ülkenin futbol ligidir?','İngiltere','İspanya','İtalya','Almanya'),
  m('Futbol','k','Futbolda “El Pibe de Oro” lakaplı efsane oyuncu kimdir?','Diego Maradona','Lionel Messi','Pelé','Johan Cruyff'),
  m('Futbol','o','Galatasaray UEFA Kupası’nı hangi yıl kazandı?','2000','1996','2002','1999'),
  m('Futbol','o','Türkiye EURO 2008’de hangi turda elendi?','Yarı final','Çeyrek final','Grup aşaması','Son 16'),
  m('Futbol','o','Hangi ülke Dünya Kupası’nı en çok kazanan ülkedir?','Brezilya','Almanya','Arjantin','İtalya'),
  m('Futbol','o','İlk Dünya Kupası’nı (1930) hangi ülke kazandı?','Uruguay','Brezilya','Arjantin','İtalya'),
  m('Futbol','o','Real Madrid’in ev sahibi olduğu stadyum hangisidir?','Santiago Bernabéu','Camp Nou','Old Trafford','San Siro'),
  m('Futbol','o','1998 Dünya Kupası’nı hangi ülke kazandı?','Fransa','Brezilya','Hırvatistan','İtalya'),
  m('Futbol','o','En çok Altın Top ödülünü kazanan futbolcu kimdir?','Lionel Messi','Cristiano Ronaldo','Michel Platini','Johan Cruyff'),
  m('Futbol','z','Dünya Kupası tarihinin en hızlı golünü kim attı (2002)?','Hakan Şükür','Rüştü Reçber','Emre Belözoğlu','Tuncay Şanlı'),
  m('Futbol','z','İlk Avrupa Futbol Şampiyonası’nı (1960) hangi ülke kazandı?','SSCB','İspanya','Almanya','Fransa'),
  m('Futbol','z','1966 Dünya Kupası’nı hangi ülke kazandı?','İngiltere','Almanya','Brezilya','İtalya'),
  m('Futbol','z','EURO 2004’ü sürpriz biçimde hangi ülke kazandı?','Yunanistan','Portekiz','Çek Cumhuriyeti','Hollanda'),
  n('Futbol','k','Futbolda bir takım sahaya kaç oyuncuyla çıkar?',11,'oyuncu'),
  n('Futbol','k','Bir futbol maçının normal süresi kaç dakikadır?',90,'dakika'),
  n('Futbol','o','Pelé toplam kaç Dünya Kupası kazanmıştır?',3,'kupa'),
  n('Futbol','o','İlk Dünya Kupası hangi yıl yapıldı?',1930,'yılı',40),
  n('Futbol','z','Türkiye Millî Takımı Dünya Kupası’nda üçüncülüğü hangi yıl kazandı?',2002,'yılı',20),

  /* ================= Sinema ve dizi ================= */
  m('Sinema ve dizi','k','Titanik filminin yönetmeni kimdir?','James Cameron','Steven Spielberg','Christopher Nolan','Ridley Scott'),
  m('Sinema ve dizi','k','Harry Potter’ın okuduğu büyücülük okulunun adı nedir?','Hogwarts','Beauxbatons','Durmstrang','Ilvermorny'),
  m('Sinema ve dizi','k','Darth Vader karakteri hangi film serisinde yer alır?','Yıldız Savaşları','Matrix','Yüzüklerin Efendisi','Star Trek'),
  m('Sinema ve dizi','k','“Aslan Kral” filminin baş karakteri olan genç aslanın adı nedir?','Simba','Mufasa','Scar','Nala'),
  m('Sinema ve dizi','k','Buzz Lightyear hangi animasyon filminin karakteridir?','Oyuncak Hikâyesi','Arabalar','Shrek','Ice Age'),
  m('Sinema ve dizi','k','“Recep İvedik” serisinin başrol oyuncusu kimdir?','Şahan Gökbakar','Cem Yılmaz','Ata Demirer','Yılmaz Erdoğan'),
  m('Sinema ve dizi','o','Türk sinemasının altın çağı anlamına gelen “Yeşilçam” neyi ifade eder?','Türk sinemasını','Türk tiyatrosunu','Türk müziğini','Türk edebiyatını'),
  m('Sinema ve dizi','o','“Muhteşem Yüzyıl” dizisi hangi padişahı anlatır?','Kanuni Sultan Süleyman','Fatih Sultan Mehmed','II. Abdülhamid','Yavuz Sultan Selim'),
  m('Sinema ve dizi','o','“Behzat Ç.” dizisinin başrol oyuncusu kimdir?','Erdal Beşikçioğlu','Kıvanç Tatlıtuğ','Haluk Bilginer','Tarık Akan'),
  m('Sinema ve dizi','o','“Kurtlar Vadisi”nde Polat Alemdar karakterini kim canlandırmıştır?','Necati Şaşmaz','Bülent İnal','Erkan Petekkaya','Kenan İmirzalıoğlu'),
  m('Sinema ve dizi','o','“G.O.R.A.” filminde Cem Yılmaz’ın canlandırdığı karakter hangisidir?','Arif','Recep','Behzat','Kemal'),
  m('Sinema ve dizi','o','“Inception” filminin yönetmeni kimdir?','Christopher Nolan','Steven Spielberg','Denis Villeneuve','David Fincher'),
  m('Sinema ve dizi','o','“Jurassic Park” filminin yönetmeni kimdir?','Steven Spielberg','James Cameron','George Lucas','Ridley Scott'),
  m('Sinema ve dizi','o','“Game of Thrones” dizisi hangi kitap serisine dayanır?','Buz ve Ateşin Şarkısı','Yüzüklerin Efendisi','Narnia Günlükleri','Karanlık Madde'),
  m('Sinema ve dizi','z','“Kış Uykusu” filmiyle Cannes Altın Palmiye’yi kazanan Türk yönetmen kimdir?','Nuri Bilge Ceylan','Fatih Akın','Zeki Demirkubuz','Ferzan Özpetek'),
  m('Sinema ve dizi','z','“Parazit” filminin yönetmeni kimdir?','Bong Joon-ho','Park Chan-wook','Hirokazu Kore-eda','Ang Lee'),
  m('Sinema ve dizi','z','“Citizen Kane” filminin yönetmeni kimdir?','Orson Welles','Alfred Hitchcock','Stanley Kubrick','Billy Wilder'),
  m('Sinema ve dizi','z','“2001: Bir Uzay Destanı” filminin yönetmeni kimdir?','Stanley Kubrick','George Lucas','Ridley Scott','Steven Spielberg'),
  m('Sinema ve dizi','z','“Baba” (The Godfather) filminin yönetmeni kimdir?','Francis Ford Coppola','Martin Scorsese','Brian De Palma','Sergio Leone'),
  m('Sinema ve dizi','z','“Vizontele” filmini kimler yönetmiştir?','Yılmaz Erdoğan ve Ömer Faruk Sorak','Cem Yılmaz ve Ali Atay','Ata Demirer ve Okan Bayülgen','Sinan Çetin ve Atıf Yılmaz'),
  m('Sinema ve dizi','z','İlk uzun metrajlı sesli film olarak kabul edilen yapım hangisidir?','The Jazz Singer','Metropolis','Citizen Kane','Modern Times'),
  n('Sinema ve dizi','k','Harry Potter kitap serisi kaç kitaptan oluşur?',7,'kitap'),
  n('Sinema ve dizi','o','Titanik filmi hangi yıl vizyona girdi?',1997,'yılı',15),
  n('Sinema ve dizi','o','Friends dizisi kaç sezon sürmüştür?',10,'sezon'),
  n('Sinema ve dizi','o','Game of Thrones dizisi kaç sezon sürmüştür?',8,'sezon'),
  n('Sinema ve dizi','z','İlk Yıldız Savaşları filmi hangi yıl vizyona girdi?',1977,'yılı',15),
  n('Sinema ve dizi','z','Lumière kardeşler ilk halka açık film gösterimini hangi yıl yaptı?',1895,'yılı',40),

  /* ================= Müzik ================= */
  m('Müzik','k','Aşağıdaki çalgılardan hangisi telli değildir?','Ney','Bağlama','Ud','Keman'),
  m('Müzik','k','Davul hangi çalgı grubuna girer?','Vurmalı','Telli','Üflemeli','Tuşlu'),
  m('Müzik','k','Ney hangi çalgı grubuna girer?','Üflemeli','Telli','Vurmalı','Yaylı'),
  m('Müzik','k','“Bohemian Rhapsody” şarkısıyla tanınan grup hangisidir?','Queen','The Beatles','Pink Floyd','Led Zeppelin'),
  m('Müzik','o','“Dört Mevsim” adlı eserin bestecisi kimdir?','Antonio Vivaldi','Johann Sebastian Bach','Wolfgang Amadeus Mozart','Frédéric Chopin'),
  m('Müzik','o','“Ay Işığı Sonatı” kime aittir?','Beethoven','Mozart','Chopin','Liszt'),
  m('Müzik','o','“Kuğu Gölü” balesinin bestecisi kimdir?','Çaykovski','Prokofyev','Stravinski','Rahmaninov'),
  m('Müzik','o','The Beatles hangi şehirde kurulmuştur?','Liverpool','Londra','Manchester','Birmingham'),
  m('Müzik','o','Zeki Müren’in lakabı nedir?','Sanat Güneşi','Sultan','Kral','Efsane'),
  m('Müzik','o','Neşet Ertaş hangi çalgıyla özdeşleşmiştir?','Bağlama','Ud','Kanun','Keman'),
  m('Müzik','o','Hangi sanatçı “7’den 77’ye” programıyla tanınır?','Barış Manço','Zeki Müren','Cem Karaca','Tarkan'),
  m('Müzik','o','“Rock’n’Roll’un Kralı” olarak bilinen sanatçı kimdir?','Elvis Presley','Frank Sinatra','Johnny Cash','Bob Dylan'),
  m('Müzik','z','Aşağıdakilerden hangisi “Türk Beşleri”nden biridir?','Ahmed Adnan Saygun','Zeki Müren','Neşet Ertaş','Münir Nurettin Selçuk'),
  m('Müzik','z','“Boléro” eserinin bestecisi kimdir?','Maurice Ravel','Claude Debussy','Erik Satie','Georges Bizet'),
  m('Müzik','z','Mozart hangi ülkede doğmuştur?','Avusturya','Almanya','İtalya','Fransa'),
  m('Müzik','z','Beethoven’ın 9. Senfonisi’nin son bölümünde söylenen ünlü ezgi hangisidir?','Neşeye Övgü','Ay Işığı','Für Elise','Kaderin Sesi'),
  m('Müzik','z','Müzikte “forte” ne anlama gelir?','Güçlü, yüksek sesle','Yavaş','Hızlı','Yumuşak'),
  n('Müzik','k','Do-re-mi dizisinde kaç ses vardır?',7,'ses'),
  n('Müzik','k','The Beatles kaç kişiden oluşuyordu?',4,'kişi'),
  n('Müzik','o','Klasik bir gitarda kaç tel vardır?',6,'tel'),
  n('Müzik','o','Bir kemanın kaç teli vardır?',4,'tel'),
  n('Müzik','z','Beethoven toplam kaç senfoni tamamlamıştır?',9,'senfoni'),
  n('Müzik','z','Mozart kaç yıl yaşamıştır?',35,'yıl'),

  /* ================= Edebiyat ================= */
  m('Edebiyat','k','İstiklal Marşı’nın şairi kimdir?','Mehmet Akif Ersoy','Namık Kemal','Ziya Gökalp','Tevfik Fikret'),
  m('Edebiyat','k','“Romeo ve Juliet” kimin eseridir?','William Shakespeare','Charles Dickens','Goethe','Victor Hugo'),
  m('Edebiyat','k','“Küçük Prens” kitabının yazarı kimdir?','Antoine de Saint-Exupéry','Jules Verne','Victor Hugo','Albert Camus'),
  m('Edebiyat','o','“Kürk Mantolu Madonna” romanının yazarı kimdir?','Sabahattin Ali','Orhan Pamuk','Yaşar Kemal','Oğuz Atay'),
  m('Edebiyat','o','“İnce Memed” romanının yazarı kimdir?','Yaşar Kemal','Orhan Kemal','Kemal Tahir','Fakir Baykurt'),
  m('Edebiyat','o','“Tutunamayanlar” romanının yazarı kimdir?','Oğuz Atay','Yusuf Atılgan','Sait Faik Abasıyanık','Ahmet Hamdi Tanpınar'),
  m('Edebiyat','o','“Suç ve Ceza” romanının yazarı kimdir?','Fyodor Dostoyevski','Lev Tolstoy','Anton Çehov','Aleksandr Puşkin'),
  m('Edebiyat','o','“Çalıkuşu” romanının yazarı kimdir?','Reşat Nuri Güntekin','Halide Edib Adıvar','Refik Halit Karay','Ömer Seyfettin'),
  m('Edebiyat','o','“Sinekli Bakkal” romanının yazarı kimdir?','Halide Edib Adıvar','Reşat Nuri Güntekin','Peyami Safa','Yakup Kadri Karaosmanoğlu'),
  m('Edebiyat','o','“Beyaz Kale” romanının yazarı kimdir?','Orhan Pamuk','Elif Şafak','Latife Tekin','Ahmet Ümit'),
  m('Edebiyat','o','“Savaş ve Barış” romanının yazarı kimdir?','Lev Tolstoy','Fyodor Dostoyevski','Maksim Gorki','Ivan Turgenyev'),
  m('Edebiyat','o','“1984” romanının yazarı kimdir?','George Orwell','Aldous Huxley','Ray Bradbury','H. G. Wells'),
  m('Edebiyat','o','“Sefiller” romanının yazarı kimdir?','Victor Hugo','Honoré de Balzac','Gustave Flaubert','Alexandre Dumas'),
  m('Edebiyat','o','“Yüzyıllık Yalnızlık” romanının yazarı kimdir?','Gabriel García Márquez','Jorge Luis Borges','Mario Vargas Llosa','Isabel Allende'),
  m('Edebiyat','o','“Dönüşüm” adlı eserin yazarı kimdir?','Franz Kafka','Thomas Mann','Hermann Hesse','Stefan Zweig'),
  m('Edebiyat','o','“Memleketimden İnsan Manzaraları” adlı eserin yazarı kimdir?','Nâzım Hikmet','Orhan Veli','Cahit Sıtkı Tarancı','Ahmed Arif'),
  m('Edebiyat','z','“Mesnevi” kimin eseridir?','Mevlânâ','Yunus Emre','Nesimi','Fuzuli'),
  m('Edebiyat','z','“Divan-ı Hikmet” kime aittir?','Ahmed Yesevi','Yunus Emre','Mevlânâ','Hacı Bektaş Veli'),
  m('Edebiyat','z','“Hüsn ü Aşk” mesnevisinin yazarı kimdir?','Şeyh Galip','Fuzuli','Nef’i','Nabi'),
  m('Edebiyat','z','“Kutadgu Bilig” adlı eserin yazarı kimdir?','Yusuf Has Hacib','Kaşgarlı Mahmud','Ahmed Yesevi','Edip Ahmed Yükneki'),
  m('Edebiyat','z','Türk dilinin ilk sözlüğü sayılan “Divanü Lügati’t-Türk”ü kim yazmıştır?','Kaşgarlı Mahmud','Yusuf Has Hacib','Ahmed Yesevi','Dede Korkut'),
  m('Edebiyat','z','“İlahi Komedya”nın yazarı kimdir?','Dante Alighieri','Petrarca','Boccaccio','Machiavelli'),
  m('Edebiyat','z','Aşağıdakilerden hangisi Nobel Edebiyat Ödülü kazanmış bir Türk yazardır?','Orhan Pamuk','Yaşar Kemal','Nâzım Hikmet','Elif Şafak'),
  n('Edebiyat','o','İstiklal Marşı kaç kıtadan oluşur?',10,'kıta'),
  n('Edebiyat','z','Orhan Pamuk Nobel Edebiyat Ödülü’nü hangi yıl kazandı?',2006,'yılı',15),

  /* ================= Teknoloji ================= */
  m('Teknoloji','k','Aşağıdakilerden hangisi bir web tarayıcısıdır?','Firefox','Linux','Python','Excel'),
  m('Teknoloji','k','iPhone’u hangi şirket üretir?','Apple','Samsung','Google','Microsoft'),
  m('Teknoloji','k','“WWW” kısaltması neyin açılımıdır?','World Wide Web','Wide World Web','Web World Wide','World Web Wide'),
  m('Teknoloji','o','Android işletim sistemini hangi şirket geliştirir?','Google','Apple','Microsoft','Nokia'),
  m('Teknoloji','o','Instagram hangi şirketin bünyesindedir?','Meta','Google','Microsoft','Amazon'),
  m('Teknoloji','o','CPU kısaltması neyi ifade eder?','Merkezi işlem birimi','Güç kaynağı','Depolama birimi','Ekran kartı'),
  m('Teknoloji','o','USB kısaltmasının açılımı nedir?','Universal Serial Bus','United System Board','Unique Serial Byte','Universal System Bus'),
  m('Teknoloji','o','HTML ne için kullanılır?','Web sayfasının yapısını oluşturmak','Veritabanı yönetmek','Video düzenlemek','Ağ güvenliği sağlamak'),
  m('Teknoloji','o','Alan adlarını IP adreslerine çeviren sistemin adı nedir?','DNS','HTTP','FTP','SMTP'),
  m('Teknoloji','o','ChatGPT hangi şirket tarafından geliştirilmiştir?','OpenAI','Google','Meta','Microsoft'),
  m('Teknoloji','o','Kablosuz yerel ağ bağlantısı için kullanılan teknoloji hangisidir?','Wi-Fi','HDMI','USB','SSD'),
  m('Teknoloji','z','Dünyayı saran ağ olan World Wide Web’i kim geliştirmiştir?','Tim Berners-Lee','Vint Cerf','Bill Gates','Steve Jobs'),
  m('Teknoloji','z','İlk programcı olarak kabul edilen kişi kimdir?','Ada Lovelace','Grace Hopper','Alan Turing','Charles Babbage'),
  m('Teknoloji','z','Linux çekirdeğini kim geliştirmiştir?','Linus Torvalds','Richard Stallman','Dennis Ritchie','Ken Thompson'),
  m('Teknoloji','z','Python programlama dilinin yaratıcısı kimdir?','Guido van Rossum','James Gosling','Bjarne Stroustrup','Brendan Eich'),
  m('Teknoloji','z','Bitcoin’in yaratıcısı olarak bilinen takma ad hangisidir?','Satoshi Nakamoto','Vitalik Buterin','Hal Finney','Nick Szabo'),
  m('Teknoloji','z','Akıllı telefonlarda en yaygın kullanılan işlemci mimarisi hangisidir?','ARM','x86','RISC-V','MIPS'),
  m('Teknoloji','z','QR kod hangi ülkede icat edilmiştir?','Japonya','ABD','Güney Kore','Almanya'),
  m('Teknoloji','z','Enigma şifresini çözen çalışmalarla da tanınan, bilgisayar biliminin öncülerinden matematikçi kimdir?','Alan Turing','Charles Babbage','John von Neumann','Claude Shannon'),
  n('Teknoloji','k','Bir bayt kaç bitten oluşur?',8,'bit'),
  n('Teknoloji','o','Bir klavyede F1’den F12’ye kadar kaç fonksiyon tuşu vardır?',12,'tuş'),
  n('Teknoloji','o','İlk iPhone hangi yıl tanıtıldı?',2007,'yılı',15),
  n('Teknoloji','o','Google hangi yıl kuruldu?',1998,'yılı',15),
  n('Teknoloji','z','Wikipedia hangi yıl kuruldu?',2001,'yılı',15),
  n('Teknoloji','z','YouTube hangi yıl kuruldu?',2005,'yılı',15),
  n('Teknoloji','z','Facebook hangi yıl kuruldu?',2004,'yılı',15),

  /* ================= Yemek ================= */
  m('Yemek','k','Guacamole’nin ana malzemesi nedir?','Avokado','Domates','Nohut','Patlıcan'),
  m('Yemek','k','Humus hangi baklagilden yapılır?','Nohut','Mercimek','Fasulye','Bezelye'),
  m('Yemek','k','Pizza hangi ülkenin mutfağından çıkmıştır?','İtalya','Yunanistan','Fransa','İspanya'),
  m('Yemek','k','Suşide geleneksel olarak hangi tahıl kullanılır?','Pirinç','Buğday','Arpa','Mısır'),
  m('Yemek','k','Baklava aşağıdakilerden hangisiyle yapılır?','Yufka ve şerbet','Bulgur ve yoğurt','Pirinç ve süt','Mısır ve peynir'),
  m('Yemek','o','Beyran çorbası hangi şehrimizle özdeşleşmiştir?','Gaziantep','Trabzon','Edirne','Sinop'),
  m('Yemek','o','İskender kebap hangi şehrimizle anılır?','Bursa','Adana','Şanlıurfa','Konya'),
  m('Yemek','o','Paella hangi ülkenin yemeğidir?','İspanya','İtalya','Meksika','Yunanistan'),
  m('Yemek','o','Tacos hangi ülke mutfağına aittir?','Meksika','İspanya','Brezilya','Peru'),
  m('Yemek','o','Kimchi hangi ülkenin geleneksel yemeğidir?','Güney Kore','Japonya','Çin','Tayland'),
  m('Yemek','o','Suşide kullanılan yosun türünün adı nedir?','Nori','Wakame','Kombu','Hijiki'),
  m('Yemek','o','Dünyanın en pahalı baharatı olarak bilinen baharat hangisidir?','Safran','Karabiber','Kimyon','Tarçın'),
  m('Yemek','o','Tarhana nedir?','Çorba','Tatlı','Salata','İçecek'),
  m('Yemek','o','Ayranın ana maddesi nedir?','Yoğurt','Süt','Peynir','Kefir'),
  m('Yemek','z','Geleneksel mozzarella hangi hayvanın sütünden yapılır?','Manda','Koyun','Keçi','İnek'),
  m('Yemek','z','Gazpacho nasıl bir yemektir?','Soğuk domates çorbası','Sıcak balık yemeği','Tatlı','Hamur işi'),
  m('Yemek','z','Tiramisu hangi ülkenin tatlısıdır?','İtalya','Fransa','İspanya','Avusturya'),
  m('Yemek','z','Wasabi hangi ülke mutfağında yaygın olarak kullanılır?','Japonya','Çin','Hindistan','Tayland'),
  m('Yemek','z','“Umami” hangi tadı ifade eder?','Et suyu gibi lezzetli tat','Acı','Ekşi','Tatlı'),
  n('Yemek','o','Katı haşlanmış yumurta yaklaşık kaç dakikada pişer?',10,'dakika'),
  n('Yemek','z','Türk kahvesi kültürü UNESCO listesine hangi yıl girdi?',2013,'yılı',10),

  /* ================= Sanat ================= */
  m('Sanat','k','Mona Lisa tablosunu kim yapmıştır?','Leonardo da Vinci','Michelangelo','Rafael','Botticelli'),
  m('Sanat','k','“Yıldızlı Gece” tablosunun ressamı kimdir?','Vincent van Gogh','Claude Monet','Pablo Picasso','Salvador Dalí'),
  m('Sanat','o','“Kaplumbağa Terbiyecisi” tablosunun ressamı kimdir?','Osman Hamdi Bey','Şeker Ahmet Paşa','Hoca Ali Rıza','İbrahim Çallı'),
  m('Sanat','o','Süleymaniye Camii’nin mimarı kimdir?','Mimar Sinan','Sedefkâr Mehmed Ağa','Mimar Kemaleddin','Davud Ağa'),
  m('Sanat','o','“Çığlık” tablosunun ressamı kimdir?','Edvard Munch','Gustav Klimt','Egon Schiele','Paul Gauguin'),
  m('Sanat','o','“Guernica” tablosunun ressamı kimdir?','Pablo Picasso','Salvador Dalí','Joan Miró','Francisco Goya'),
  m('Sanat','o','“Öpücük” tablosuyla tanınan ressam kimdir?','Gustav Klimt','Claude Monet','Paul Cézanne','Edgar Degas'),
  m('Sanat','o','“Düşünen Adam” heykelini kim yapmıştır?','Auguste Rodin','Michelangelo','Donatello','Bernini'),
  m('Sanat','o','“Son Akşam Yemeği” freskinin sanatçısı kimdir?','Leonardo da Vinci','Michelangelo','Rafael','Caravaggio'),
  m('Sanat','o','Selimiye Camii hangi şehrimizdedir?','Edirne','İstanbul','Bursa','Konya'),
  m('Sanat','o','Ebru sanatı nasıl yapılır?','Su yüzeyindeki boyayla','Taş oyarak','Ahşap işleyerek','Cam üfleyerek'),
  m('Sanat','z','Salvador Dalí hangi akımın en tanınmış temsilcilerindendir?','Sürrealizm','Kübizm','Empresyonizm','Pop Art'),
  m('Sanat','z','Pablo Picasso hangi akımın öncülerindendir?','Kübizm','Sürrealizm','Empresyonizm','Barok'),
  m('Sanat','z','Mimar Sinan’ın “ustalık eserim” dediği yapı hangisidir?','Selimiye Camii','Süleymaniye Camii','Şehzade Camii','Sultanahmet Camii'),
  m('Sanat','z','Sultanahmet (Mavi) Camii’nin mimarı kimdir?','Sedefkâr Mehmed Ağa','Mimar Sinan','Davud Ağa','Mimar Vedat Tek'),
  m('Sanat','z','Ayasofya’nın mimarları kimlerdir?','Anthemios ile İsidoros','Mimar Sinan ile Davud Ağa','Vitruvius ile Palladio','Brunelleschi ile Alberti'),
  m('Sanat','z','Sistina Şapeli’nin tavan resimlerini kim yapmıştır?','Michelangelo','Leonardo da Vinci','Rafael','Botticelli'),
  m('Sanat','z','“Venüs’ün Doğuşu” tablosunun ressamı kimdir?','Botticelli','Tiziano','Rafael','Caravaggio'),
  m('Sanat','z','Çinisiyle ünlü, Osmanlı’nın seramik merkezi olan şehrimiz hangisidir?','İznik','Edirne','Sinop','Amasya'),
  m('Sanat','z','Empresyonizm akımına adını veren tablo hangi sanatçıya aittir?','Claude Monet','Edouard Manet','Auguste Renoir','Edgar Degas'),
  n('Sanat','o','Van Gogh kaç yıl yaşamıştır?',37,'yıl'),
  n('Sanat','z','“Yıldızlı Gece” hangi yıl yapılmıştır?',1889,'yılı',40),
  n('Sanat','z','Michelangelo’nun Davut heykeli yaklaşık kaç metre yüksekliğindedir?',5,'metre'),
  n('Sanat','z','Özgürlük Heykeli hangi yıl açılmıştır?',1886,'yılı',40),

  /* ================= Doğa ================= */
  m('Doğa','k','Dünyanın en büyük hayvanı hangisidir?','Mavi balina','Afrika fili','Balina köpekbalığı','Zürafa'),
  m('Doğa','k','Kanguru hangi kıtaya özgüdür?','Avustralya','Afrika','Güney Amerika','Asya'),
  m('Doğa','k','Aşağıdakilerden hangisi memeli değildir?','Penguen','Yunus','Yarasa','Balina'),
  m('Doğa','k','Panda ne ile beslenir?','Bambu','Balık','Et','Böcek'),
  m('Doğa','k','Aşağıdakilerden hangisi uçamayan bir kuştur?','Devekuşu','Kartal','Leylek','Serçe'),
  m('Doğa','o','Dünyanın en hızlı kara hayvanı hangisidir?','Çita','Aslan','Antilop','At'),
  m('Doğa','o','Kış uykusuna yatan hayvan hangisidir?','Ayı','Kurt','Tilki','Geyik'),
  m('Doğa','o','Yunuslar hangi hayvan sınıfındandır?','Memeli','Balık','Sürüngen','Kuş'),
  m('Doğa','o','Kelebeğin larva evresine ne denir?','Tırtıl','Pupa','Kurtçuk','Kozalak'),
  m('Doğa','o','Dünyanın en uzun boylu hayvanı hangisidir?','Zürafa','Fil','Deve','Avustralya devekuşu'),
  m('Doğa','o','Dünyanın en büyük kara hayvanı hangisidir?','Afrika fili','Gergedan','Su aygırı','Zürafa'),
  m('Doğa','o','Kamuflaj yeteneğiyle ünlü, rengini değiştirebilen hayvan hangisidir?','Bukalemun','Semender','Kertenkele','Yılan'),
  m('Doğa','z','Hangi hayvanın parmak izi insan parmak izine çok benzer?','Koala','Şempanze','Goril','Orangutan'),
  m('Doğa','z','Aşağıdakilerden hangisi yumurtlayan bir memelidir?','Ornitorenk','Yarasa','Yunus','Kunduz'),
  m('Doğa','z','Türkiye kıyılarında yaşayan ve nesli tehlike altındaki deniz memelisi hangisidir?','Akdeniz foku','Mavi balina','Beluga','Deniz aslanı'),
  m('Doğa','z','Bitkilerin yeşil rengini veren pigment hangisidir?','Klorofil','Karoten','Melanin','Hemoglobin'),
  m('Doğa','z','Dünyanın en uzun boylu ağaç türü hangisidir?','Kıyı sekoyası','Meşe','Çam','Söğüt'),
  m('Doğa','z','Dünyanın en büyük mercan resifi olan Büyük Set Resifi hangi ülkenin kıyısındadır?','Avustralya','Brezilya','Endonezya','Meksika'),
  n('Doğa','k','Örümceklerin kaç bacağı vardır?',8,'bacak'),
  n('Doğa','k','Bir böceğin kaç bacağı vardır?',6,'bacak'),
  n('Doğa','z','Bir ahtapotun kaç kalbi vardır?',3,'kalp'),
  n('Doğa','z','Mavi balina en fazla yaklaşık kaç metre uzunluğa ulaşır?',30,'metre'),
  n('Doğa','z','Bir Afrika fili yaklaşık kaç ay gebe kalır?',22,'ay'),

  /* ================= Dil ve deyimler ================= */
  m('Dil ve deyimler','k','“Ağzı kulaklarına varmak” deyimi ne anlama gelir?','Çok sevinmek','Çok konuşmak','Çok şaşırmak','Dedikodu yapmak'),
  m('Dil ve deyimler','k','“Burnu havada olmak” deyimi ne anlama gelir?','Kibirli olmak','Hasta olmak','Meraklı olmak','Neşeli olmak'),
  m('Dil ve deyimler','o','“Göz yummak” deyimi ne anlama gelir?','Bir kusuru görmezden gelmek','Uyumak','Ağlamak','Dikkatle bakmak'),
  m('Dil ve deyimler','o','“Kulak misafiri olmak” deyimi ne anlama gelir?','Gizlice konuşulanı duymak','Misafir ağırlamak','Dinlemeyi bilmemek','Kulak ağrısı çekmek'),
  m('Dil ve deyimler','o','“Ağzında bakla ıslanmamak” deyimi ne anlama gelir?','Sır saklayamamak','Çok yemek yemek','Konuşamamak','Susuz kalmak'),
  m('Dil ve deyimler','o','“Yüzü kızarmak” deyimi ne anlama gelir?','Utanmak','Kızmak','Hasta olmak','Sevinmek'),
  m('Dil ve deyimler','o','“Havadan sudan konuşmak” ne anlama gelir?','Önemsiz şeylerden söz etmek','Hava durumunu anlatmak','Su içerek konuşmak','Yüksek sesle konuşmak'),
  m('Dil ve deyimler','o','“Damlaya damlaya göl olur” atasözü neyi anlatır?','Küçük birikimler zamanla büyür','Yağmur çok yağar','Göller kurur','Su çok kıymetlidir'),
  m('Dil ve deyimler','o','“Ayağını yorganına göre uzat” atasözü ne öğütler?','Gelirine göre harcamayı','Rahat uyumayı','Sıcak tutmayı','Sabırlı olmayı'),
  m('Dil ve deyimler','o','“Bir elin nesi var, iki elin sesi var” atasözü neyi anlatır?','İşbirliğinin gücünü','Yalnızlığı','Müziği','Dua etmeyi'),
  m('Dil ve deyimler','o','“Dilinin ucunda olmak” deyimi ne anlama gelir?','Tam hatırlayamamak','Çok konuşmak','Sır tutmak','Yalan söylemek'),
  m('Dil ve deyimler','z','Aşağıdaki harflerden hangisi Türk alfabesinde yoktur?','X','Ç','Ş','Ğ'),
  m('Dil ve deyimler','z','“Cömert” sözcüğünün zıt anlamlısı hangisidir?','Cimri','Zengin','Fakir','Kibar'),
  m('Dil ve deyimler','z','Bilinen en eski Türkçe yazılı metinler hangileridir?','Orhun Yazıtları','Kutadgu Bilig','Dede Korkut Hikâyeleri','Divanü Lügati’t-Türk'),
  m('Dil ve deyimler','z','Orhun Yazıtları’nı 1893’te ilk çözen dilbilimci kimdir?','Vilhelm Thomsen','Kaşgarlı Mahmud','Hüseyin Namık Orkun','Muharrem Ergin'),
  m('Dil ve deyimler','z','Dünyada ana dili olarak en çok konuşulan dil hangisidir?','Mandarin Çincesi','İngilizce','İspanyolca','Hintçe'),
  m('Dil ve deyimler','z','Aşağıdaki ülkelerden hangisinin resmî dili Portekizce değildir?','Arjantin','Brezilya','Portekiz','Angola'),
  m('Dil ve deyimler','z','Aşağıdakilerden hangisi bir yansıma sözcüktür?','Şırıl şırıl','Güzel','Koşmak','Kitap'),
  n('Dil ve deyimler','k','Türk alfabesinde kaç harf vardır?',29,'harf'),
  n('Dil ve deyimler','o','İngiliz alfabesinde kaç harf vardır?',26,'harf'),
  n('Dil ve deyimler','o','Türkçede kaç sesli (ünlü) harf vardır?',8,'harf'),
  n('Dil ve deyimler','o','Türkçede kaç sessiz (ünsüz) harf vardır?',21,'harf'),
  n('Dil ve deyimler','z','Yunan alfabesinde kaç harf vardır?',24,'harf'),
  n('Dil ve deyimler','z','Dünyada yaklaşık kaç dil konuşulmaktadır?',7000,'dil')
];

// İngilizce kategorisi ayrı dosyada; “Karışık” modda yer almaz, yalnızca seçilince gelir.
export const QUESTIONS = [...BASE, ...MORE1, ...MORE2, ...MORE3, ...EN, ...EN2];
